### ISSUE TITLE
RFC 7230: ABNF for http(s) URIs contains fragment

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#103]
See https://www.rfc-editor.org/errata/eid4251 and https://www.rfc-editor.org/errata/eid4252

**Comment by reschke** [comment]
HTTPBIS issue that introduced the fragment identifiers into the ABNF: https://trac.ietf.org/trac/httpbis/ticket/451

**Comment by mnot** [comment]
Seems reasonable, although some people who refer to the ABNF might be surprised. Can we add a paragraph directly below each ABNF rule that points out that fragments are allowed, giving some examples?

**Comment by reschke** [comment]
See pull request in https://github.com/httpwg/http-core/pull/106
