### ISSUE TITLE
index 

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#1038]
~~~
<!-- [rfced] Should any of the following terms be added to the Index?

:authority
accept-ext
accept-params
Alt-Svc header field
Cache-Control header field
charset names
CN-ID
Cookie header field
DNS-ID
host (ABNF element)
identity coding
identity token 
IP-ID
Keep-Alive header field
relative-part
path-abempty
Proxy-Connection header field
Set-Cookie header field
subjectAltName
Transfer-Encoding header field
US-ASCII
-->
~~~

**Comment by mnot** [comment]
No strong feelings; none of these look necessary to me.

**Comment by MikeBishop** [comment]
I'd think indexing the header field definitions is an all-or-none decision.  It doesn't make sense to have only some header fields (of those defined in this document, anyway) in the index.

**Comment by reschke** [comment]
@MikeBishop  - I think we are consistent. For instance, "Transfer-Encoding" header field is defined in MESSAGING, not SEMANTICS.

**Comment by reschke** [comment]
I believe there's nothing to do here.
