### ISSUE TITLE
inclusive language

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#1040]
~~~
<!-- [rfced] Please review the "Inclusive Language" portion of the
     online Style Guide
     <https://www.rfc-editor.org/styleguide/part2/#inclusive_language>
     and let us know if any changes are needed.  For example, please
     consider whether the following should be updated: "black hole",
     "webmaster", and "whitespace".
-->
~~~

**Comment by royfielding** [comment]
I already did this one in our master, except i ignored the comment on whitespace which is just silly.

**Comment by royfielding** [comment]
this was done in https://github.com/httpwg/http-core/commit/9f1970e7a4de0615d42b5470879e9769e967e9c5
so do we just need to remove the comment, or add an [auth] comment?

**Comment by reschke** [comment]
> so do we just need to remove the comment, or add an [auth] comment?

We can tell the RPC that the comment is resolved.
