### ISSUE TITLE
cite h2bis

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#1045]
This is in AUTH48 as well, so we can upgrade the 7540 citation.

**Comment by martinthomson** [comment]
You can cite RFC 9113 if you like, though that won't work just yet (and nor does it have a date).

**Comment by reschke** [comment]
@MikeBishop - you may want to do the same thing in HTTP/3!

**Comment by MikeBishop** [comment]
Covered in https://github.com/quicwg/base-drafts/pull/4957 already.
