### ISSUE TITLE
Pragma status

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#1047]
[Caching 5.4](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#field.pragma) says that Pragma is deprecated, but the [IANA table](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#field.name.registration) doesn't reflect this.

**Comment by reschke** [comment]
the really important bit is that IANA needs to update the registry...
