### ISSUE TITLE
`Vary: Range` in responses to range requests: Necessary?

### ISSUE THREAD

**Issue by mpdude** [httpwg/http-core#1055]
Dear httpwg,

congratulations on completing RFC 9110 and thank you for your efforts put into it! You've added a dedicated section for Range Requests, and I have a question on that.

In [section 15.3.7](https://www.rfc-editor.org/rfc/rfc9110#section-15.3.7), it says:

> A server that generates a 206 response MUST generate the following header fields, in addition to those required in the subsections below, if the field would have been sent in a [200 (OK)](https://www.rfc-editor.org/rfc/rfc9110#status.200) response to the same request: [Date](https://www.rfc-editor.org/rfc/rfc9110#field.date), Cache-Control, [ETag](https://www.rfc-editor.org/rfc/rfc9110#field.etag), Expires, [Content-Location](https://www.rfc-editor.org/rfc/rfc9110#field.content-location), and [Vary](https://www.rfc-editor.org/rfc/rfc9110#field.vary).

Assume I have a response with code 200 that is either heuristically cacheable or has an explicit cache-control header, but does not contain a `Vary` header.

What should happen if the client performs the same request again, but this time includes a `Range` header?

Should the 206 contain `Vary: Range`, since the body of the response depends on (and changes with) this value? Or are caches supposed to know about the special semantics of 206 themselves and take `Range` into account accordingly?

**Comment by royfielding** [comment]
The 206 would not contain a Vary: Range because the selected representation in not influenced by Range -- only the content extracted from that representation. And, yes, caches have to know that in order to make use of 206 responses.
