### ISSUE TITLE
Release dates of papers

### ISSUE THREAD

**Issue by frknl** [httpwg/http-core#1091]
While this link containing latests draft released June 9, how it's becoming possible for the RFC 9110's release date is June 6?  Also this draft doesn't listed in IETF datatracker. The latest revision is 19 but they are not same.
https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html

**Comment by reschke** [comment]
It's not "released" (and it will not). It's simply a timestamp of file generation.
