### ISSUE TITLE
Sending a Validation Request and secondary cache keys

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#110]
Caching [says](https://httpwg.org/specs/rfc7234.html#validation.sent):

> One or more entity-tags, indicating one or more stored responses, can be used in an If-None-Match header field for response validation, or in an If-Match or If-Range header field for representation selection (i.e., the client is referring specifically to one or more previously obtained representations with the listed entity-tags).

Can the cache send any old entity-tag it has stored for the URL in these headers, or must it only do it for those that can be _selected_ by the incoming request, as per the secondary cache key algorithm?

Also, this section uses "selected" in a different meaning; that should probably be changed to avoid confusion.

**Comment by mnot** [comment]
I *think* it needs to constrain it to the selected stored responses.

**Comment by royfielding** [comment]
We need to be careful to include the case where an upstream cache (or UA) has sent a conditional request (perhaps with some of its own stored etags) and this cache is forwarding them along.

**Comment by mnot** [comment]
## 4.3.1. Sending a Validation Request

When sending a conditional request for validation, a cache updates the request it is attempting to satisfy with one or more precondition header fields. These contain validator metadata sourced from the stored response(s) that have the same cache key (both primary and secondary, as applicable).

The precondition header fields are then compared by recipients to determine whether any stored response is equivalent to a current representation of the resource.

[rest as before]

**Comment by royfielding** [comment]
Isn't this presuming the validation is part of an upstream request? What if the cache is auto-refreshing stored responses during idle time?

Maybe we should define these as separate cases?
