### ISSUE TITLE
upgrade example shouldn't use HTTP/2.0

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#112]
...because that might be misleading given that HTTP/2 now exists.

**Comment by MikeBishop** [comment]
Make it `h2c`.  😉

**Comment by royfielding** [comment]
That is the mechanism and syntax for upgrading to h2 within an HTTP/1.1 connection, so I see no reason to change it.  Whether it is h2 or h2c depends on TLS being underneath (and a twisted view of history).  This is the kind of thing one might do over a local socket or localhost connection.

**Comment by mnot** [comment]
Yes, this should be changed; it will confuse some.

Suggest `websocket` since that's actually in use.

**Comment by royfielding** [comment]
Personally, since you guys don't seem to understand that it is both a real world example and the correct token to use (in HTTP/1.1), I think it is useful as is.  But if it really makes the h2 bubble happier, go ahead and change it to websocket.  It is just an example.
