### ISSUE TITLE
Defining Trailer header field separately from chunked trailers

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#117]
While rearranging the sections, we decided to make the header field definition of Trailer be separate from the syntactic definition of chunked trailer parts. However, this exposed a lack of such definition text (aside from the ABNF) in the past RFCs.

The following text (currently in crefs) has been added to the new section on "Trailer" in Semantics around the existing ABNF for the field:

> The "Trailer" header field in a message indicates fields that the sender anticipates sending after the message header block (i.e., during or after the payload is sent). This is typically used to supply metadata that might be dynamically generated while the data is sent, such as a message integrity check, digital signature, or post-processing status.

> How, where, and when trailer fields might be sent depends on both the protocol in use (HTTP version and/or transfer coding) and the semantics of each named header field. Many header fields cannot be processed outside the header section because their evaluation is necessary for message routing, authentication, or configuration prior to receiving the representation data.

**Comment by mnot** [comment]
I like this. See related proposal in #16.

**Comment by reschke** [comment]
Maybe also mention timing information (because that seems to be the first use case in browsers being implemented)?

**Comment by royfielding** [comment]
Completed along with the changes for #219
