### ISSUE TITLE
Defining Content-Length independently from its use in HTTP/1.1 framing

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#118]
We decided to move the version-independent parts of the definition of Content-Length to Semantics, but that calls for some new text to explain its semantics in general.

For now, we have added (in crefs) the following text to the section on "Content-Length" in Semantics:

> The "Content-Length" header field indicates the number of data octets (body length) for the representation. In some cases, Content-Length is used to define or estimate message framing.

**Comment by mnot** [comment]
s/representation/representation data/?
