### ISSUE TITLE
Include RFC 7694

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#119]
From the abstract:

> In HTTP, content codings allow for payload encodings such as for compression or integrity checks. In particular, the "gzip" content coding is widely used for payload data sent in response messages.

> Content codings can be used in request messages as well; however, discoverability is not on par with response messages. This document extends the HTTP "Accept-Encoding" header field for use in responses, to indicate the content codings that are supported in requests.

**Comment by mnot** [comment]
Discussed in Montreal; support for doing this.
