### ISSUE TITLE
RFC 7231 content-type charset param case sensitivity

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#13]
https://greenbytes.de/tech/webdav/rfc7231.html#media.type

> The type, subtype, and parameter name tokens are case-insensitive. Parameter values might or might not be case-sensitive, depending on the semantics of the parameter name. The presence or absence of a parameter might be significant to the processing of a media-type, depending on its definition within the media type registry.

...it then continues showing examples that imply that the charset value is case-insensitive (which is correct), but it would be helpful if it cited RFC 2046 which defines charset's case  sensitivity.

**Comment by royfielding** [comment]
We define charset in the next section, which already references the normative specs (that displaced RFC 2046 as the formal definition).

**Comment by reschke** [comment]
See https://github.com/httpwg/http-core/pull/113
