### ISSUE TITLE
Upgrading Weak ETags

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#132]
IIRC one of the use cases that was always intended for conditional requests was to allow a weak ETag to be "upgraded" to a strong once once the origin becomes certain that it can identify changes.

However, the text in [7234 4.3.4](https://httpwg.org/specs/rfc7234.html#freshening.responses) doesn't account for this case.

Should it?

Regardless, 4.3.4 should explicitly identify the comparison function being used.

I'll write some browser and intermediary cache tests.

**Comment by mnot** [comment]
(issue found by Frank <fau@riseup.net>)

**Comment by mnot** [comment]
PIng @royfielding - am I misremembering here? E.g., can a server send a `W/"foo"` and then update it to a strong `"foo"` ETag in a `304`?

**Comment by mnot** [comment]
Discussed in Bangkok. Needs research.

**Comment by mnot** [comment]
@jgettys does this ring any bells?

**Comment by mnot** [comment]
Closing due to lack of information. If anyone has any, please say so.

**Comment by royfielding** [comment]
It doesn't help much, but I found an old Apache httpd bug report

  https://bz.apache.org/bugzilla/show_bug.cgi?id=42987
