### ISSUE TITLE
Be explicit about string case sensitivity

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#133]
Should we just adopt [RFC7405](https://tools.ietf.org/html/rfc7405) wherever we use a string?

**Comment by reschke** [comment]
Yes, I think that's what the IESG wants us to do. (We were directed to use it in alt-svc)

**Comment by mnot** [comment]
I've started a branch (mnot-133).

Question: do we want to convert things like this:

> HTTP-name = %x48.54.54.50 ; HTTP

into:

> http-name: %s"HTTP"

? We do that a fair amount for case-sensitive strings.

**Comment by royfielding** [comment]
+1

**Comment by mnot** [comment]
OK. I'll leave my branch there if you want to start with it; otherwise feel free to delete it.

**Comment by reschke** [comment]
FWIW, I'd prefer to do this only in the places where the string actually is case-sensitive.

**Comment by reschke** [comment]
I guess I forgot to close the ticket.
