### ISSUE TITLE
Clarify the exact format of a 100 response

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#134]
E.g. is it sufficient to include just the first line?

What about headers such as Server, Date?

Is the trailing \r\n mandatory?

**Comment by mnot** [comment]
Things like trailing /r/n should be apparent elsewhere; if they're not, please file a separate bug.

We generally shy away from mandating particular headers being present anywhere. A 100 is a bit unusual in that it's quite plausible that it would have an empty header set, and that might be worth pointing out.

**Comment by wenbozhu** [comment]
Agreed about the trailing \r\n.

FWIW, I checked all the "default' headers our server sends, and decided to keep server/date headers for the initial 100 response.
