### ISSUE TITLE
Serializing a header line

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#137]
In https://github.com/web-platform-tests/wpt/issues/7567 we discovered that browsers serialize request header lines differently, with Chrome not serializing a space after the colon if the value is empty.

Presumably this only affects H/1 and I'm not sure how that relates to HTTP Core, but I do think it's worth documenting somewhere. Only alternative I can think of is Fetch, but thus far that's stayed mostly clear of requiring particular networky things.

**Comment by reschke** [comment]
Can you elaborate a bit more what you're looking for? The HTTP specs currently do not say anything at all how a client API interacts with the bits on the wire...

**Comment by annevk** [comment]
This isn't really about an API per se, it's about how a request in general is serialized.

**Comment by thc202** [comment]
The issue description has a typo(?), where it says comma it should say colon.

**Comment by annevk** [comment]
Say you have a `Content-Type` header whose value is the empty byte sequence. You can serialize that in various ways, but browsers are aligning on `Content-Type: \r\n` (Chrome omits the 0x20 at the moment).

**Comment by reschke** [comment]
Ah.

The answer is: it doesn't matter. Leading and trailing whitespace in header field values is insignificant.

**Comment by annevk** [comment]
It wasn't really a question, it's a desire for clients to align on "canonicalized" H/1 serialization behavior.

**Comment by reschke** [comment]
Well, it *really* doesn't matter.

There is no HTTP spec issue here.

**Comment by mnot** [comment]
Anne, it's important to realise that "clients" here includes proxies, non-browser UAs, CDNs, etc. Given the variety of behaviour they exhibit, converging on a requirement here is going to be difficult.

As Julian says, this space isn't semantically significant. It would be be better to test recipients to assure that when they receive a space (or not), they behave correctly.

To put it another way - we also don't specify the exact mapping of HTTP messages onto one or more TCP packets, because there are a variety of implementation techniques, optimisations, middle boxes, requirements, etc. And yet it still works. What problem are you trying to solve?

**Comment by annevk** [comment]
Experience in the web platform suggests that in cases such as this you either require a canonical serialization or you require a random serialization (and test for it). In a world with a few dominant clients, it's somewhat inevitable that servers end up requiring things they should not.

https://annevankesteren.nl/2016/05/client-server goes into this to some extent as well.

**Comment by mnot** [comment]
So let's test for it.

**Comment by annevk** [comment]
WPT tests for the "canonical serialization" and all browser implementations have now converged on that. It does seem good to also have that defined. (Similar to how implementations need to consume `\r` (not defined I think) or `\n` as separator, but are encouraged to produce `\r\n`.)

**Comment by reschke** [comment]
> Although the line terminator for the start-line and header fields is the sequence CRLF, a recipient MAY recognize a single LF as a line terminator and ignore any preceding CR.

<https://greenbytes.de/tech/webdav/rfc7230.html#rfc.section.3.5.p.3>

**Comment by reschke** [comment]
For some value of "working".

**Comment by royfielding** [comment]
HTTP does not have a required serialization. What we have is a recommendation:

https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#rfc.section.5.1

`A field value might be preceded and/or followed by optional whitespace (OWS); a single SP preceding the field-value is preferred for consistent readability by humans. The field value does not include any leading or trailing whitespace: OWS occurring before the first non-whitespace octet of the field value or after the last non-whitespace octet of the field value ought to be excluded by parsers when extracting the field value from a header field.`

And it seems to be enough.

**Comment by mcmanus** [comment]
ietf104: there was no interest in the room expressed for making a change based on this issue

**Comment by mnot** [comment]
Closing with no action. @annnvk if you think you can convince people otherwise, please say why here or on list.

**Comment by annevk** [comment]
Browsers are aligned now. As the test demonstrates it's not that hard to write naïve server software that does the wrong thing for clients that serialize differently. From a robustness perspective you'd have to either require randomness from clients or a consistent serialization. I suspect at this point browsers are not going to want to do randomness. Other clients might not want to do the consistent serialization perhaps?

I suspect folks not caring about H/1 is also a factor. I certainly don't care enough to pick this up on the Fetch side, though I would take a PR.
