### ISSUE TITLE
Arguments on CC: private and no-cache

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#138]
both `Cache-Control: private` and `Cache-Control: no-cache` take an optional argument of a list of headers; e.g.,

> Cache-Control: private="foo,bar,baz"

This is AFAICT not implemented anywhere, and I wouldn't be at all surprised if this syntax broke some caches.

We discussed last time around and the resolution was to describe them as "the special handling for the qualified form is not widely implemented." This is misleading; it is NOT implemented, for all intents and purposes.

**Comment by royfielding** [comment]
Both are implemented correctly by Apache httpd's mod_cache: see cache_control_remove() in httpd/modules/cache/cache_util.c.

**Comment by mcmanus** [comment]
in bkk: leave it in based on field implementation - close with no action
