### ISSUE TITLE
2.1 Client/Server Messaging

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#142]
2.1. Client/Server Messaging still is HTTP/1.1-specific. Suggested deletions below:

> A client sends an HTTP request to a server in the form of a request message, beginning with a ~~request-line that includes a~~ method, URI, ~~and protocol version (Section 3 of [Messaging]),~~ followed by header fields containing request modifiers, client information, and representation metadata (Section 5 of [Messaging]), ~~an empty line to indicate the end of the header section,~~ and finally a message body containing the payload body (if any, Section 6 of [Messaging]).
>
> A server responds to a client's request by sending ~~one~~ zero or more non-final and exactly one final HTTP response message~~s~~, each beginning with ~~a status line that includes the protocol version,~~ a success or error code, ~~and textual reason phrase (Section 4 of [Messaging])~~, possibly followed by header fields containing server information, resource metadata, and representation metadata (Section 5 of [Messaging])~~, an empty line to indicate the end of the header section~~, and finally a message body containing the payload body (if any, Section 6 of [Messaging]).
>
> ~~A connection might be used for multiple request/response exchanges, as defined in Section 9.3 of [Messaging]~~.

Also, trailers?

**Comment by MikeBishop** [comment]
Textual reason-phrase is also 1.1 specific.

**Comment by mnot** [comment]
@MikeBishop what's the implication of that? It's already suggested to be deleted.

**Comment by MikeBishop** [comment]
It wasn't in a previous iteration of your suggestion -- see your edit history.  Perhaps we noticed this in parallel?

**Comment by mnot** [comment]
Ah ;)

**Comment by mnot** [comment]
Somewhat related is #159.
