### ISSUE TITLE
Exact separator used when combining header fields

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#148]
Fetch and XMLHttpRequest have for the longest time used comma-followed-by-space (0x2C 0x20) as separator when multiple header fields are combined into a single header field.

This is also what at least Firefox and Chrome do from code inspection:

* https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsHttpHeaderArray.h#256
* https://cs.chromium.org/chromium/src/net/http/http_response_headers.cc?l=465

I think this is because of https://tools.ietf.org/html/rfc2616#section-4.2 encouraging values to start with a single space and folks conceptually still seeing it as multiple values.

Now https://tools.ietf.org/html/rfc7230#section-3.2.2 has a much more explicit definition, which no longer allows for a space as far as I can tell, "breaking" with what implementations are doing.

Most of the time this difference is insignificant, but anything with quoted-string or equivalent will be able to tell what was used if those configuring the headers like to play games.

I'd like HTTP to either allow 0x2C 0x20 as an alternative separator (and have Fetch mandate it for browsers) or simply adopt 0x2C 0x20 as separator for everyone.

I have some tests around this as well, but they only affect APIs, which theoretically could have a different non-HTTP-conformant view, but that'd seem really bad: https://github.com/web-platform-tests/wpt/pull/13471. See https://github.com/whatwg/fetch/pull/813 and https://github.com/whatwg/fetch/issues/752 for further context.

cc @ddragana @MattMenke2 @youennf

**Comment by reschke** [comment]
Whitespace is allowed (and insignificant).

Can you point at the actual difference  between 2616 and 7230 which makes you think that something changed?

**Comment by annevk** [comment]
> Can you point at the actual difference between 2616 and 7230 which makes you think that something changed?

In 2616 the same section states that values can be preceded by whitespace. Whereas in 7230 it only describes how to combine, without any mention of whitespace. Both sections are linked in OP.

> You mean when a quoted-string is broken into several header field instances?

Yeah, also relevant for structured headers, which is how I started stumbling into this. If one client combines with a space, another without, and another with three spaces, you get subtly different strings and possibly room for security bugs.

**Comment by reschke** [comment]
This one?

> The field value MAY be preceded by any amount of LWS, though a single SP is preferred.

That's not specific to recombination.

**Comment by annevk** [comment]
I know...

**Comment by reschke** [comment]
FWIW, the message was invalid wrt that header field already, so "figure out what the sender meant" doesn't make a lot of sense to me.

**Comment by annevk** [comment]
The problem is that "invalid" depends on whether the recipient knows the syntax, which is just broken if the recipient is allowed to combine before forwarding (which makes it "valid").

**Comment by annevk** [comment]
The only sensible thing to do is to always combine before determining validity.

**Comment by mnot** [comment]
See PR. @annevk I haven't done anything to address your later comments; how do folks feel about adding a statement spelling out that consequence, either here, or in Considerations for New Fields?

**Comment by reschke** [comment]
I think explaining the issue would indeed be good.
