### ISSUE TITLE
Nit on CONNECT tunnel forwarding

### ISSUE THREAD

**Issue by tfpauly** [httpwg/http-core#170]
The current section on CONNECT (7.3.6) in the semantics document refers to the proxy forwarding *packets*:

```
The CONNECT method requests that the recipient establish a tunnel to the destination 
origin server identified by the request-target and, if successful, thereafter restrict its 
behavior to blind forwarding of packets, in both directions, until the tunnel is closed.
```

Since the proxy terminates TCP, there is no forwarding of IP packets, but rather the contents of the TCP streams.

**Comment by wtarreau** [comment]
Well spotted! I'd even suggest "to blindly forward bytes in both directions ...". Too often I see people who imagine that packet delimitation is respected on both sides of a proxy and I have to tell them that it's just a uninterrupted stream of bytes that each layer decides to delimit wherever it wants.

**Comment by LPardue** [comment]
I'd say that 7231 is self-consistent with the use of packet in 7230. We should change wording consistently. Or, was this issue raised on the WIP core doc?

**Comment by tfpauly** [comment]
@LPardue this issue is being raised on the WIP core doc. The same text does also exist in 7231, but I consider them to both be in error. While we're updating the text for the core doc, let's fix the text to be clearer.

**Comment by LPardue** [comment]
Thanks for the clarification @tfpauly, that sounds good to me.

**Comment by LPardue** [comment]
Fwiw, the HiNT draft uses the terminology: blind forwarding of IP payloads, UDP datagram payloads and TCP/IP packet payload.

**Comment by MikeBishop** [comment]
HTTP/3 says:
> All DATA frames on the stream correspond to data sent or received on the TCP
> connection. Any DATA frame sent by the client is transmitted by the proxy to the
> TCP server; data received from the TCP server is packaged into DATA frames by
> the proxy. Note that the size and number of TCP segments is not guaranteed to
> map predictably to the size and number of HTTP DATA or QUIC STREAM frames.

**Comment by tfpauly** [comment]
@MikeBishop that text looks good. Something along those lines, but that also works for HTTP/1.1, would be right for this core doc text.

**Comment by reschke** [comment]
Maybe just replace "packets" with "data"?

**Comment by wtarreau** [comment]
So as mentioned above in #327, while having a look at the latest draft I was struck again by this "packets" there, and even forgot about this old issue. Pinging again. I suggest that we change "forwarding of packets" with "forwarding of the byte stream" so that we can close these issues.
