### ISSUE TITLE
Case sensitivity of extension point token ids

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#179]
E.g., range-units. Working on #133, it's not clear.

**Comment by mnot** [comment]
Same question could be asked for transfer-codings, content-codings, cache-control directives, and a few other places. I suspect interop for case-varying things is not great in at least some of these places.

**Comment by wtarreau** [comment]
FWIW in haproxy the match for these is case-insensitive. The rationale here is that the Connection field contains tokens, which are header field names thus are case-insensitive, thus all other ones supposed to be tokens as well are de-facto case-insensitive. From a code perspective it makes sense since the same matching functions are used. BTW, 7234#5.2 says cache-control tokens are case-insensitive.

**Comment by wtarreau** [comment]
However for us the "q=" prefix for preferences is case-sensitive. Maybe that's wrong, I don't know :-/

**Comment by craigpratt** [comment]
I think the reality is that implementations generate (and many servers expect) the bytes range unit in lower case. But I'll have to look at some of the impls I'd looked at when considering the addition of a new range unit...

**Comment by mnot** [comment]
Overview:

- methods: defined as _case-sensitive_
- field names: defined as case-insensitive in messaging, **not** semantics
- transfer-codings: defined as case-insensitive
- content-codings: **not defined**
- language tags: defined as case-insensitive
- range-units: **not defined**
- authentication scheme: defined as case-insensitive
- media types: defined as case-insensitive
- cache directives: defined as case-insensitive

**Comment by mnot** [comment]
Based upon the above, I suggest we:

- [ ] make both content-codings and range-units case-insensitive, as this appears to be an oversight
- [ ] explicitly make field names case-insensitive in semantics

**Comment by mnot** [comment]
Also, in most places the same sentence is used to encourage registration; we should do that where applicable.
