### ISSUE TITLE
Section 5.4 (Host) in Semantics has normative 1.1 requirements

### ISSUE THREAD

**Issue by quasicomputational** [httpwg/http-core#182]
In section 5.4, there are a couple of normative requirements for HTTP/1.1 ("A client MUST send a Host header field in all HTTP/1.1 request messages."; "A client MUST send a Host header field in an HTTP/1.1 request"; "A server MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request"), and it makes two references to the `absolute-form` production, which is defined in the Messaging draft (and hence is a dangling reference in Semantics). Those should probably live in Messaging, and the Semantics document should be more general.

**Comment by reschke** [comment]
The references are dangling because the definition of "Host" moved (was in RFC 7230 before).

**Comment by mnot** [comment]
E.g., 

> A client must send a Host header field in all HTTP/1.1 request messages. 

and 

> A server must respond with a 400 (Bad Request) status code to any HTTP/1.1 request message that lacks a Host header field

**Comment by mnot** [comment]
Looking for a place in messaging to move these. What about 3.3 Reconstructing the Target URI?

**Comment by mnot** [comment]
@royfielding @reschke see question above ^^

**Comment by reschke** [comment]
yes, 3.3 looks ok for that

**Comment by mnot** [comment]
The end of 3.2 seemed like a better fit in the end; PTAL.
