### ISSUE TITLE
Privacy considerations section: reference suggestion

### ISSUE THREAD

**Issue by rvaneijk** [httpwg/http-core#185]
Hi Roy,

Please consider this reference for the privacy considerations section:

Bujlow, T., Carela-Español, V., Solé-Pareta, J., & Barlet-Ros, P. (2017). A survey on web tracking: Mechanisms, implications, and defenses. Proceedings of the IEEE, 105(8), 1476–1510.

Regards,
Rob

**Comment by royfielding** [comment]
https://upcommons.upc.edu/handle/2117/108437

**Comment by martinthomson** [comment]
@englehardt has done a lot of work in this area, so he might have another suggestion.  The referenced paper does cover a good amount of techniques that target HTTP itself, so I'd say that it's worth citing unless a better option presents itself.
