### ISSUE TITLE
Content-Encodings should be self-describing

### ISSUE THREAD

**Issue by bsdphk** [httpwg/http-core#21]
As part of the discussion about the Encryption specification we discussed how Content-Encodings can  or should take parameters from HTTP headers.

The consensus was that they shouldn't.

Whatever information a C-E may need should be inside the body of the object, just like the GZIP header etc.

We should document this as a rule, if we ever do a HTTP[1].ter

**Comment by reschke** [comment]
+1, except for the constraint: "when possible". In the case of the encryption coding, it's clearly necessary to have the actual key information needed for description outside the payload.

**Comment by royfielding** [comment]
we can add something to https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#content.coding.extensibility
