### ISSUE TITLE
byte-range-set definition allows OWS but probably doesn't work in practice

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#212]
In Semantics, the definition of byte-range-set is

    byte-range-set  = 1#( byte-range-spec / suffix-byte-range-spec )

implying that they are a list, like header field values, with optional whitespace.
However, all of the examples are things like

        bytes=0-0,-1
        bytes=500-600,601-999
        bytes=500-700,601-999

and I seriously doubt that recipients are prepared for OWS around the commas.

Related to #196 and #210

**Comment by royfielding** [comment]
Hmm, it does seem to work in practice, at least for spaces between commas.

**Comment by mnot** [comment]
Discussed in Montreal; allow it, and change example to illustrate.

**Comment by royfielding** [comment]
An example has been added in 7594239b46ef2c755b2e91a4572d86707d5f1021
