### ISSUE TITLE
semantics: confusing title "Designing New Header Field Values"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#214]
The title may be technical correct (because it's about the field value syntax), but I believe people looking for this might trip over this.

Proposal: "Designing New Header Fields"

**Comment by annevk** [comment]
Perhaps instead of two separate sections for new header field names and one for header field values they should be grouped as they were before?

The reader is probably looking for the advice on X- and how to define a value at the same time.

**Comment by reschke** [comment]
Ah. I believe we currently do not have any advice on header field *names*, but maybe we should.

**Comment by wtarreau** [comment]
On Thu, Mar 28, 2019 at 10:12:36AM -0700, Julian Reschke wrote:
> Ah. I believe we currently do not have any advice on header field *names*,
> but maybe we should.

+1

**Comment by mcmanus** [comment]
see also #30

**Comment by annevk** [comment]
@reschke I was looking at https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html and I see "Considerations for New Header Fields" which has some advice around X- at least (and is a subsection of "Header Field Names") and "Designing New Header Field Values" which we are discussing here, which is a subset of "Header Field Values". It would make sense to me to group these as a new subsection of "Message Abstraction" dealing with "New Header Fields".

**Comment by reschke** [comment]
Good catch. So this needs reorg in any case.

**Comment by royfielding** [comment]
Yes, the initial edits that put these sections together were limited to preserve the diffs since the reorganized RFC text (to ensure we didn't lose information). I plan to do a more extensive rewrite soon to consolidate sections, make the text more readable, introduce the combined field terms, and remove 1.1 syntax-specific bits from semantics.

**Comment by mnot** [comment]
+1, will take a stab at this.

**Comment by mnot** [comment]
Waiting for #47 resolution.

**Comment by mnot** [comment]
Consolidated those two sections. There are other things to be done (e.g., the misleading "header" nature of the title, other rewrites), but those are other issues (existing or to be raised).
