### ISSUE TITLE
Allow float values for Prefer: wait=<val>

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#227]
(please help redirect if this issue should be discussed elsewhere)

https://tools.ietf.org/html/rfc7240

The wait param currently is integer only (in seconds). Given the wait param is to intended to specify the timeout for server (backend), i.e. with network RTT excluded, sub-second values seems necessary for this header to be practically useful.

@jasnell

**Comment by mnot** [comment]
Probably best to take this to the mailing list; it's not in-scope for any of our current repos.
