### ISSUE TITLE
OPTIONS and empty response

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#235]
<https://greenbytes.de/tech/webdav/rfc7231.html#rfc.section.4.3.7.p.4>:

> A server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

That is incorrect, as the status code could be 204, or the response might come with chunked encoding (even when empty).

This is <https://www.rfc-editor.org/errata/eid5806>.

**Comment by awwright** [comment]
What purpose is this requirement serving? It seems to have the effect of prohibiting `Transfer-Encoding: chunked` with a zero length payload.

Shouldn't RFC 7230, "3.3.3. Message Body Length" be sufficient for determining payload sizes?

**Comment by reschke** [comment]
Agreed. The text makes it sound as if OPTIONS is somehow special. Giving advice might be good, but the use of normative keywords makes this confusing.

The simplest fix might indeed be to remove the sentence.
