### ISSUE TITLE
"final" status code/response should be defined in semantics

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#245]
...that will also allow [Caching] to move a reference.

**Comment by royfielding** [comment]
Section 9.2 (Informational status codes) is already describing these as "final response" and "interim response", and I think we use interim elsewhere for this type of requirement. I would prefer that we stick with the interim/final terminology instead of non-final/final.

**Comment by reschke** [comment]
@royfielding - PR adjusted accordingly.

**Comment by mnot** [comment]
Can this be closed?

**Comment by reschke** [comment]
Yes.
