### ISSUE TITLE
Reduce https and TLS connection discussion to normative references to TLS 1.3

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#263]
We have imported RFC2818, but we still have to reduce the normative text to stuff that isn't already defined by TLS13 (and just add normative references to them as needed).

**Comment by royfielding** [comment]
Wow, actually, TLS13 left this for us to define as being application-specific.

**Comment by mnot** [comment]
Which parts? Do you mean [early data](https://tools.ietf.org/html/rfc8470)?

**Comment by royfielding** [comment]
I mean things like what is the authority, how to compare against certificate, how to validate certificate, and when it's okay to proceed. We may have completed this with my big patch in February.

**Comment by mnot** [comment]
Discussed; @reschke and @mnot to review, if we don't find any leftover text that's redundant can close. E.g., 5.4.3.

**Comment by royfielding** [comment]
Do we still need 2818 stuff in https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#https.initiation

**Comment by reschke** [comment]
Maybe we could ask EKR for review?

**Comment by mnot** [comment]
@ekr?

**Comment by ekr** [comment]
Sorry, I'm kind of missing context. Is the situation that you pulled in a bunch of text from 2818?

**Comment by mnot** [comment]
@ekr yes; this is going to obsolete 2818. Can you look at [2.5.2](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#https.uri), [5.4.2](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#https.origin) and [5.4.3](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#https.initiation)?

**Comment by ekr** [comment]
If we're going to do this, we should also sort out the relationship with 6125. @stpeter

**Comment by mnot** [comment]
See also #404.
