### ISSUE TITLE
Scope of applicability for HTTP extensions

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#265]
When defining new header fields or methods or any other extensions to HTTP, it can be the case that those elements make statements where the scope is unclear.  For instance, in #99 we learned that `Retry-After` often states something that applies to an entire server (or server instance), or maybe a subset of resources, or maybe just the request itself.  HTTP generally assumes that the scope of applicability is a request, but it might also be the specific representation or the resource.

New protocol extensions need to consider carefully what the scope of applicability is for new protocol elements and the information they carry.  Adding text about this to the document (to expand #50) would be good.

**Comment by MikeBishop** [comment]
As another example, the HTTP_1_1_REQUIRED error code in HTTP/2 only makes a definitive statement about the resource, but most implementations I'm aware of treat it as a statement about the origin, albeit not a long-lasting one, in order to avoid a potential latency penalty on every future request.

**Comment by mnot** [comment]
I think this is some text in each of the "Considerations for..." sections. Will do a PR.
