### ISSUE TITLE
Clarify "private" and "public"

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#268]
From <https://www.w3.org/mid/9F36A6F8-0276-4F8C-B063-C4619901EBB1@webfactory.de>:

Both state that a (depending on context private, shared or both types of) "cache MAY store the response and reuse it for later requests, even if the response would normally be non-cacheable".

To my understanding, this does not intend to override the requirements from the "Storing Responses in Caches" section (https://tools.ietf.org/html/draft-ietf-httpbis-cache-06#section-3) altogether. Instead, I would assume that it only refers to the condition "has a status code that is defined as heuristically cacheable" in that section (or, as it was stated in RFC7234, "has a status code that is defined as cacheable by default")? 

Would it make sense to amend the list of conditions in that section, appending to the "the response either..." second-level list: "contains a private response directive if the cache is not shared"?

**Comment by mpdude** [comment]
OP here 👋🏻
