### ISSUE TITLE
Qualified usage of `private` vs. shared caches

### ISSUE THREAD

**Issue by mpdude** [httpwg/http-core#270]
Section 3 of `draft-ietf-httpbis-cache` says:
> A cache MUST NOT store a response to any request, unless: [...]
> – the "private" response directive (see Section 5.2.2.6) does not appear in the response, if the cache is shared.

Section 5.2.2.6 then reads:
>   The "private" response directive indicates that the response message
   is intended for a single user and MUST NOT be stored by a shared
   cache.  [...] 

>   If the private response directive specifies one or more field-names,
   this requirement is limited to the field-values associated with the
   listed response header fields.  That is, a shared cache MUST NOT
   store the specified field-names(s), whereas it MAY store the
   remainder of the response message.

To me, this last paragraph was a surprising read after Section 3 made a rather clear "if it is `private` and the cache is shared, don't cache it" statement.

Maybe it would help to amend the wording in Section 3 to read (emphasis mine)
> the "private" response directive (see Section 5.2.2.6) does not appear _in unqualified form_ in the response, if the cache is shared

**Comment by royfielding** [comment]
Right, though I expect "qualified" or "unqualified" is a little too vague to explain it. Maybe the "private" response directive without a list of field names?

**Comment by mnot** [comment]
Currently, we have:

> if the cache is shared: the "private" response directive is not present in the response (ref to section)

Proposal:

> if the cache is shared: the "private" response directive, if present, allows the response to be stored (possibly with modifications; see ref to section)

**Comment by mpdude** [comment]
@mnot I am not sure I get you right :-/. Which section exactly are you referring to with your suggestion?

**Comment by mnot** [comment]
Sorry - [here](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#response.cacheability)

**Comment by royfielding** [comment]
I think that would be sufficient to close. Maybe specifically say "allows the response to be stored by a shared cache (with modifications)".
