### ISSUE TITLE
fix grammar for "Vary" header field

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#272]
it uses
   
    "*" / #vary

but "vary" is a token, and token allows "*" anyway. Also, see #7.

**Comment by reschke** [comment]
In particular, "*" is a valid field name. We probably should reserve it in the registry.

**Comment by annevk** [comment]
(CORS has an issue like that as well, including for a `*` method; see the note at https://fetch.spec.whatwg.org/#http-new-header-syntax.)

**Comment by reschke** [comment]
Proposal:

    vary-by = "*" / field-name
    Vary = 1#vary-by

Then state that if "*" appears, no "real" field-name is allowed to appear as well (for backwards compat).

Do we need to discuss cases like

    Vary: *, *

?

**Comment by royfielding** [comment]
I don't see why that is an improvement.

**Comment by mnot** [comment]
I thought we were going to reserve `*` and define its meaning in prose...

**Comment by mnot** [comment]
I.e., it should just be

> Vary = 1#field-name

**Comment by reschke** [comment]
which implies registering "*" as reserved field name, right?

**Comment by mnot** [comment]
Yes. That's #274

**Comment by mnot** [comment]
Discussed; will create a PR to move ABNF and prose to list-based.

**Comment by reschke** [comment]
Do we need to list that as change from 7230?

**Comment by mnot** [comment]
Probably a good idea; will commit to master and link here.
