### ISSUE TITLE
message field registry migration needs to consider status "reserved"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#273]
We have at least one entry in status "reserved" (for "close"). We need to define how it will show up in the new registry.

**Comment by reschke** [comment]
Proposal 1:

add a status "reserved" (and define the procedure for reserving field names)

Proposal 2:

move "close" to "permanent", but add a comment column in the registry and note what is special about that field name over there.

**Comment by mnot** [comment]
Either is fine with me, but I lean towards (2).

**Comment by reschke** [comment]
Asked mailing list in <https://lists.w3.org/Archives/Public/ietf-http-wg/2020JanMar/thread.html#msg103>.
