### ISSUE TITLE
need to reserve field name and method name "*"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#274]
A field name of "*" would clash with the definition of "Vary" (see #272).

A method name of "*" would clash with Access-Control-Request-Method (see https://fetch.spec.whatwg.org/#http-new-header-syntax) (ack @annevk)

**Comment by reschke** [comment]
...or disallow registration.

**Comment by reschke** [comment]
partly blocked by #273

**Comment by reschke** [comment]
To "reserve" in the method registry, we'll need to add a "comments" column to the registry. Makes sense?

cc: @mnot

**Comment by annevk** [comment]
Would you leave Safe and Idempotent empty as well? Forbidding registration might be simpler?

**Comment by reschke** [comment]
Good question. Maybe "n/a"?

In any case, extending the registration procedure to disallow "*" works for me as well.

**Comment by mnot** [comment]
Disallowing registration is fine for me too. Should we also disallow registering it as a field name?

There are a few other ways we could do this that might be worth considering; e.g., we could require registered values to have at least two characters, or require registered values to begin with ALPHA. We already say:

> While the field-name syntax is defined to allow any token character, in practice some implementations place limits on the characters they accept in field-names. To be interoperable, new field names should constrain themselves to alphanumeric characters, "-", and ".", and should begin with an alphanumeric character.

**Comment by reschke** [comment]
> Disallowing registration is fine for me too. Should we also disallow registering it as a field name?

Yes, for consistency.

**Comment by mnot** [comment]
Discussed; put into the registry with a comment about why it's reserved; not safe or idempotent.

**Comment by reschke** [comment]
Note https://github.com/whatwg/fetch/issues/1052
