### ISSUE TITLE
Clarification of GET versus POST for information retrieval

### ISSUE THREAD

**Issue by bazzadp** [httpwg/http-core#277]
Am sure this has been discussed before, and I'm opening a can of worms but here goes (if nothing else would be nice to have this as an issue to be easily referenceable)...

The traditional accepted use case for [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1) is for information retreival and [POST](https://tools.ietf.org/html/rfc7231#section-4.3.3) is for uploading information to a server. This is reflected in the language of the definitions as linked in the previous sentences and does not seem to be materially changed in the [new versions currently in draft](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-06#section-7.3).

However the sections on [Disclosure of Personal Information](https://tools.ietf.org/html/rfc7231#section-9.3) and [Disclosure of Sensitive Information in URIs](https://tools.ietf.org/html/rfc7231#section-9.4) recognise the privacy and security implications of putting sensitive information in the URL as Query Params and state that "Such services ought to use POST-based form submission instead." Again this language seems [unchanged in the current drafts](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-06#section-13.8).

This seems out of sync with the definition of POST provided previously and leads to arguments as to whether information retrieval by sensitive params is an "acceptable" use of POST (particularly for those insisting on a rigid [definition of REST](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URI_and_HTTP_methods)). Note I'm not talking about authentication cookies here - but more other params which clarify the resouce required, rather than authenticate access to such a resource. For example "download document id 1234" is often an information retreival request, which is supplemented by cookies to confirm access to that document. In this case the document id may be considered sensitive (e.g. if it's a policy number, or a claim identifier) so should not be sent as a URL param which would rule out GET, unless you want to get into providing the params as HTTP Headers instead which just seems like a messy idea.

Of course you could use a GET with a body but the RFC [explicitly notes why this is a bad idea](https://tools.ietf.org/html/rfc7231#section-4.3.1): "sending a payload body on a GET request might cause some existing implementations to reject the request." and this has been [strengthened in the lastest draft](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-06#section-7.3.1) to: "A client SHOULD NOT generate a body in a GET request" in #202 

The POST definition doesn't explicitly forbid it's use for information retreival, but all the examples suggest data is being sent to the server for storage (perhaps not the first example, but certainly the others) and there are [many](https://stackoverflow.com/questions/52050997/should-i-use-a-post-request-to-send-a-retrieval-request-to-my-server-for-a-large) examples of this being debated.

While this has always been an issue, it is getting more and more important in this more privacy-aware world and with various legislation and security requiremnts and I feel the specs could be more explicit, and reflect what I imagine is a common use case for POST.

Therefore should text and/or the examples be added to clarify the position in regards to retreival via POST requests, and to resolve the apparent discrepency in regards to the [Disclosure of Sensitive Information in URIs](https://tools.ietf.org/html/rfc7231#section-9.4) section?

**Comment by asbjornu** [comment]
Have you read the discussion in #250? It lead to the creation of httpwg/http-extensions#943 and httpwg/http-extensions#942 that both attempt to tackle this problem from different angles.

**Comment by bazzadp** [comment]
I saw #202 but missed the discussion in the subsequent pull request to resolve that (#250) so thanks @asbjornu for pointing me at that.

https://github.com/httpwg/http-extensions/issues/942 and https://github.com/httpwg/http-extensions/issues/943 both seem concerned with making payloads with bodies cacheable which is actually the opposite of the uses cases I’m talking about. In my use case the fact these are fetched with private query params that we don’t want to store in the URL params so they are not leaked, would also mean (in most cases) that you wouldn’t want the resulting response cached either. This is why POST works fine for this use case, apart from the ideology behind it.

POST has the added benefit of being a well known and well-support method whereas introducing a new method like SEARCH will take time to filter through various tech stacks. That makes sense when you want to change the definition (explicitly make it cacheable which POST is not) so must wait until it’s support, but seems less necessary when we have an existing method that works fine.

Of course if this is a terrible use case for POST then that should be clarified in the spec IMHO, with reasons why. Currently it seems open for debate.

**Comment by mnot** [comment]
Perhaps just adding a simple sentence like this to the definition of POST would help:

> Note that POST is sometimes used to retrieve information from a server when it is not desirable to expose information in the URI with GET; see [ref to security considerations].

**Comment by royfielding** [comment]
After reading all three sections again, I think that it works best as an explanation in GET and a more nuanced warning in the security considerations.

**Comment by bazzadp** [comment]
I think that's good to get that in there thanks @royfielding 

Though for completeness, perhaps should also mention it under POST section, maybe using @mnot 's [suggested wording](https://github.com/httpwg/http-core/issues/277#issuecomment-667873300) or similar? Or alternatively including as an another [example use case at the beginning of the POST definition](https://tools.ietf.org/html/rfc7231#section-4.3.3)? But happy to leave it as, if you think that's overkill.
