### ISSUE TITLE
Prefer SRV records over just A/AAAA

### ISSUE THREAD

**Issue by vanrein** [httpwg/http-core#280]
There currently is [no support for `SRV` records](https://bugzilla.mozilla.org/show_bug.cgi?id=14328) in the HTTPbis specifications.  It would be useful to prefer `SRV` records over the current practice of directly using `A` and `AAAA` records.

**Benefits:**

  * `SRV` records specify preferences and load balancing -- the client is the only remaining single-point-of-failure
  * `SRV` reocrds specify a port number -- reducing visible port numbers in HTTP URIs
  * `SRV` records provide the protocol and port information to use with DANE
  * `SRV` records can hang from a domain yet point at a host underneath -- no need for `www.` in HTTP URIs
  * `SRV` records can hang from a domain and point into another -- simplifying 3rd party services
  * Less clutter in DNS from `CNAME` records -- and less "CNAME and OTHER" complaints

**Interesting potential:**

  * Automatic directions to mirror sites
  * [Links with DNS-SD](https://tools.ietf.org/html/rfc6763) and perhaps even distributed name space management [with TXT records](https://tools.ietf.org/html/rfc6763#section-6)

**Certificates:**  The name in TLS Certificates should *not* be the host name pointed at in the `SRV` record, but the name entered in the authority part of the URI.  Although the use of the host name would simplify massive virtual hosting solutions, it would only take a change in DNS to redirect a site; not all clients rely on DNSSEC.  Also, certificate rolling is probably still best to do per site, rather than massively per hosting location.

Having [campaigned this idea since forever](http://dns.vanrein.org/srv/), its mere usefulness has not caused much, and it seems to need standards action.

**Comment by martinthomson** [comment]
It is not typically the case that features are implemented and deployed because they are standardized. Usually, things are standardized because there is demand for the feature in implementations. That demand has not been there for SVC.

The proposed [HTTPSSVC record](https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-httpssvc) (which might be renamed to something less awkward) aims to address the shortcomings of A/AAAA without also picking up the baggage of SVC.

**Comment by mnot** [comment]
This isn't in-scope for the core specs; closing.
