### ISSUE TITLE
Task: review all anchors in document set

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#287]
Things to do:
- remove "header" where appropriate

**Comment by reschke** [comment]
For HTML generated by rfc2629.xslt, we can keep old anchors functional using x:anchor-alias. But that will not be the case for HTML generated by xml2rfc.

**Comment by reschke** [comment]
See https://github.com/httpwg/http-core/pull/360

**Comment by reschke** [comment]
Maybe:

- use "." only for hierachy (status. , field.)
- use -" as whitespace replacement not "."

**Comment by reschke** [comment]
Note: do this after submitting the next drafts which will be changing section numbers; changing anchors at the same time would be unwise.

**Comment by reschke** [comment]
Should we replace "MEDTHODNAME" by "method.METHODNAME"? Will affect many source lines...

**Comment by royfielding** [comment]
no

**Comment by mnot** [comment]
what roy said

**Comment by reschke** [comment]
- [ ] use "." only for hierarchy (status. , field.)
- [ ] use -" as whitespace replacement not "."
- [X]  make sure we have anchors for all sections
- [ ] review use of "intro." pattern

**Comment by reschke** [comment]
So I'm unsure about "use -" as whitespace replacement not "."" -- this looks nice and clean in practice, but essentially means to change anchors on the majority of sections. Is that really worth it? I'd rather do the opposite.

**Comment by royfielding** [comment]
I don't see any need to replace anchors unless there is a conflict (like field-lines instead of field.lines because of field.field-name being a good pattern) or some existing anchor needs to be shortened for sanity.

**Comment by mnot** [comment]
WFM

**Comment by reschke** [comment]
OK, so'll try to replace "-" by "." unless this leads to confusion with other patterns.

**Comment by reschke** [comment]
Replace all hyphens in anchor names, except when:

- they represent hyphens in field names
- they conflict the "status." or "field." naming convention

In the latter case, consider changing the prefix, for instance from "field." to "fields."

**Comment by reschke** [comment]
See #803
