### ISSUE TITLE
RFC 7231: Include definition of status code 308

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#3]
...currently defined in RFC 7538.

**Comment by mnot** [comment]
This would obsolete 7538?

**Comment by reschke** [comment]
Yes.

**Comment by reschke** [comment]
Maybe we should also add the table from https://greenbytes.de/tech/webdav/rfc7538.html#rfc.section.1 somewhere.

**Comment by mnot** [comment]
Possibly at the top of the 3xx section.
