### ISSUE TITLE
Clarify Accept header parameters and OWS recommendation

### ISSUE THREAD

**Issue by scalablecory** [httpwg/http-core#301]
In later RFCs, the Accept header was updated to support OWS before/after the semicolons:

```
     Accept = #( media-range [ accept-params ] )

     media-range    = ( "*/*"
                      / ( type "/" "*" )
                      / ( type "/" subtype )
                      ) *( OWS ";" OWS parameter )
     accept-params  = weight *( accept-ext )
     accept-ext = OWS ";" OWS token [ "=" ( token / quoted-string ) ]
```

Someone implementing a client might read the OWS recommendation as "you must accept without OWS but should always transmit OWS":

```
For protocol elements where optional whitespace is preferred to improve readability, a sender SHOULD generate the optional whitespace as a single SP
```

It would be useful to clarify in Section 5.3.2 "Accept" that in RFC 2616, OWS was explicitly not allowed and that inserting OWS would cause RFC 2616 compliant servers to fail parsing.

**Comment by royfielding** [comment]
Why would they read "optional whitespace" as a statement that whitespace is required?

**Comment by scalablecory** [comment]
Restated,

Some may feel readability is desirable and mistakenly interpret that OWS is free here when in reality it makes you non-compliant with RFC 2616. This is an unnecessary land mine: it requires readers to know both revisions to avoid a backward compatibility issue.

**Comment by mnot** [comment]
@scalablecory --

> OWS was explicitly not allowed and that inserting OWS would cause RFC 2616 compliant servers to fail parsing

Where do you see that in 2616? Note the [implied *LWS rule](https://tools.ietf.org/html/rfc2616#section-2.1).

**Comment by scalablecory** [comment]
@mnot Thanks, I was missing that rule. That clears this up I think  -- closing.
