### ISSUE TITLE
fix ABNF for If-Match and If-None-Match

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#305]
...not to special-case "*" as top-level construct.

**Comment by mnot** [comment]
Also need to fix things like

> when the field value is "*"

to something like

> when the field value contains "*"

**Comment by mnot** [comment]
Discussed; intent is to add a note at the end of each section pointing out that the behaviour of multiple/mixed stars is undefined, and that this is a lame way to specify a field.
