### ISSUE TITLE
Define "request" and "response" independent of HTTP/1.1

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http-core#311]
It looks like "request" and "response" are defined in https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#operation as kinds of "messages", and then "messages" are defined in the same section by reference to https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#http.message ... which only applies to HTTP/1.1. I *think* these are intended to be version-independent concepts, so they need a version-independent definition.

**Comment by MikeBishop** [comment]
Each version defines how a message is transferred, but I agree that the concept of what a message is needs to be defined independently.

**Comment by mnot** [comment]
I took the most minimal approach. I could also imaging rearranging things so that there's a top-level section "messages" to define these things more prominently, but that can be done editorially if we think it's worthwhile.
