### ISSUE TITLE
Duplicate header resolution in H1

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#32]
Firefox rejects responses with multiple `Location` headers (unless their values happen to be identical). Other browsers have different handling and it likely differs per header field. It would be great to get a consistent story around this.

**Comment by mnot** [comment]
Anne, is this issue specifically about Location?

**Comment by annevk** [comment]
It basically exists for each header (e.g., I've personally tested `Content-Length` and `Content-Type` and found numerous interoperability issues).

**Comment by annevk** [comment]
See https://github.com/web-platform-tests/wpt/pull/10548 and https://github.com/web-platform-tests/wpt/pull/10525 for some progress on `Content-Length` and `Content-Type` by the way.

https://github.com/whatwg/fetch/pull/813 notes some concerns about combining before parsing (or perhaps only about combining eliding empty/whitespace values).

**Comment by mnot** [comment]
See also #193. Can we close this in favour of that?

**Comment by reschke** [comment]
I believe so.

**Comment by annevk** [comment]
That's fine with me.
