### ISSUE TITLE
Handling of If-Unmodified-Since with unknown modified dates

### ISSUE THREAD

**Issue by evert** [httpwg/http-core#326]
I'm working on a new implementation of conditionals, and I'm a little confused about `If-Unmodified-Since`.

What should a server do if a client passed an `If-Unmodified-Since` header, but the target resource does not know its own modification date?

My intuition is that without a `Last-Modified` header, we should assume that the request is *always fresh*, and given that `If-Unmodified-Since` is used to protect against the 'lost update' problem, we should default to returning `412` if the last modification date could not be determined.

I don't think the current draft covers this case, but perhaps I've missed something.

**Comment by mnot** [comment]
It's a fair question.

I think we should explicitly state that an origin server can ignore this header if the resource does not have a concept of modification time.

Furthermore, I suspect that I-U-S should change this requirement:

> An origin server that receives an If-Unmodified-Since header field must evaluate the condition prior to performing the method (Section 8.2.1).

to something like:

> An origin server that receives an If-Unmodified-Since header field must evaluate the condition  (Section 8.2.1) prior to performing an unsafe method (Section 7.2.1).

**Comment by mnot** [comment]
Hm. In Evaluation, we say:

>    Likewise, a server &MUST; ignore the conditional request header fields
   defined by this specification when received with a request method that does
   not involve the selection or modification of a
   <x:ref>selected representation</x:ref>, such as CONNECT, OPTIONS, or TRACE.

It seems like we need to reference that if we're placing requirements around methods later on.
