### ISSUE TITLE
Unwelcome mention of "packets" in messaging/7.3.6/CONNECT

### ISSUE THREAD

**Issue by wtarreau** [httpwg/http-core#327]
The text for CONNECT says "...restrict its behavior to blind forwarding of **packets**, in both directions...".

This term "packet" is problematic here for two reasons. The first one is that it may confuse implementations in how to proceed since packets do not exist at this layer, and the second is that it will definitely comfort those complaining that they don't see the same "packets" on both sides of a proxy that they're right!

We should rather use "of the byte stream" (or anything similar) to be exact and remove any ambiguity. Note that I looked for other occurrences and didn't find any.

**Comment by wtarreau** [comment]
Oops sorry it was in semantics/7.3.6/CONNECT, not messaging. Connect is so much border line between the two that I got it mixed up :-)

**Comment by reschke** [comment]
Same as #183?

**Comment by wtarreau** [comment]
Interesting, and I already responded to this one, though I already forgot as it was more than one year ago. I suspect this really shocks me then :-) OK I'm closing it and will ping there again. Thank Julian!

**Comment by wtarreau** [comment]
And #170 was in fact already exactly the same!
