### ISSUE TITLE
Placement of TE: field

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#328]
TE: is currently defined in the HTTP/1.1 encoding.  However, the definition is used by HTTP/2 and HTTP/3 to say that it MAY be present, but MUST NOT have any value other than `trailers`.  It's a little strange, since this is definitely an artifact of wire encoding, but is used quasi-consistently across HTTP encodings.

Does this belong in Semantics?

**Comment by royfielding** [comment]
I think it does. In fact, I've been thinking of moving all of the header fields to Semantics for their definition (not necessarily their associated requirements) and simply noting when a field is not allowed (or translated) in h2, etc.

**Comment by mnot** [comment]
Dup of #18, so closing.
