### ISSUE TITLE
Are request forms Semantics?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#329]
H2 and H3 describe the use of the pseudo-headers / pseudo-fields in reference to requests in absolute-form, origin-form, etc.  However, those forms are currently defined in the HTTP/1.1 mapping, not in Semantics. Are they considered to be version-independent concepts, or should we frame the references to them in HTTP/3 as purely illustrative?

**Comment by MikeBishop** [comment]
There's also a reference to the request target in the definition of CONNECT, but request target is [defined in terms of these forms](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#request.target).

**Comment by mnot** [comment]
This is #340. Yes, I know this was here first, but I'm going to close it as a dup.
