### ISSUE TITLE
Proxy-Authenticate scope

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#331]
P-A is [defined](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#header.proxy-authenticate) as:

> The "Proxy-Authenticate" header field consists of at least one challenge that indicates the authentication scheme(s) and parameters applicable to the proxy for this effective request URI (Section 5.5).

This seems really odd -- P-A is not generally used in a way that's specific to a single target URI.

**Comment by mnot** [comment]
I think it's scoped to the request; i.e., if the client retries the same request with appropriate credentials, it's likely to succeed; we can't say much more than that.

**Comment by reschke** [comment]
FTR, the text we have is inherited from <https://greenbytes.de/tech/webdav/rfc2616.html#header.proxy-authenticate>.
