### ISSUE TITLE
Use URL Standard for Location header

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#34]
See https://wiki.whatwg.org/wiki/HTTP#Location_header:_URLs. Basically it's pretty clear that it's not a "URI reference".

**Comment by mcmanus** [comment]
in bkk: this isn't compatible beyond browser scope - uri reference is required.

todo: add some non-normative advice about the grammar and error handling noting you still have to deal with valid messages

**Comment by mnot** [comment]
The spec currently contains:

~~~
    &Note; Some recipients attempt to recover from Location fields
    that are not valid URI references. This specification does not mandate or
    define such processing, but does allow it for the sake of robustness.
~~~

Besides replacing "recipients" with "implementations" or "client implementations", I'm not sure what else to say.

**Comment by mnot** [comment]
Discussed in Montreal; close with proposal above.

**Comment by mnot** [comment]
Looking at this again, we use "some recipients" pretty consistently, so closing with no action.
