### ISSUE TITLE
Clarify use of If-None-Match with unsafe methods

### ISSUE THREAD

**Issue by michael-o** [httpwg/http-core#356]
Section 3.2 says:

> If-None-Match can also be used with a value of "*" to prevent an
   unsafe request method (e.g., PUT) from inadvertently modifying an
   existing representation of the target resource when the client
   believes that the resource does not have a current representation
   (Section 4.2.1 of [RFC7231]).  This is a variation on the "lost
   update" problem that might arise if more than one client attempts to
   create an initial representation for the target resource.

Please clarify what is supposed to happen when `If-None-Match` is used with unsafe methods and the value is NOT "*". Should the server respond with `BAD_REQUEST`?

**Comment by evert** [comment]
Reading the current version of the RFC, with one exception the `If-` family of headers all behave the same regardless of the method used.

The only exception is `If-None-Match` and `If-Modified-Since`, which return `304` for GET methods.

Everything else returns 412.

**Comment by michael-o** [comment]
This does not answer non `*` on `PUT`.

**Comment by evert** [comment]
I'll rephrase: all of the `If-` headers return 412 if the precondition failed, except `If-None-Match` and `If-Modified-Since` with `GET` or `HEAD`.

Here's the latest version:

https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.2.4

There's no exception for specifying etags in If-None-Match in `PUT`.

**Comment by michael-o** [comment]
> 
> 
> I'll rephrase: all of the `If-` headers return 412 if the precondition failed, except `If-None-Match` and `If-Modified-Since` with `GET` or `HEAD`.
> 
> Here's the latest version:
> 
> https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.2.4
> 
> There's no exception for specifying etags in If-None-Match in `PUT`.

So, far as I understand you rephrase, in the event of a `PUT` request and `If-None-Match: *` the actual ETag does not really matter. The client wil receive a 412 in any case. If the client does not send this header and the server refuses to overwrite the resource (the semanatics do not allow a subsequent `PUT`, but `PATCH` only) I expect a 409 would be most appropriate here?!

**Comment by evert** [comment]
Yes, a `PUT` request on `If-None-Match: *` should always fail with 412 on a resource that does not exist (yet).

If you're outright refusing to support `PUT` on pre-existing resources, I would argue that it's more desirable to just return a `405`. From a client's perspective, it's the more relevant error as there's nothing they can do to make this request pass.

**Comment by michael-o** [comment]
Alright, this makes sense. Skipping `If-*` headers altogether. Why not `409`, but `405`?

**Comment by mnot** [comment]
I don't think there's an underlying specification issue here; closing. Please discuss on the mailing list if you still have questions. Thanks!

**Comment by liyishuai** [comment]
Upon receiving a PUT request conditioned over `If-None-Match: W/"foo"`, according to [Section 12.1.2](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.12.1.2):
https://github.com/httpwg/http-core/blob/6c90bb07994bf5055045f40b3d44ed75c3cd03bc/draft-ietf-httpbis-semantics-latest.xml#L7102-L7105
If the target's ETag is `"foo"`, then this condition evaluates to false and the server should respond with 412 Precondition Failed. However, Apache HTTPD uses [strong comparison](https://svn.apache.org/viewvc/httpd/httpd/trunk/modules/http/http_protocol.c?diff_format=h&view=annotate#l598) for methods other than GET and HEAD, and processes this PUT request. Is this a bug in Apache or an edge case to be addressed in the specification?

**Comment by mnot** [comment]
Sounds like an apache bug; @royfielding?

**Comment by royfielding** [comment]
A PUT with a weak entity-tag in If-None-Match is not a sensible use case, but it looks like Apache httpd is deliberately preventing it. This may be a leftover from 2616 (will check later). The current spec is fine.

**Comment by liyishuai** [comment]
[RFC 2616 Section 14.26](https://tools.ietf.org/html/rfc2616#section-14.26) (If-None-Match) says:
> The weak comparison function can only be used with GET or HEAD requests.

which conflicts with the "MUST use the weak comparison" in the current spec.

I understand that this use case is nonsense, but I'm [formalizing HTTP specifications in Coq](https://github.com/liyishuai/coq-http), which requires specifying the server's behavior upon receiving such request from a ridiculous client. Should the server respond with 400 Bad Request, 412 Precondition Failed, or 2xx Success (or MAY choose among these)?

**Comment by mnot** [comment]
@liyishuai RFC723x obsoleted 2616, and I don't see that text in [RFC7232](https://tools.ietf.org/html/rfc7232#section-3.2) or our current specification.

**Comment by royfielding** [comment]
Right, my guess is that Apache still respects the old requirement just because nobody noticed. We can fix that at Apache.

To answer the original question (and @liyishuai), the current spec says 412:

```
   An origin server MUST NOT perform the requested method if the condition
   evaluates to false; instead, the origin server MUST respond with either
   a) the 304 (Not Modified) status code if the request method is GET or HEAD
   or b) the 412 (Precondition Failed) status code for all other request methods.
```
assuming that the request was successful up until the precondition check.
