### ISSUE TITLE
Fragment preservation is overly broad

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#37]
As far as I can tell browsers only preserve fragments during navigation. See https://github.com/w3c/web-platform-tests/pull/7261 for a test. https://github.com/whatwg/fetch/issues/505#issuecomment-286317874 for where this originally came up.

It seems better if HTTP didn't say anything about fragments other than that their handling is up to clients.

**Comment by reschke** [comment]
It says what it says *because* UAs differed in what they were doing.

The HTTP specs predate Fetch. If you want a change in the HTTP specs, it would be good if you could explain why Fetch differs from browser navigation in behavior.

**Comment by annevk** [comment]
Differed how?

**Comment by reschke** [comment]
In whether they were applying the fragment, and how they recombined them. See <https://trac.ietf.org/trac/httpbis/ticket/43>.

**Comment by annevk** [comment]
It seems you didn't actually test the various scenarios outlined in OP (and curiously you only tested browsers, not other clients).

**Comment by annevk** [comment]
I think I do somewhat agree with your assessment in that issue that it's better to leave this up to a higher level in the stack as HTTP just relays fragments, but doesn't really do anything with them.

**Comment by annevk** [comment]
Note that this can likely be closed as I was mistaken to some extent: https://github.com/whatwg/fetch/issues/505#issuecomment-361985220.

**Comment by annevk** [comment]
And to be clear, my plan of record is to make Fetch and HTML depend on HTTP defining the fragment handling, so if you do plan to leave it to a higher layer at some point, let Fetch know.

**Comment by mnot** [comment]
@annevk so we're good to close this one?

**Comment by annevk** [comment]
I guess you can close it, but it's not actually solved end-to-end yet. Changes haven't landed downstream, and clients haven't changed either. The longer the latter is true the more likely this will bubble back up and has to be revisited.

**Comment by reschke** [comment]
I'm still not sure what possibly would need to be "revisited".

The spec says what it says because people complained that 2616 didn't specify this. Years ago, we did the testing and got browsers to agree what to do on page navigation, and wrote that down.

What *exactly* do you think might be left to do?

**Comment by annevk** [comment]
Navigation isn't the only place where fragments are relevant (and HTTP doesn't restrict itself to navigation).

**Comment by mnot** [comment]
OK, closing. We can reopen if an action is needed.
