### ISSUE TITLE
in text about combining field lines, be more clear about type of whitespace

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#370]
We currently say:

> A recipient MAY combine multiple field lines with the same field name into one field line, without changing the semantics of the message, by appending each subsequent field line value to the initial field line value in order, separated by a comma and optional whitespace. For consistency, use comma SP.

https://github.com/httpwg/http-extensions/pull/1173#issuecomment-632396968 suggests that here "whitespace" refers to section 1.2.1 which defines OWS, BWS and RWS.

I'm ok with that, but I think this can be clearer; minimally by adding a section reference.

**Comment by royfielding** [comment]
I think that is editorial and you should feel free to add it if you think it helps. I worry sometimes that we have so many xrefs it makes the prose hard to read.

**Comment by mnot** [comment]
+1

It would be _great_ if the HTML renderings could somehow just use a link on the applicable text, instead of a parenthetical reference.

**Comment by reschke** [comment]
The alternative here would to say "OWS" instead of "optional whitespace".

**Comment by reschke** [comment]
> It would be great if the HTML renderings could somehow just use a link on the applicable text, instead of a parenthetical reference.

For rfc2629.xslt, I can of course add that. For xml2rfc in general, that would be a request for a new xref/@format.

**Comment by royfielding** [comment]
Fixed by 06bb185b04f31c4af1598e65702cf2095da1d334
