### ISSUE TITLE
terminology/definition of where request target and response status live

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#372]
Section 2.1 has:

> A client sends an HTTP request to a server in the form of a request message, beginning with a method (Section 7) and URI, followed by header fields containing request modifiers, client information, and representation metadata (Section 4), and finally a payload body (if any, Section 6.3.3).
> 
> A server responds to a client's request by sending one or more HTTP response messages, each beginning with a success or error code (Section 9), possibly followed by header fields containing server information, resource metadata, and representation metadata (Section 4), and finally a payload body (if any, Section 6.3.3).

So this is also specific to 1.1.

My proposal would be to define terms for request-line and status-line that are indenpendant of the protocol version.

For 1.1, these would map to what we had before (and might have to include the "Host" header field, right?).

For 2 (and 3, I guess), they would map to the pseudo header fields (all?).

We'd also have to fix the text above, as some ("Host") or all (pseudo header fields) are actually contained in the header field section.

**Comment by royfielding** [comment]
I think we just changed this section. Does this issue still apply?

**Comment by mnot** [comment]
I think this is an unnecessary level of abstraction; it just adds to the terms and concepts that people have to remember, and isn't as familiar as just saying "method and request target" and "status code and optional status phrase".

**Comment by mnot** [comment]
Discussed; issue is that in 2.1 Client/Server, instances of "beginning with..." are misleading.

**Comment by royfielding** [comment]
currently says

A client sends an HTTP request to a server in the form of a request message, beginning with a method (Section 7) and request target, followed by header fields containing request modifiers, client information, and representation metadata (Section 4), and finally a payload body (if any, Section 6.3.3).
