### ISSUE TITLE
semantics: clarify that "identity" is not a valid value for "content-encoding"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#388]

**Comment by annevk** [comment]
It might be worth checking that clients indeed treat it the same as an unknown value.

**Comment by reschke** [comment]
That's an interesting question as well; but it seems to be orthogonal to this issue.

Handling content codings is tricky (such as wrt ordering, repetition, and unknown encodings), It would indeed be good to have tests.

**Comment by reschke** [comment]
-> move req into field definitions

**Comment by royfielding** [comment]
fixed by #389
