### ISSUE TITLE
Content-Type header parsing

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#39]
This is related to #33, but subtly different. As explored in https://github.com/whatwg/mimesniff/issues/30 browsers have different code paths for request and response `Content-Type` header parsing. Values such as `*/*, text/html` in a response `Content-Type` header end up being interpreted as `text/html`, presumably for compatibility with deployed content.

This seems like another fallout of intermediaries adding potentially duplicate headers and (early) implementations being poorly tested for erroneous input.

**Comment by reschke** [comment]
This appears like a browser issue to me. There is and never was an intention to have different rules.

**Comment by annevk** [comment]
I'm not sure what that means. If it affects browsers, why would it not affect other clients in the HTTP ecosystem? Don't we all consume the same content?

**Comment by reschke** [comment]
Once again, there are no different rules. Browsers apparently implemented workarounds for misconfigured servers, but that doesn't mean that what browsers do is what everybody else is doing.

**Comment by mnot** [comment]
Do we need to do more than reference mimesniff (see #51)? Note there's already generic text about sniffing in [Content-Type](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#header.content-type).

**Comment by annevk** [comment]
This issue is really about parsing `Content-Type` and determining its (parsed) value, irrespective of any sniffing that might also take place.

**Comment by annevk** [comment]
More concretely, `text/html, text/plain` means `text/plain` in browsers. `text/plain;` means `text/plain` (not an error). `text/html;charset=gbk`, `text/html` means `text/html;charset=gbk` (yup, `charset` is copied over as a special case).

https://github.com/whatwg/fetch/pull/831 has a patch for Fetch to define this in detail with an acknowledgment that it doesn't match HTTP.

It seems greatly preferable to uplift this kind of thing and agree on header parsers across the HTTP ecosystem, but if that's not doable so be it.

**Comment by mnot** [comment]
Discussed in Basel; we could document a suggested error handling algorithm, as long as it's clear that rejecting the message because the content-type is invalid is still acceptable.

Suggested algorithm would be to use the last syntactically valid type. @annevk does that align with fetch?

**Comment by annevk** [comment]
More than today, but it's also more involved: https://fetch.spec.whatwg.org/#content-type-header.

**Comment by mnot** [comment]
Waiting for terminology from #193.

**Comment by reschke** [comment]
I just updated my ancient tests for content-type, see <http://test.greenbytes.de/tech/tc/httpcontenttype>.

To my surprise, Safari apparently handles comma-separated different from multiple fields, see <http://test.greenbytes.de/tech/tc/httpcontenttype/#multitextxmloneline>.

@annevk, that would be a bug according to FETCH, right?

**Comment by annevk** [comment]
Yes, I suspect there's a bug filed already. I think I found such bugs in all browsers as they all have very similar logic in their core HTTP parsers.

**Comment by reschke** [comment]
Ah. But then, I'm not really convinced that we should add this to the spec. My understanding that the request was based on browsers alreay agreeing on the error handling...

**Comment by annevk** [comment]
There's no complete agreement on all details involved. See https://github.com/whatwg/fetch/pull/831#issuecomment-441993627 for links to bugs.

**Comment by reschke** [comment]
I did some more testing with Java client libs (HTTPURLConnection, JDK HttpClient, Apache HttpClient). Of these, only the first seems to have an API getting the type directly, and that indeed takes the last value (no matter whether sent as list in a single instance, or in multiple fields).

It would be nice if there was a concrete Webkit bug that points out their inconsistency (see https://github.com/httpwg/http-core/issues/39#issuecomment-674045027) (cc @tfpauly).

**Comment by annevk** [comment]
I recommend either filing one that blocks https://bugs.webkit.org/show_bug.cgi?id=192000 or detailing the specific case you care about there in a comment.

**Comment by reschke** [comment]
done: https://bugs.webkit.org/show_bug.cgi?id=215604
