### ISSUE TITLE
ETag: space allowed?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#40]
It seems that in RFC 7232, we unintentionally excluded SP from the allowed characters in "etagc", see

  https://www.greenbytes.de/tech/webdav/rfc7232.html#header.etag

and

  https://stackoverflow.com/questions/6719214/syntax-for-etag#comment65343714_11572348

This probably merits an erratum.

**Comment by royfielding** [comment]
I am pretty sure that was intentional due to lack of interop.
We removed all whitespace from the value.  Of course, that should have
been specifically noted in Changes, though we did say the ABNF changed.

I do not believe SP/HT has been used by ETag values, in practice.

**Comment by reschke** [comment]
OK,, so we forgot to mention it in the "Changes" section.

**Comment by reschke** [comment]
https://www.rfc-editor.org/errata/eid5162

**Comment by reschke** [comment]
Duplicate of https://github.com/httpwg/http-core/issues/89
