### ISSUE TITLE
Index missing in text after switch to v3 format

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#409]
The upgrade to xml2rfc v3 seems to have lost the generated Index sections even though we didn't change the default for indexInclude

   https://tools.ietf.org/html/rfc7991#section-2.45.4

Do we need to fix that in the tools?

**Comment by reschke** [comment]
xml2rfc v3 can not generate an index. See <https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/418>.

**Comment by royfielding** [comment]
Well, isn't that special.

**Comment by reschke** [comment]
it's kind of optimistic to set this to "waiting". The issue has been reported 11 months ago.

**Comment by mnot** [comment]
I believe the textual RFCs can be regenerated by the RFC Editor once their bugs are fixed; only the XML is canonical. So we can probably close this with no action.

**Comment by reschke** [comment]
But we currently can't submit XML with iref elements because if breaks the TXT output...

**Comment by mnot** [comment]
So, do we need an XSLT to strip `iref`?

**Comment by reschke** [comment]
clean-for-DTD.xslt already does that.

**Comment by royfielding** [comment]
On third thought, I think we are better off saving a few million trees by skipping the index output (but leave the iref markup in our copy of the xml so that others can generate it if needed).

I know it represents a very long legacy of editorial work, but the fact is that I haven't used it once over the past 23 years. I just use the ToC, perl, egrep, or textmate to find things in practice.

**Comment by reschke** [comment]
Bug apparently fixed in xml2rfc; waiting for release.

**Comment by reschke** [comment]
work with current xml2rfc release (as of yesterday) and modified XSLT (see https://github.com/httpwg/http-core/commit/4b43d08957842b1e21ab771818fb8994bd408a6d)
