### ISSUE TITLE
Transfer-Encoding header on 1xx, 204, 304 response

### ISSUE THREAD

**Issue by benburkert** [httpwg/http-core#41]
RFC 7230, section 3.3.3 forbids a response body when the status code is 1xx, 204, or 304. But it makes no mention of a `Transfer-Encoding` header on a response that cannot contain a message body. Is a `TE` header on a bodyless response permissible?

An answer to the question should clarify what a client is to do with the connection when a `TE` header is seen on a 1xx/204/304 response. @tombergan [reported](https://go-review.googlesource.com/c/go/+/71910#message-c40eef04c08f6492e195fc07bba624522aa54e50) that chrome will keep the connection open for reuse, while node.js will close the connection. Closing the connection avoids the ambiguity in handling follow up requests over the same connection, and might protect against response splitting attacks. However, it seems overly defensive to close the connection because the server may be about to invalidate the response by sending a body, even though the response is perfectly valid at the point the connection is being closed.

See golang/go#22330 for more context.

**Comment by tombergan** [comment]
> Is a TE header on a bodyless response permissible?

https://tools.ietf.org/html/rfc7230#section-3.3.1
> A server MUST NOT send a Transfer-Encoding header field in any
> response with a status code of 1xx (Informational) or 204 (No
> Content).  A server MUST NOT send a Transfer-Encoding header field in
> any 2xx (Successful) response to a CONNECT request (Section 4.3.6 of
> [RFC7231]).

This doesn't mention 304 (surprisingly) but does explicitly state that TE is forbidden on 1xx and 204.

**Comment by benburkert** [comment]
OK, perhaps it's just an oversight that 304 responses and HEAD requests are not included in that section too?

**Comment by reschke** [comment]
<https://www.greenbytes.de/tech/webdav/rfc7230.html#rfc.section.3.3.1.p.5>:

> Transfer-Encoding MAY be sent in a response to a HEAD request or in a 304 (Not Modified) response (Section 4.1 of [RFC7232]) to a GET request, neither of which includes a message body, to indicate that the origin server would have applied a transfer coding to the message body if the request had been an unconditional GET. This indication is not required, however, because any recipient on the response chain (including the origin server) can remove transfer codings when they are not needed.

**Comment by mnot** [comment]
Any clarification required here, or can we close with no action?

**Comment by benburkert** [comment]
nope, the section @reschke pointed out answered my question.
