### ISSUE TITLE
Review use of 'field'

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#411]
I want to take another look at how we use `field` vs `header field` and `trailer field`. There are a few cases where `header field` has been aggressively trimmed down to `field` which could lead readers to believe that it's valid in trailers too.

**Comment by mnot** [comment]
In Messaging `field.parsing`, it says:

> Messages are parsed using a generic algorithm, independent of the
   individual field names. The contents within a given field line value are
   not parsed until a later stage of message interpretation (usually after the
   message's entire header section has been processed).

Should that be 'after the entire field section has been processed'?

**Comment by mnot** [comment]
Just below:

> A server &MUST; reject any received request message that contains
   whitespace between a header field name and colon with a response status code of
   <x:ref>400 (Bad Request)</x:ref>.

Is that specific to headers?

**Comment by mnot** [comment]
And then:

>    The field line value does not include any leading or trailing whitespace: OWS
   occurring before the first non-whitespace octet of the field line value or after
   the last non-whitespace octet of the field line value ought to be excluded by
   parsers when extracting the field line value from a header field line.

'header' doesn't seem appropriate there.

**Comment by mnot** [comment]
In `line.folding`, 

>    Historically, HTTP header field line values could be extended over multiple

This isn't harmful (since it's just illustrative), but maybe misleading; should just be 'field line values'

**Comment by mnot** [comment]
In `field.transfer-encoding`, 

> Additional information about the encoding parameters can be
   provided by other header fields not defined by this specification.

Is that an intentional restriction?

**Comment by mnot** [comment]
In `message.body.length`:

>    Any response to a HEAD request and any response with a
   <x:ref>1xx (Informational)</x:ref>, <x:ref>204 (No Content)</x:ref>, or
   <x:ref>304 (Not Modified)</x:ref> status code is always
   terminated by the first empty line after the header fields, regardless of
   the header fields present in the message, and thus cannot contain a
   message body.

... or trailer sections?

**Comment by reschke** [comment]
Am 08.10.2020 um 07:57 schrieb Mark Nottingham:
> Just below:
>
>     A server &MUST; reject any received request message that contains
>     whitespace between a header field name and colon with a response
>     status code of
>     <x:ref>400 (Bad Request)</x:ref>.
>
> Is that specific to headers?

For trailers, a MUST would not work, as it would require buffering the
payload before sending a response.

**Comment by mnot** [comment]
Good point, I remember that now :)

**Comment by mnot** [comment]
I think we can close.
