### ISSUE TITLE
No TE Response header

### ISSUE THREAD

**Issue by yadij** [httpwg/http-core#413]
Transfer-Encoding header can be used on request payloads, but the TE header is defined only as a request header and Accept mechanisms are defined only for Content-Encoding. As a result there is no clear way for clients to be informed of what non-chunked encodings the server will accept. Only out-of-band mechanisms and guesswork can be used.

This is not as issue with HTTP/1.0 style traffic with one request per connection. But under HTTP/1.1 it would help greatly in optimizing pipeline requests to allow servers to signal explicit support. Please open the definition of TE to allow use on Responses.

**Comment by reschke** [comment]
Just to be clear: that would only effect HTTP/1.1, right?

**Comment by yadij** [comment]
Yes.

**Comment by mnot** [comment]
TE is already defined to do two things -- advertise supported transfer-codings and advertise use of trailers. Personally, I'd rather mint a new header just for this purpose -- e.g., `Accept-TE` -- rather than extend its use.

**Comment by reschke** [comment]
"Accept-TE" sounds good to me.

**Comment by yadij** [comment]
I think both uses of TE are applicable to the response use-case and trying to minimize the delta on core docs this late in the process.

I'm okay with whichever solution though. Just pointing out a hole found while planning implementation beyond the basic Transfer-Encoding:chunked.

**Comment by reschke** [comment]
> Just pointing out a hole found while planning implementation beyond the basic Transfer-Encoding:chunked.

@yadij - a clarification would be helpful... Are you indeed considering *new* transfer codings for HTTP/1.1?

**Comment by yadij** [comment]
No. Just the ones already defined which are not "chunked". gzip, base64, etc.

**Comment by reschke** [comment]
"base64"? Anyway; my understanding was that compressui schemes in TE aren't used much in the wild. Is that a misunderstanding?

**Comment by mnot** [comment]
Discussed on the editors' call; this needs to be a separate proposal (i.e., an Internet-Draft) for discussion by the Working Group; introducing it into core isn't in scope for this effort.
