### ISSUE TITLE
Header Field Registry

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#42]
... is currently interleaved with News and SMTP, which is less than ideal.

See:
  https://mnot.github.io/I-D/httpbis-header-registry/

**Comment by royfielding** [comment]
Strictly speaking, it's an IANA instruction, but those instructions are in some other RFC.  I think we would need the responsible list to agree first, which I guess means dispatch.

**Comment by mnot** [comment]
Yes. I'm talking to Alexey about it.

**Comment by mnot** [comment]
Discussed in DISPATCH Bangkok, no problem from them.

I've updated and submitted my draft, see:
  https://tools.ietf.org/html/draft-nottingham-httpbis-header-registry-00

**Comment by mcmanus** [comment]
in bkk: make it so

**Comment by mnot** [comment]
As per discussion in #188, re-opening to remind us to remove this:

> Entries with a status of 'deprecated' are to have a status of 'obsoleted'.
