### ISSUE TITLE
Talk about the relationship between Host and TLS SNI

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#434]
This has security and interoperability impact.

**Comment by mnot** [comment]
... but it's best to leave it unspecified, as SNI isn't stable yet.

**Comment by martinthomson** [comment]
SNI or ESNI?  Or are we talking about the broader debate?

**Comment by mnot** [comment]
My original thinking was that it was important to point out that SNI (not E) doesn't necessarily match what's in host. However, connection coalescing makes this implicit.

We could mention it in passing, if it would help remind people of that.

**Comment by martinthomson** [comment]
Hmm.  Dealing with this properly is tricky.  As you say, maybe best left to lie for the moment.
