### ISSUE TITLE
Variants cause conflicts in browser cache

### ISSUE THREAD

**Issue by namedgraph** [httpwg/http-core#443]
As shown in this [SO question](https://stackoverflow.com/questions/60799116/if-none-match-headers-ignore-content-type-and-vary) and the article [The browser cache is Vary broken](https://jakearchibald.com/2014/browser-cache-vary-broken/), browser cache implementations are broken when it comes to content negotiation and the `Vary` header.

The suggestion would be to explicitly include the `Vary` value in the cache key, for example: `Cache = (Vary ✕ Request-URI)*`

**Comment by awwright** [comment]
Isn't this bug report for browser vendors?

**Comment by mnot** [comment]
Hi @namedgraph - can you restate your issue as one regarding the specifications? As it is, we can't act on this, so I'm closing the issue. Also note that there's ongoing work in designing a replacement for `Vary`.
