### ISSUE TITLE
remove MIME-Version field definition

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#449]

**Comment by reschke** [comment]
(keep the appendix though)

**Comment by reschke** [comment]
Clarification needed...

We want to remove:

1. The IANA regisztration of MIME-Version, and
2. Appendix "B.1. MIME-Version"

?

**Comment by royfielding** [comment]
We want to keep the appendix, which should just be pointing to the field defined by MIME as the way to indicate MIME-conformace within email. It is not used within HTTP.

**Comment by reschke** [comment]
...but it is currently defined for HTTP as well, see <https://greenbytes.de/tech/webdav/rfc7231.html#mime-version> and the IANA registry. Do we want to change that?

**Comment by royfielding** [comment]
> ...but it is currently defined for HTTP as well, see https://greenbytes.de/tech/webdav/rfc7231.html#mime-version and the IANA registry. Do we want to change that?

Yes.

**Comment by yadij** [comment]
It is also used within HTTP. A lot of the messages we see include that header.

AFAIK it was supposed to be way to identify whether ASCII or UTF-8 is supported by the generating agent. But UTF-8 agents are not removing it when breaking MIME compliance. So would be great to remove now that HTTP is migrating towards more UTF-8 uses.

**Comment by reschke** [comment]
> It is also used within HTTP. A lot of the messages we see include that header.

Could you be a bit more specific? Who is generating those?

> So would be great to remove now that HTTP is migrating towards more UTF-8 uses.

Is it?

**Comment by reschke** [comment]
So @royfielding, IIUC, we would:

- change the appendix to point out that MIME-Version is only defined for MIME, not HTTP, and
- instruct IANA to *remove* the entry for MIME-Version as an HTTP field

?

**Comment by ioggstream** [comment]
Remove or obsolete Mime-Version?

**Comment by reschke** [comment]
We discussed this yesterday, and we leaned to removing the text from the new documents, leaving the IANA registry pointing to the old spec.

That said, do you have any use for it?

**Comment by ioggstream** [comment]
I don't have any use for it, but I was curious about how the entry deprecation was properly tracked to people reading the IANA table for the first time :)

**Comment by reschke** [comment]
@yadij - could you elaborate on

> It is also used within HTTP. A lot of the messages we see include that header.

?

**Comment by yadij** [comment]
> @yadij - could you elaborate on
> 
> > It is also used within HTTP. A lot of the messages we see include that header.
> 
> ?

A quick check of my local proxy shows 8% of messages contain a Mime-Version header. That is a bit lower than when I last looked into it, but still a lot.

**Comment by reschke** [comment]
Very interesting. Any chance to find out who is sending them, and maybe why? Do they all say "1.0"?

**Comment by royfielding** [comment]
If this is a concern, I suggest we just keep MIME-Version as registered and refer to its definition in MIME.

**Comment by reschke** [comment]
At this point, I'm not sure whether we actually want to change anything?

**Comment by reschke** [comment]
On hold - the idea was to move all field defs to semantics, but then we realized that transfer-encoding should stay. Leave MIME-Version alone for now.
