### ISSUE TITLE
Combining field values across sections

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#454]
The practice of combining list-form fields into a single value is widespread, and the document addresses this pretty clearly.  However it never really says that this combination needs to be limited to a single field section.  It's pretty clear that trailers need to be kept discrete, but there is nothing so direct.

It's probably worth adding "within a field section" somewhere.

**Comment by ioggstream** [comment]
Agree, but I can't find the definition of "field section" neither in MESSAGING nor in SEMANTICS :)

**Comment by martinthomson** [comment]
I was pointed to https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field-order which is good, but it doesn't really say that this combining only applies to a single field section (and yes, that is not a term that is defined in the document as far as I can see).
