### ISSUE TITLE
Combining Partial Content

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#458]
3.4 says:

> When combining the new response with one or more stored responses, a cache must use the header fields provided in the new response, aside from Content-Range, to replace all instances of the corresponding header fields in the stored response.

As per other discussions, this needs to be more nuanced; either a reference to 4.3.4, or new text.

**Comment by mnot** [comment]
The [tests show](https://cache-tests.fyi/?suite=updateHEAD) that no one is really doing this; `HEAD` is either converted to a GET on the backend, or it doesn't seem to touch the cache.

I think the most sane thing to do is to refer to the rules for a 304 update, but make it clear that this is optional.

**Comment by reschke** [comment]
Could you clarify how HEAD is relevant for "Combining Partial Content"?

**Comment by mnot** [comment]
Arg, sorry, wrong issue.
