### ISSUE TITLE
UTC in dates

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#472]
[Caching 4.2](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#expiration.model) says:

> A cache recipient should consider a date with a zone abbreviation other than GMT or UTC to be invalid for calculating expiration.

But [Semantics 5.7.7](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#http.date) says nothing about using UTC in dates.

Is this intentional? Similar question regarding the mismatch in case sensitivity.

**Comment by mnot** [comment]
Based on [this test](https://cache-tests.fyi/?id=freshness-expires-invalid-utc#), it appears that some implementations do support `UTC`, but only about half of those tested, so this isn't interoperable. 

So, we can't mandate supporting `UTC`, but neither can we make it non-conformant to support it as a recipient.

My inclination at this point is to slightly change this to clarify it, something like:

> A cache recipient SHOULD consider a date with a zone abbreviation other than GMT to be invalid for calculating expiration, but it MAY also accept UTC for historic reasons.

(also, editorially I can't help but wonder if `GMT` and `UTC` should be in quotes in that text)

**Comment by mnot** [comment]
This language also appears to have been introduced in 7234; the closest relevant language in 2616 is:

~~~
      - If an HTTP header incorrectly carries a date value with a time
        zone other than GMT, it MUST be converted into GMT using the
        most conservative possible conversion.
~~~

**Comment by reschke** [comment]
The mention of UTC was added in <https://trac.ietf.org/trac/httpbis/changeset/2397>. Backout?

**Comment by mnot** [comment]
I'm OK to back it out; @royfielding?
