### ISSUE TITLE
Date case sensitivity

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#473]
Caching 4.2:

> Although all date formats are specified to be case-sensitive, a cache recipient should match day, week, and time-zone names case-insensitively.

What does "week" refer to in this text? Also, why is this separate from the text on HTTP-dates? Do we really mean that caches should parse them in a different fashion than other components?

**Comment by reschke** [comment]
...we probably should find out when and why this difference was introduced...

**Comment by bagder** [comment]
Is "week" perhaps meant to be "month"?

**Comment by mnot** [comment]
This appears to have been added in 7234. The obvious thing to do is to use the appropriate rule names from [semantics](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#http.date): `day-name`, `day-name1`, `month` and `GMT`.

The [relevant tests](https://cache-tests.fyi/?id=freshness-expires-wrong-case-weekday&id=freshness-expires-wrong-case-month&id=freshness-expires-wrong-case-tz#expires-parse) seem to support this.

It also probably makes sense to mention this relaxation in Semantics, seeing as how caches are one of the primary consumers of dates in HTTP.

**Comment by reschke** [comment]
Ok, after some digging I found: <https://trac.ietf.org/trac/httpbis/ticket/165>.

(so it was me :-)

**Comment by mnot** [comment]
also https://github.com/httpwg/httpbis-issues/issues/165
