### ISSUE TITLE
Invalidation, Location and Content-Location

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#478]
The [tests show](https://cache-tests.fyi/?suite=invalidation) that support for invalidation on `Location` and `Content-Location` is really poor. In my experience, developers don't count on this, and in some case it's counter-productive (because a `POST` response might want the client to use a cached resource, rather than invalidate). 

Should we drop the requirement to invalidate these URLs?

**Comment by MikeBishop** [comment]
Requirement, perhaps.  I'd still keep it as a SHOULD, or minimally a MAY, though.

**Comment by mnot** [comment]
Calling it a SHOULD wouldn't exactly help interoperability. MAY makes more sense -- e.g., "Caches MAY invalidate other URLs, particularly...".
