### ISSUE TITLE
415 and Accept

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#48]
This came up in ACME where they wanted to use 415 and Accept.  

RFC 7694 implies this is OK, and makes two observations:

* 415 is for cases where request content type or content coding is not acceptable
* you can use Accept-Encoding with 415

RFC 7694 failed to explicitly allow Accept with 415, though it naturally follows.

We might consider rolling 7694 into any update given its tiny size, and then fix this in the process.

**Comment by reschke** [comment]
Allowing "Allow" sounds right to me.

Whether we want to make this in scope of http11ter we'll need to discuss...

**Comment by reschke** [comment]
Opened #119 to discuss inclusion of RFC 7694.

If we decide not to do this, should we update 7694 instead?

**Comment by reschke** [comment]
Right.

**Comment by reschke** [comment]
@martinthomson - what was the outcome on the ACME side?

**Comment by martinthomson** [comment]
I think that they avoided it:

> If a request does not meet this requirement, then the server MUST return a response with status code 415 (Unsupported Media Type).

With no mention of Accept.  I don't know what Boulder does, but can probably find out if absolutely necessary.

**Comment by reschke** [comment]
@martinthomson - that would be great.

**Comment by jsha** [comment]
In Boulder, if a POST doesn't have `Content-Type: application/json`, we return 415 with no Accept header.

**Comment by spaceone** [comment]
I don't understand the initial issue here fully but it would be nice If HTTP would have something to indicate in a response which response payloads it provides, e.g. using `Accept: application/json; q=1.0, text/html; q=0.9` in a response (e.g. to a `OPTIONS` request)!

And what also would be nice is if the resource could also inform the client which media types it supports in the request (as JSON has no forms to include this information and HTML only allows forms with `application/x-www-form-urlencoded` and `multipart/form-data` there is no standardized way to tell clients the possibilities).

**Comment by mnot** [comment]
Discussed in Basel; ACME apparently doesn't need this any more. Waiting on resolution of #119.

**Comment by mnot** [comment]
@reschke do you wan to take this one?

**Comment by reschke** [comment]
I can give it a try.
