### ISSUE TITLE
Overly brief section titles 

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#491]
I think it would be good for section titles to be more descriptive and ideally more active. In some cases, I think including 'HTTP' in the title helps readability, even though the reader presumably knows that this document is about HTTP. We should also be consistent about things like pluralisation.

Some tentative suggestions:

* 1.2 Evolution -> History and Evolution of HTTP
* 1.3 Semantics -> Core Semantics of HTTP
* 1.4 Obsoletes -> Specifications Obsoleted by this Document
* 4 Identifiers -> Identifiers in HTTP
* 4.1 URI References -> URI References in HTTP
* 4.2 URI Schemes -> HTTP-related URI Schemes
* 4.2.1 http URI Scheme -> The http URI Scheme
* 4.2.2 https URI Scheme -> The https URI Scheme
* 4.2.3 http(s) Normalization and Comparison -> Normalization and Comparison of http(s) URIs
* 4.2.4 http(s) Deprecated userinfo -> Deprecation of userinfo in http(s) URIs
* 5.1. Protocol Version -> 5.1. HTTP Protocol Versioning
* 5.2. Framing -> 5.2. Message Framing in HTTP
* 5.3 Control Data _N.B. what's up with this section?_
* 5.5. Payload -> Message Payload
* 5.5.2. Identification -> Identifying Message Payloads
* 5.6.3. Processing -> Processing Trailer Fields
* 5.7.1.1. Sender Requirements -> Sender Requirements for Lists
* 5.7.1.2. Recipient Requirements -> Recipient Requirements for Lists
* 6 Routing -> Routing HTTP Messages
* 6.1. Target Resource -> Target Resources
* 6.2. Routing Inbound -> Routing Requests
* 6.5. Transformations -> Message Transformations
* 7.1. Selected Representation -> Selected Representations
* 7.2. Data -> Representation Data
* 7.3. Metadata -> Representation Metadata
* 9 Context -> Message Context
* 10 Authentication -> HTTP Authentication
* 10.5. Protection Space (Realm) -> Establishing a Protection Space (Realm)
* 10.6. Authenticating User to Origin Server -> Authenticating Users to Origin Servers
* 10.7. Authenticating Client to Proxy -> Authenticating Clients to Proxies
* 12.2. Evaluation -> Evaluation of Preconditions
* 12.3. Precedence -> Precedence of Preconditions

**Comment by royfielding** [comment]
That's pretty much the opposite of what I was taught. There's no need to repeat HTTP everywhere. We should be removing non-essential text whenever possible. Headings are supposed to be concise and read within the context of the outline, not as an additional illustration of the section content.

**Comment by mnot** [comment]
I agree that there isn't a need to repeat HTTP in every section title, and that where possible we should be brief. However, section titles should facilitate navigation within the document, as well as within the ToC, and overly brief titles make that difficult. 

E.g., just the word "data" conveys almost no information about what's being discussed, and requires the reader to manually establish context.
