### ISSUE TITLE
MIME sniffing

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#51]
7231 [says](http://httpwg.org/specs/rfc7231.html#header.content-type):

> In practice, resource owners do not always properly configure their origin server to provide the correct Content-Type for a given representation, with the result that some clients will examine a payload's content and override the specified type. Clients that do so risk drawing incorrect conclusions, which might expose additional security risks (e.g., "privilege escalation"). Furthermore, it is impossible to determine the sender's intent by examining the data format: many data formats match multiple media types that differ only in processing semantics. Implementers are encouraged to provide a means of disabling such "content sniffing" when it is used.

It seems like this should at least mention:
* [MIME sniffing](https://mimesniff.spec.whatwg.org)
* [x-content-type-options: nosniff](https://fetch.spec.whatwg.org/#x-content-type-options-header)

**Comment by royfielding** [comment]
As mentioned in the PR, it makes sense here to reference MIME Sniffing as that is responsive to the entire paragraph. However, X-CTO is neither a standard nor recommended in practice, and falls into a "no I really mean it" example rather than a means for the user to disable sniffing. I have updated the PR accordingly.

**Comment by annevk** [comment]
`X-Content-Type-Options` is definitely recommended to some extent, it's the only way to avoid a certain set of issues.

**Comment by mcmanus** [comment]
ietf104: no interest in mentioning xcto explicitly
