### ISSUE TITLE
Question: does SEMANTICS obsolete/update RFC3864 aka BCP90 ?

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-core#515]
## Question

IIUC httpbis-semantics changes the field name registry, thus ~~obsoleting~~ updating BCP 90 / RFC3684.

Is that correct? 
Should httpbis-semantics mention that?

@reschke

**Comment by reschke** [comment]
"obsoletes": no, because BCP 90 is also for email. "updates": yes, I think so. @mnot?

**Comment by mnot** [comment]
Hm; I suppose so, given that it's taking some of 3684's turf away.

**Comment by reschke** [comment]
Now does that make SEMANTICS part of BCP90?

**Comment by mnot** [comment]
I'm inclined to say no -- it modifies the scope of BCP90 to exclude HTTP header fields. Worth discussing more broadly, though.
