### ISSUE TITLE
move transfer-coding ABNF to [Semantics]?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#531]
This is the remaining ABNF production that Semantics imports from Messaging (for the definition of "TE"). Maybe we should move the production to messaging, reversing the dependency.

**Comment by mnot** [comment]
Discussed on call; worth a try.

**Comment by reschke** [comment]
...turns out that there are a few more things to consider:

- Semantics currently claims there are regular parameters here, but transfer-parameter is special wrt BWS
- should we move the special case of "trailers" in the grammar into prose? In any case, what would it mean to have a ranking on "trailers"? Invalid, thus ignore?
- "t-ranking" seems to duplicate "weight"
