### ISSUE TITLE
"Messages": tune intro

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#532]
We currently say:

"The request might also contain header fields (Section 5.4) for request modifiers, client information, and representation metadata, a payload body (Section 5.5.4) to be processed in accordance with the method, and trailer fields (Section 5.6) for metadata collected while sending the payload."

I think it would be better to say:

"The request might also contain header fields (Section 5.4) for request modifiers, client information, and representation metadata, a payload (Section 5.5) to be processed in accordance with the method, and trailer fields (Section 5.6) for metadata collected while sending the payload."

so s/payload body (Section 5.5.4)/payload (Section 5.5)/

**Comment by royfielding** [comment]
but the "payload" is both some of the metadata and the transfer-decoded body.

**Comment by reschke** [comment]
...but it really reads strange to reference 5.4, 5.5.4, and 5.6...

**Comment by royfielding** [comment]
This is going to be fixed as part of #553
