### ISSUE TITLE
Semantics: "5.3. Header Fields" -> "5.3. Header and Trailer Fields"?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#540]

**Comment by royfielding** [comment]
We had that before.  We currently have a very long section about the message abstraction.

We could split it by sections to avoid having Header FIelds as the heading. Something like

```
5.   Message Abstraction
    5.1.   Framing and Completeness
    5.2.   Protocol Version
    5.3.   Header Section
        5.3.1.   Header Field Ordering and Combination
        5.3.2.   Header Field Limits
        5.3.3.   Header Field Names
        5.3.4.   Header Field Values
    5.4.   Body Section(s)
        5.4.1.   Purpose of Payload
        5.4.2.   Identifying Payloads
        5.4.3.   Payload Metadata
        5.4.4.   Payload Body
    5.5.   Trailer Section(s)
        5.5.1.   Trailer Field Ordering and Combination
        5.5.2.   Trailer Field Limitations
        5.5.3.   Trailer Field Names and Values

6.   Common Rules for Defining Field Values
    6.1.   Lists (#rule ABNF Extension)
        6.1.1.   Sender Requirements
        6.1.2.   Recipient Requirements
    6.2.   Tokens
    6.3.   Whitespace
    6.4.   Quoted Strings
    6.5.   Comments
    6.6.   Parameters
    6.7.   Date/Time Formats
```

**Comment by reschke** [comment]
I see.

What bugs me somewhat is that most of what we currently have in 5.3 applies to all fields, not only header fields.

**Comment by mnot** [comment]
Julian, I had the same concern when reading, but I'm OK with it as it is -- yes, the trailer section has to reference the header fields, but that's not awful. If trailers were as common as headers I might feel differently, but they're effectively a corner case.

Roy - I like that reorganisation, if you want to pursue it.

**Comment by royfielding** [comment]
Another rabbit hole, but I think I can see a light.
