### ISSUE TITLE
"9.1.1. Expect" has a lot of text specific to HTTP/1.*

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#544]
worth untangling?

**Comment by mnot** [comment]
I don't see that text as 1.1-specific; it's for all versions 1.1 and afterwards (i.e., it's in there for 1.0 backwards compatibility).

**Comment by royfielding** [comment]
Not worth untangling, though I did work on cleaning up the terms in #546 

I just noticed that the Note at the bottom of that section is no longer correct since we restored the extension syntax.

**Comment by reschke** [comment]
Opened #547 for that...
