### ISSUE TITLE
definition of HEAD vs "payload header fields"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#559]
currently links to "Message Payload", but that is not that helpful in order to find out what fields actually are "payload header fields".

**Comment by reschke** [comment]
Note. We currently say:

"The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request had been a GET, except that the payload header fields (Section 6.4) MAY be omitted."

https://github.com/httpwg/http-core/pull/555 would change this to:

"The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request had been a GET, except that header fields that describe message body encoding or transmission (e.g., Transfer-Encoding) MAY be omitted."

(me confused by that)

**Comment by royfielding** [comment]
I should probably just list them all. Content-Length and Transfer-Encoding are the obvious ones, but I would have to go through the spec to be sure there are not more.

The reason for this is that servers do not generate the body on HEAD responses, so the fields that are defined while buffering the first 8K of body (when they can still be sent as headers) are not sent on HEAD responses. Maybe we should just say that.
