### ISSUE TITLE
abstract: use of "header fields"

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#561]
"This document defines the semantics of HTTP: its architecture, terminology, the "http" and "https" Uniform Resource Identifier (URI) schemes, core request methods, request header fields, response status codes, response header fields, and content negotiation."

replace by just "fields"?

**Comment by mnot** [comment]
I think it's useful to retain the current text, because those phrases are more likely to be recognised by readers coming to the document.

**Comment by royfielding** [comment]
No real opinion, but it should be rewritten anyway:

This document defines the semantics shared by all versions of the Hypertext Transfer Protocol (HTTP), including its architecture, terminology, and core protocol elements, along with the "http" and "https" identifier schemes.

It could go on from there to describe the core elements, and maybe the core features as well, but *shrug*.
