### ISSUE TITLE
"15.3.1. 200 OK" representation data

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#572]
"HEAD: the same representation as GET, but without the representation data;"

Should that be "payload data"?

**Comment by royfielding** [comment]
No, that's correct, but I will tweak it slightly:

   HEAD: the same representation as GET, but without transferring the representation data;

**Comment by royfielding** [comment]
Note that the context is a discussion of what representation is included in a 200 response, which is why we are talking about representation data here instead of payload data.
