### ISSUE TITLE
"15.3.4. 203 Non-Authoritative Information" mention of Warning field

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#573]
"The 203 response is similar to the Warning code of 214 Transformation Applied (Section 5.5 of [Caching]), which has the advantage of being applicable to responses with any status code."

But then we have removed "Warning"...

**Comment by mnot** [comment]
I think we can just remove this text; if it's important, we can refer to 7234 and mention that it's deprecated.

**Comment by royfielding** [comment]
I say just remove the sentence.
