### ISSUE TITLE
"15.4. Redirection 3xx": changing method to HEAD?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#578]
"If the request method has been changed to GET or HEAD, ..."

Why would the method ever be changed to HEAD?

**Comment by reschke** [comment]
I see, because of 303.

**Comment by annevk** [comment]
In that case it hasn't changed though, right? It was simply preserved?

**Comment by reschke** [comment]
My understanding was that you for instance get a 303 upon POST, and then, for some reason, just do  a HEAD, as described for status code 303.

But why would that ever make sense?

(reopening)

**Comment by annevk** [comment]
FWIW, Fetch (in [HTTP-redirect fetch](https://fetch.spec.whatwg.org/#concept-http-redirect-fetch)) for 303 changes the method to GET if it's not GET or HEAD (it also does so for 301/302 if the method is POST).

**Comment by royfielding** [comment]
HEAD can be used, in general, for checking links. For example, a maintenance spider configured to GET (or even POST) for links to myhost.org but only try HEAD for links to notmyhost.com.

**Comment by reschke** [comment]
Ack, I'll close this then.
