### ISSUE TITLE
"15.5.9. 408 Request Timeout" mentions connections

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#579]
"If the client has an outstanding request in transit, the client MAY repeat that request on a new connection."

**Comment by royfielding** [comment]
I don't think this needs to be changed (connection is a defined term), but if you can think of some other way to say that the 408 implies partial receipt of the last request (which means the connection gone broke) then go ahead.

**Comment by mnot** [comment]
Suggestion:

> If the client has an outstanding request in transit, the client MAY repeat that request. If the current connection is not usable (e.g., as it would be in HTTP/1.1, because request delimitation is lost), a new connection will be used.

**Comment by royfielding** [comment]
+1
