### ISSUE TITLE
Content codings contract

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#58]
It would be somewhat nice if HTTP defined the content codings contract more clearly. That given a content coding and a response body, if the content coding is supported, the response body will be incrementally decoded until it either completes or some error is hit.

In particular, it would be nice if https://fetch.spec.whatwg.org/#handle-content-codings could be an explicit hook, rather than handwavy language.

**Comment by reschke** [comment]
I agree that this is roughly how content codings work, but I'm not sure what exactly you think the spec should say here. Do you have a rough proposal?

**Comment by annevk** [comment]
It'd be ideal if HTTP defined an algorithm for the transformation and then required any registrations to fulfill the same contract so it could easily delegate to them. It would ideally also define what happens when the content coding is not supported (e.g., return failure or return the bytes unmodified).

The main things that would clarify is that failure can occur and it would stipulate when it occurs. Both of these are observable for any streaming APIs, such as `fetch()` in the browser.

**Comment by annevk** [comment]
Content, though similar things might be good for transfer.

**Comment by reschke** [comment]
OK, let's discuss content codings first...

For those, a totally plausible API for HTTP wouldn't do anything automatically - it would just expose the raw payload, and information about which content (de-)codings need to be applied. In particular, that API design would enable experimentation with new content codings.

(FWIW, this is what the servlet API does, no?)

**Comment by annevk** [comment]
Yeah, that makes sense. We don't expose that capability at the moment, but I agree that it should be an optional thing that you can invoke (and for Fetch we'd chose to invoke it and maybe expose an option down the road to not do so if everyone is willing to support that).

I'm not familiar with the servlet API.

**Comment by reschke** [comment]
FWIW, automatic handling on content codings may also interact badly with ETags. (See https://greenbytes.de/tech/webdav/rfc7232.html#rfc.section.2.3.3.p.4.1)

**Comment by mnot** [comment]
@annevk can you make a straw-man proposal here?

**Comment by annevk** [comment]
There's two things to define, as I see it, the contract of an individual content coding. Which is effectively a transformation on the payload and returns a stream of bytes that can error. All content codings would have to follow that format.

And then there's the handling of a sequence of content codings, which needs to deal with dispatching to those individual algorithms and dealing with unsupported values.

And per https://github.com/whatwg/fetch/issues/716 whether something is supported might depend on certain external variables, such as whether HTTPS is used, but covering that algorithmically might be a bridge too far.

**Comment by mnot** [comment]
Thanks, Anne.

For better or worse, HTTP is defined primarily using ABNF and prose requirements. It sees to me that specifying it using more formal contracts is a significant divergence in specification style, and if we're going to do that, it should be done consistently across the document set. That seems like it's out of scope for this effort.

If you know of any ambiguities in the document(s) that make it impossible or difficult to infer such a contract, please raise those as issues.
