### ISSUE TITLE
"17.15.1. Confidentiality of Credentials" refers to TLS

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#586]
" For example, services that depend on individual user authentication often require a connection to be secured with TLS ("Transport Layer Security", [RFC8446]) prior to exchanging any credentials."

This originates from RFC 7235.

Nowaday, shouldn't we instead say "require HTTPS"?

**Comment by royfielding** [comment]
I think it should be 

   ... authentication require a secured connection prior to exchanging any credentials (ref target="https.uri").

and x:ref around the term "secured" (defined in that section).
