### ISSUE TITLE
Reason phrase

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#60]
It would be good to clarify two things:

1. Reason phrase is an optional part of the protocol and new wire formats must exclude it.
2. When a wire format excludes it, (legacy) APIs must use the empty string for it.

I don't have tests for 2 unfortunately, but there's rough agreement in https://github.com/whatwg/fetch/issues/599, including it seems from mnot, that it's a good approach.

**Comment by annevk** [comment]
I should mention that I got some pushback on 2 in https://bugzilla.mozilla.org/show_bug.cgi?id=1397646, though the alternative proposed does not strike me as ideal (leaving this undefined).

**Comment by reschke** [comment]
I don't think I agree with 1 or 2.

**Comment by annevk** [comment]
Care to elaborate?

**Comment by reschke** [comment]
1. It is optional, but I don't see why we would require it to be excluded from new formats.
2. I also do not see why we would make API requirements.

**Comment by mnot** [comment]
I tend to agree that the HTTP spec shouldn't be making hard requirements for APIs or tying the hands of future versions of the protocol in this way. That said, clarifying the optionality and unreliability of the reason phrase would be good.

**Comment by annevk** [comment]
I don't really agree. It seems a lot better if it's not optional, but is instead always the empty string in H/2. Otherwise you get proxies inserting it and such.

**Comment by reschke** [comment]
What's the harm of proxies inserting something here?

(FWIW: my choice would have been not to remove it in HTTP/2)

**Comment by mnot** [comment]
Because it's an attractive nuisance - applications think it's an end-to-end signal, and it's not.

**Comment by reschke** [comment]
It is, but I think the confusion we have caused by not having it in HTTP/2 far outweighs any potential benefit.

**Comment by mnot** [comment]
Even before H2, it wasn't reliable; some implementations overwrite whatever is put in there.

**Comment by mnot** [comment]
Currently in Messaging - [Status Line](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#status.line):

> The reason-phrase element exists for the sole purpose of providing a textual description associated with the numeric status code, mostly out of deference to earlier Internet application protocols that were more frequently used with interactive text clients. A client should ignore the reason-phrase content.

Suggest adding:

> ... A client should ignore the reason-phrase, because it is not transmitted in other versions of HTTP, and is overwritten by some HTTP/1.1 implementations. As such, it is not a reliable channel for information.

**Comment by reschke** [comment]
s/is not transmitted in other versions of HTTP/is not transmitted in some other versions of HTTP/

**Comment by mnot** [comment]
+1 to the edit.

Not intended to be a requirement. Ought (should?) we revert all of the "ought"s to "should" if we adopt  RFC8174?

**Comment by mnot** [comment]
Changing ought to should would allow us to escape from [RFC6919](https://tools.ietf.org/html/rfc6919)'s baleful glare...

**Comment by reschke** [comment]
https://en.wikipedia.org/wiki/Wikipedia:If_it_ain%27t_broke,_don%27t_fix_it

**Comment by royfielding** [comment]
Umm, it is already an existing requirement.  Uppercase.

> A client SHOULD ignore the reason-phrase content.

I would change it to

> A client SHOULD ignore the reason-phrase content because it is not a reliable channel for information (it might be discarded or overwritten by intermediaries).

**Comment by mnot** [comment]
WFM.
