### ISSUE TITLE
import 421 (Misdirected Request) Status Code from h2

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#622]
I think we need to copy the 421 status code definition from [Section 9.1.2 of RFC7540](https://httpwg.org/specs/rfc7540.html#MisdirectedRequest) since it is generally applicable for rejecting a misdirected request.

**Comment by royfielding** [comment]
curious if @martinthomson has an opinion on moving 421 to http-core

**Comment by martinthomson** [comment]
A slight preference for moving it, I think.

**Comment by mnot** [comment]
Since we're doing h2bis and since it is applicable more broadly, I agree.

**Comment by reschke** [comment]
When doing so, we need to consider https://www.rfc-editor.org/errata/eid4666

**Comment by royfielding** [comment]
Hmm, the errata is about the cacheable paragraph (which is now heuristically) and I was going to remove that for the same reason but decided to import without changes first. I am just going to remove it now.

**Comment by reschke** [comment]
That  might work as well; but then we'll have to mention in "changes" that the default changed.
