### ISSUE TITLE
2.3 Length Requirements

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#634]
> When a received protocol element is parsed, the recipient MUST be able to parse any value of reasonable length that is applicable to the recipient's role and that matches the grammar defined by the corresponding ABNF rules. 

This MUST is very fuzzy, and obviously isn't testable. Should it just be prose?

**Comment by reschke** [comment]
Not convinced, but wouldn't object. Maybe "needs to"?

**Comment by royfielding** [comment]
That's what makes the ABNF normative. I don't see a need to change it now.

**Comment by mnot** [comment]
Sorry, what does the ABNF have to do with this? The issue is the phrase "MUST be able to parse any value of reasonable length", where "reasonable length" is not defined.

**Comment by royfielding** [comment]
It is defined as being reasonable. I have not problem testing that (subjectively). ;-)

**Comment by royfielding** [comment]
> Sorry, what does the ABNF have to do with this? The issue is the phrase "MUST be able to parse any value of reasonable length", where "reasonable length" is not defined.

I meant the second half.

**Comment by royfielding** [comment]
How about

> A recipient SHOULD parse a received protocol element defensively, with only marginal expectation that the element conforms to the ABNF and can be parsed within the scope of a reasonable buffer.

**Comment by mnot** [comment]
I like it
