### ISSUE TITLE
"Captive Portal"

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#637]
3.6 refers to a captive portal as a type of intermediary; we should make sure this aligns with the more recent CAPPORT drafts (IIRC current usage of that term is for the origin that the user is redirected to when captured; it's not an intermediary).

**Comment by martinthomson** [comment]
It is probably enough to strike "captive portal".  "Interception proxy" will do, if "attacker" does not.

The term was never something that RFC 7230 relied on and as you say the modern understanding of the term has evolved.
