### ISSUE TITLE
introduce both 1.1 and 2.0

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#64]
The introduction should reference the currently defined wire formats (1.1 and 2, also 1.0 maybe).

We also need to figure out whether and where to mention differences:

- expect/continue
- transfer codings
- status phrase

**Comment by mnot** [comment]
Also, the current introduction to all three documents says:

> HTTP is defined by a series of documents that collectively form the HTTP/1.1 specification

That needs to be adjusted to something like:

> HTTP is defined by [semantics] and [caching], and is mapped to specific wire protocols as versions; currently, [http/1.2] and [http/2] are defined.

**Comment by MikeBishop** [comment]
> > HTTP is defined by [semantics] and [caching], and is mapped to specific wire protocols as versions; currently, **[http/1.2]** and [http/2] are defined.

HTTP/1.2?  Is there something you need to share with the working group, @mnot?  😉

**Comment by royfielding** [comment]
I think (but am not sure) that this has been covered by the changes made in #416 

Maybe @MikeBishop and @martinthomson could have a look and see if the short HTTP/2 and HTTP/3 descriptions need more flowers.

**Comment by martinthomson** [comment]
I think that the number of flowers (->0) is entirely appropriate and I would be happy with those descriptions, with maybe a small tweak to the HTTP/3 text.

**Comment by mnot** [comment]
I left a review; once we resolve comments on the PR, I think this can be closed.
