### ISSUE TITLE
header-field ABNF problem

### ISSUE THREAD

**Issue by martixingwei** [httpwg/http-core#65]
the header-field is defined as:

     header-field   = field-name ":" OWS field-value OWS
     field-name     = token
     field-value    = *( field-content / obs-fold )
     field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
     field-vchar    = VCHAR / obs-text
     obs-fold       = CRLF 1*( SP / HTAB )
                    ; obsolete line folding
                    ; see Section 3.2.4
     VCHAR          = %x21-7E; visible (printing) characters

It seems that `SomeName:a<space>b<space>c` does not match the rule but `SomeName:a<space>bc<space>d` does match.

Is this intentional?

**Comment by martixingwei** [comment]
I proposed a solution as following:

    field-value    = field-content *( ( RWS / obs-fold ) field-content )
    field-content  = *field-vchar

**Comment by reschke** [comment]
I don't understand the problem. Why doesn't it match?

**Comment by martixingwei** [comment]
`field-value` is any number of `field-content` repeated. `field-content` matches 1 or 2 `field-vchar` with space in between (if 2 `field-vchar` matched), thus any `field-content` must begin and end with `field-vchar`. For `a<space>b<space>c`, there is no way to fit two consecutive `field-content`s into it. 

The first `field-content` will use `a<space>b`, but then `<space>c` left, which cannot be another `field-content` because it does not begin with `field-vchar` (`<space>=%x20`).

**Comment by martixingwei** [comment]
Yes.
