### ISSUE TITLE
Multiple kinds of payload in HTTP/2 and HTTP/3 conflict with payload terminology from core and RFC7230

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#654]
Taking another look at the problems surrounding the term "payload", I went to see what was being used in h2 (RFC7540) and HTTP/3. Unfortunately, they use both "payload body" (h2, 7230) / "payload data" (h3, http-core) and also "frame payload" (h2, h3).

So, at various times, DATA payload != payload data, but a DATA payload might contain the payload data if it happens to be the only DATA frame.

Just shoot me.

**Comment by royfielding** [comment]
Maybe we should just go back to calling it the "request body" or "response body"?

**Comment by royfielding** [comment]
Note that this is time-sensitive for h3 and @MikeBishop and would slightly impact h2 and @martinthomson.

**Comment by royfielding** [comment]
Or perhaps call the core payload concept "content" and use "payload" for messaging/frames.

**Comment by reschke** [comment]
Note that making this change will require changes in draft-ietf-quic-http.

**Comment by royfielding** [comment]
Yes, I'd like to decide this editorial change ASAP, but we can also prepare an editorial PR for HTTP/3 in parallel for @MikeBishop. That would be a much smaller change since most usage of payload in that document refer to frame payloads.
