### ISSUE TITLE
mention payload -> content in changes from... 

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#675]

**Comment by royfielding** [comment]
... RFC7230 + RFC7231?

This would be noting an editorial change, but okay.

**Comment by mnot** [comment]
People who are reading other specifications that use the old terminology may have questions.

**Comment by mnot** [comment]
Also worth putting 'body' in context, since many (e.g., the Fetch API) still use that term.

**Comment by annevk** [comment]
I could do that directly in Fetch as part of https://github.com/whatwg/fetch/issues/1136. I'll have to do some reading though as I've lost the plot a bit. 😊
