### ISSUE TITLE
Styling issue in message/http registration

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#676]
This is probably for @reschke and his tool chain, but the first line of this doesn't look great:

![image](https://user-images.githubusercontent.com/67641/104677214-23317f00-573d-11eb-8a5f-56ab0a31bd70.png)

**Comment by reschke** [comment]
Should be fixed by https://github.com/reschke/xml2rfc/commit/53d257204e889963b48818890d598dd562f99324
