### ISSUE TITLE
close connection item lost its definition

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#678]
The close connection item used to be defined in Connection as

```
   The "close" connection option is defined for a sender to signal that
   this connection will be closed after completion of the response.  For
   example,

     Connection: close

   in either the request or the response header fields indicates that
   the sender is going to close the connection after the current
   request/response is complete (Section 6.6).
```

whereas now its effect is described in Messaging without definition.

I think it should be defined somewhere.

**Comment by mnot** [comment]
[Messaging 9.3](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#persistent.connections) gets pretty close to that text:

> The "close" connection option is used to signal that a connection will not persist after the current request/response. 

... with text below that elaborates. What do you want to see here?
