### ISSUE TITLE
message parsing robustness

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#68]
... is awfully far from the definition of the message format; IME people read the start of section 3 in isolation and don't see the text below. Maybe move 3.5 up?

**Comment by mnot** [comment]
How about moving the three paras starting with "Although the line terminator..." to 2.1, and moving the `CRLF` out of the definition of `request-line` and `status-line` into `HTTP-message`, to be consistent with `header-field`? Then all of the text about `CRLF` is in one place.

**Comment by annevk** [comment]
See also #62.
