### ISSUE TITLE
URI-ID or DNS-ID?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#680]
Discovered via a question @kaduk asked; it appears that 8aa1781d4fa7d25ab946f6cb1dd1b337435e0a17 made the change to require looking for URI-IDs in the certificate and I don't see any follow-up discussion on that in #404.  However, I've never seen a certificate that offers a URI-ID for an HTTP endpoint.  Shouldn't this be a DNS-ID to match current usage?  Or perhaps either, with URI-ID preferred, if we believe that's the future?

**Comment by royfielding** [comment]
Er, right, my mistake -- I was trying to describe it as verifying a URI as input, not as looking only at the certificate field for URI-ID. It should be either be left unsaid because it is defined by that RFC, or do we need to specify DNS-ID with maybe URI-ID as a backup?

**Comment by kaduk** [comment]
I am not entirely sure that there is need to mention URI-ID (I, for one, don't know of usage of it with HTTP; I barely know of usage of it at all).
My understanding is that current practice prefers DNS-ID with a grudging tolerance for CN-ID as fallback (though there are efforts underway to fully deprecate use of CN-ID).

Note also that when referencing the RFC 6125 procedures, the protocol document is expected not only to specify what name and type are to be used as input to verification, but also whether wildcard certificate are allowed.  It is sometimes also useful to give instruction about what procedures are to be used for revocation checking, though 6125 does leave that explicitly out of its own scope.

I am also trying to promote the definition and use of "IPADDR-ID" for the iPAddress SAN, but that's somewhat unrelated.

**Comment by MikeBishop** [comment]
Do we want to state a position on adoption of URI-ID?  If not, then I think we say DNS-ID and MAY consider CN-ID, plus the wildcard language.  I'm not aware of anything to reference for IPADDR-ID, and this doesn't seem like the place to define it.

**Comment by richsalz** [comment]
Please don't use CN for anything.  Nor rfc822Address nor domainComponent.

**Comment by royfielding** [comment]
I'll be happy to accept any change here that folks generally agree to, preferably in the form of a PR. I already tried just writing it myself and that's what we have now, but it's wrong because I haven't implemented this myself.
