### ISSUE TITLE
Should -messaging obsolete RFC 1945

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#681]
HTTP/1.0 still exists, but it might be time to make it clear that we don't think it's the right protocol to use any more.  RFC 1945 is current Informational, which means we haven't ever really said it was good, but obsolescence might help.

It does mention HTTP/1.0 a few times, but only in reference to backwards compatibility.

**Comment by mnot** [comment]
I don't think so, for the same reason 2 doesn't obsolete 1.1.

**Comment by royfielding** [comment]
IIRC, informational documents can't be obsoleted because they are not on the standards track.

**Comment by royfielding** [comment]
In any case, I think if we bothered with such a thing it would be a move to Historic(al) rather than Obsoleted.

**Comment by martinthomson** [comment]
Not sure about the status being relevant here (as in I don't know, not question Roy's claim, which, if true, might answer this fine).

However,
> I don't think so, for the same reason 2 doesn't obsolete 1.1.

This is materially different, I think.  We've always been clear that HTTP/2 is not for everyone and that it would co-exist with HTTP/1.1.  But in reading through these documents, it is clear that there is no reason to do HTTP/1.0 (or HTTP/0.9 for that matter).  That speaks to the older versions being truly obsolete.

Historic(al) would be another way to address this, but my impression is that is for those documents that are completely irrelevant and that might not ever be the case for RFC 1945.

**Comment by annevk** [comment]
What does truly obsolete mean here? As far as I know we still have to support 0.9...

**Comment by reschke** [comment]
IMHO:

@martinthomson - "obsoletes" would only be correct if the spec would fully define HTTP/1.0

I agree with @royfielding that - if we want to do something - moving 1945 to "historic" would be correct. But this does not need to be done by this spec after all; a "decision" by the WG communicated to the IESG should be sufficient.

**Comment by mnot** [comment]
I agree with @reschke. Let's leave this issue open and discuss it at the interim; if the outcome is along those lines, we can de-couple it from core.

**Comment by mnot** [comment]
Discussed in Feb 2021 interim; close with no action. Can move to Historic separately if we wish.
