### ISSUE TITLE
Field section gone?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#682]
It appears that the term "field section" has been mostly excised from the document; it now appears only once, in [the first sentence of Section 5.2](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.5.2.p.1).  Is that instance intended to remain, or was it an oversight when the term changed again?

**Comment by MikeBishop** [comment]
Or is it simply that "header field section" and "trailer field section" are collapsed to "header section" and "trailer section" respectively, and "field section" remains the generic term to encompass both?

**Comment by mnot** [comment]
^ this

**Comment by mnot** [comment]
Mike, are you OK if we close this with no action?

**Comment by MikeBishop** [comment]
Yes, that's fine.
