### ISSUE TITLE
Assumed properties of new methods

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#692]
In general, an unknown or new method can be handled by a resource by rejecting the request (with 406 for instance).  However, some entities (intermediaries in particular) might be forced to engage with methods that are unknown to them.

I couldn't find text in [Section 7.6](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#message.forwarding) or Section 16.1 on this.  However, the draft might benefit from advice on this.  There are a few things that might be said, with reference to Section 9, which already says much of this:

* Intermediaries are expected to forward new methods.  This enables the deployment of new methods.

* New methods might be safe, idempotent, or cacheable.  Or they might not be.  Actions taken need to consider this possibility and act accordingly.  For instance, an intermediary that might be able to automatically retry a request cannot do so for an unknown method, which it does not know whether it is idempotent (9.2) or a cache can't cache a response unless the method is known to be cacheable (9.3).

**Comment by mnot** [comment]
PTAL. I don't think your second bullet is actionable; that's already clear in 16.1, and intermediaries aren't required to do any of those things.
