### ISSUE TITLE
Whitespace is not removed from field values in HTTP/2 or HTTP/3

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#697]
[This claim](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.5.5.p.5) in Section 5.5 is likely incorrect:

> Leading and trailing whitespace in raw field values is removed upon field parsing (e.g., Section 5.1 of [Messaging]).

Does it need qualification (in some versions) or permission (could be removed)?

**Comment by reschke** [comment]
"could be removed" or "can be removed" seems accurate.

**Comment by mnot** [comment]
I think the question here is _when_ it's removed. My understanding is that it is removed for the purposes of matching ABNF, and it's removed when the value is used, but it's not necessarily removed automatically when an implementation hands a value to an application.

**Comment by reschke** [comment]
But if the WS is not removed *before* the value is passed to the application, it might not be removed at all.

What do HTTP/2 implementations *do* here?

**Comment by mnot** [comment]
Discussed in Feb 21 interim; need to focus on interpretation of field, not e.g., forwarding. Should be a requirement.

**Comment by annevk** [comment]
It would have nice if it was an error to have leading/trailing field value whitespace in newer HTTP versions. Probably too late now, though perhaps not for H/3?
