### ISSUE TITLE
new header field considerations: list vs keyword

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#7]
Discuss when it's appropriate to do something like

   "*" / #vary

(mainly error handling)

**Comment by mnot** [comment]
I'd prefer to document this as an anti-pattern; it's error-prone and confusing.

**Comment by reschke** [comment]
I agree, but when I objected for alt-svc I apparently was in the rough.

**Comment by royfielding** [comment]
*shrug*

**Comment by mcmanus** [comment]
ietf104: agree that we should discourage this for new header (fields)

**Comment by reschke** [comment]
Ok. So before addressing this in the "new header field considerations", we better fix the grammar for "Vary" first. Opening a new ticket...

**Comment by mnot** [comment]
I think we said we could close this with no action, correct? @reschke

**Comment by reschke** [comment]
Yes.
