### ISSUE TITLE
Is a prohibition against mixed line termination a requirement?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#703]
[This text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.3.3.p.2) implies a requirement: 

> HTTP allows the transfer of text media with plain CR or LF alone representing a line break, when such line breaks are consistent for an entire representation.

I would have said instead that HTTP itself doesn't care whether content adheres to this stricture, though some implementations could (or MAY) normalize line endings before sending or after receiving content that uses a `text` media type.

**Comment by reschke** [comment]
Maybe we can improve the spec by just killing the whole subsection? It refers to the canonical form in MIME, then say we don't neef that, and then makes recommendations for text/* that AFAIU everbody ignores.
