### ISSUE TITLE
Content-Length and Transfer-Encoding coexistence

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#704]
Does [the following statement](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.6.p.5) better belong in -messaging?

> A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field.

**Comment by reschke** [comment]
Into 6.2?

**Comment by martinthomson** [comment]
Seems like the best place, yeah.

**Comment by reschke** [comment]
@martinthomson : https://github.com/httpwg/http-core/pull/747#pullrequestreview-584926069
