### ISSUE TITLE
From and authentication

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#708]
[This text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.10.1.2.p.7) is saying something about using From for authentication, but I don't understand it:

> A server SHOULD NOT use the From header field for access control or authentication, since most recipients will assume that the field value is public information.

I think that this could be saying one of two things, maybe the latter:

1. From contains only an unsupported claim about the identity of the generator of the message, so it can't be used for authentication.
2. Including a From value that also contains a secret, such as a password, that could be used to authorize a request is unwise because recipients of the message won't necessarily treat the value as confidential and so the secret might leak.

That latter is a bit strange, because an authorization could be bound to the specific request in various ways that might limit these risks.  I can't tell because the logical chain between "this is who made the request" and use of the value for authorization isn't very well developed.

It might be better to say nothing here instead.

**Comment by mnot** [comment]
My .02 - I think the intent was more the first -- just a warning that this is not an authentication mechanism to ward off the uninformed and optimistic. Given that this isn't widely used anyway, I don't think the text causes harm; I propose we just leave it as is.

**Comment by martinthomson** [comment]
Please, drop everything from "since" onward in that case.  The reasoning makes no sense to me and the unsupported recommendation is clear enough.

**Comment by royfielding** [comment]
> Please, drop everything from "since" onward in that case. The reasoning makes no sense to me and the unsupported recommendation is clear enough.

+1
