### ISSUE TITLE
Should Charset mention UTF-8

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#713]
[Accept-Charset](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.accept-charset) is deprecated due to the ubiquity of UTF-8, but the [Charset](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#charset) section makes no mention of UTF-8.  This might be worth a mention.

**Comment by annevk** [comment]
It's only used for `Accept-Charset` though and that section already mentions UTF-8. As does the Media Type section. Since `Accept-Charset` is deprecated, perhaps the `charset` production should simply be removed and `Accept-Charset` takes `token` directly?

**Comment by royfielding** [comment]
Accept-Charset is deprecated primarily for privacy. It also happens to be less useful now because of utf-8. In contrast, the charset parameter is still used most of the time, mainly to reduce sniffing. We can add something about utf-8, but promoting it too hard will cause other (social) problems.

**Comment by reschke** [comment]
@annevk's observation is correct. But then, charset is used in Content-Type as well, just not referenced directly as it is used over there as a regular parameter.

**Comment by annevk** [comment]
It's not clear to me at least that the `charset` production section also applies to `Content-Type`.

**Comment by reschke** [comment]
Syntactically, it does not (because that relies on a more generic syntax for arbitrary parameters).

But I agree, this needs cleanup.

**Comment by reschke** [comment]
Proposal is to remove the ABNF production and to clarify the text (so that it applies to Content-Type as well).
