### ISSUE TITLE
Content-Length on requests

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#723]
[This text]():

> A user agent that sends a request containing a message body MUST send a valid Content-Length header field if it does not know the server will handle HTTP/1.1 (or later) requests;

...has a condition on the conformance requirement that suggests that clients that do know the server will support HTTP/1.1 (or later) can do something else.  But it doesn't really address what constraints then apply.  I think that this was just to permit the use of the chunked transfer encoding for delimiting the message body, but that does not follow.

I think that this might be rephrased as follows:

> A user agent that sends a request that contains a message body MUST send either a valid Content-Length header field or use the chunked transfer coding.  A client MUST NOT use the chunked transfer encoding unless it knows the server will handle HTTP/1.1 (or later) requests;

**Comment by royfielding** [comment]
It reads the same to me, but +1.
