### ISSUE TITLE
TLS does not require clean close for resumption

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#725]
A clean close of the original connection was a requirement for use of resumption in previous versions of TLS, but TLS 1.3 does not have that same requirement.

I just checked, which was tedious.  Then I found this in RFC 5246:
> Note that as of TLS 1.1, failure to properly close a connection no longer requires that a session not be resumed.

This calls into question the entirety of [Section 9.8](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#tls.connection.closure).  I think that the only requirement regarding the TLS close_notify alert needs to apply only when framing responses that don't have `Transfer-Encoding: chunked` or `Content-Length`.  That might make this section much simpler.

Also, I note that this section uses the term "reuse", which is not consistent with "resume" or "resumption" in TLS.  If there is any need for mention of TLS resumption, then the TLS term should be used.

**Comment by royfielding** [comment]
Fixed by #734
