### ISSUE TITLE
Arbitrary limitation on authentication parameters

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#733]
[semantics 11.2](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#auth.params)  requires `credentials` to be either `token68` or `auth-param`. 

`token68` seems arbitrarily limited -- In particular, it does not allow `:`, which rules out an authentication scheme carrying a URL (unless it's in a parameter).

Does this limitation serve any purpose? I can understand disallowing `=` inside the content, and `"` and `,` for obvious reasons, but not other characters.

**Comment by reschke** [comment]
token68 is for backwards compat with Basic; it has no extension point. New schemes should always use auth-param, which allows both token and quoted-string.

**Comment by mnot** [comment]
Bearer does not, and it artificially constraints its payload to fit into token68. I suggest that's evidence of schemes voting with their feet.

**Comment by reschke** [comment]
AFAIR: The definition of Bearer (in internet drafts, not as published RFC) predates the text in RFC723x by multiple years.

**Comment by reschke** [comment]
Proposal: close with no action.

**Comment by mnot** [comment]
Discussed in Feb 21 Interim; seems to be too much inertia to change.
