### ISSUE TITLE
Default port for CONNECT

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#736]
The [authority form](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#authority-form) as used for CONNECT describes the request target as comprising an authority, which consists of an IP or reg-name and, optionally, a port number.  The example shows an explicit port of 80.

What happens if an explicit port is not included?  Does the proxy use the port number associated with the implied protocol (80 if the inbound connection is TCP without TLS, 443 if it is TLS)?  Or is it an error?

As far as I am aware, a port is always provided in practice.  Maybe the answer is to explicitly require that the port number is always present and note that no default port can be supplied in this case as there is no scheme and therefore no associated default port.

**Comment by mnot** [comment]
cc @kazuho

**Comment by kazuho** [comment]
@martinthomson 
> Maybe the answer is to explicitly require that the port number is always present and note that no default port can be supplied in this case as there is no scheme and therefore no associated default port.

+1. This is the most natural outcome based on our established consensus in H2 and H3 that CONNECT requests is not accompanied by a scheme.

**Comment by royfielding** [comment]
It's supposed to be a 400 error.

**Comment by royfielding** [comment]
I verified that Apache mod_proxy will respond with 400 if there is no ":" or if the port is empty or non-numeric, and 403 if the port is not configured for use.
