### ISSUE TITLE
SEMANTICS describes CONNECT in HTTP/1.1 terms

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#737]
I think the goal was for SEMANTICS to stay out of message framing and leave that to the individual mappings.  It currently says this about CONNECT:

> Any 2xx (Successful) response indicates that the sender (and all inbound proxies) will switch to tunnel mode immediately after the **blank line that concludes the successful response's header section; data received after that blank line** is from the server identified by the request target.

Perhaps this should simply talk about data received after the header section, and leave the boundaries of that version-specific?

**Comment by royfielding** [comment]
Yes, we just missed a spot. Willy noticed this one as well. It should be something like

> Any 2xx (Successful) response indicates that the sender (and all inbound proxies) will switch to tunnel mode immediately after the response's header section; data received after the header section is from the server identified by the request target.

**Comment by wtarreau** [comment]
Yes, I wanted to suggest "header section" as well as it's the term used in messaging. There is a second occurrence of this one in "15.2.2 - 101 Switching Protocols" : "will be switched to immediately after the empty line that terminates the 101 response".
