### ISSUE TITLE
Semantics 2.4 Error Handling  

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#738]
[2.4](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-error-handling)

> HTTP does not define specific error handling mechanisms except when they have a direct impact on security

This could use a bit more details considering “security” is a rather vague term, e.g. references to any examples in this spec.

**Comment by mnot** [comment]
My .02 - adding examples here won't clarify the spec, and will make it longer. I think this should be closed with no action.
