### ISSUE TITLE
Semantics 3.3 Connections ...

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#739]
[3.3](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-connections-clients-and-ser) 

> reliable transport- or session-layer connection

TCP is not strictly a reliable transport. A definition here will be useful such as “reliable connection that ensures in-order, lossless delivery of (content octets?)" 

===

What does this mean to HTTP/3 over unreliable datagrams?

**Comment by mnot** [comment]
QUIC provides reliability that is at least equivalent to TCP. We refer to QUIC as a transport protocol even though it's composed on top of UDP.

I'm not convinced that expanding the definition of 'reliable' adds a lot of value to the specification...

**Comment by wenbozhu** [comment]
I am not really sure about the current state of HTTP/3 over QUIC datagrams such as [this proposal](https://tools.ietf.org/html/draft-schinazi-quic-h3-datagram-05).  It's probably the right thing to consider QUIC datagram (as a transport) out of the scope of http-core.

===

The definition of reliable transport is largely academic.
