### ISSUE TITLE
WGLC: Mid-stream trailers

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#740]
[6](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-message-abstraction)

> However, multiple trailer sections interleaved with content have only been deployed as frame extensions.

Trailers that come after the body has well-defined semantics (i.e. metadata applicable to the entire body). 

Interleaved, mid-stream trailers are considered and implemented as extensions, and maybe we should delay adding them to the core semantics. 

This is however an important topic for HTTPAPI, IMO.

**Comment by reschke** [comment]
See related mailing list thread at <https://lists.w3.org/Archives/Public/ietf-http-wg/2021JanMar/0070.html>.

**Comment by mnot** [comment]
Discussed at Feb 21 interim; sentiment is to remove it; @royfielding to create a PR.
