### ISSUE TITLE
Semantics: 7.6.3 typo?

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#742]
> Via: 1.0 ricky, 1.1 mertz, 1.0 lucy

Should this be

> Via: 1.0 ricky, 1.1 fred, 1.0 lucy

**Comment by reschke** [comment]
...this example goes back to RF 2068.

Is your point that when combining values, one of the pseudonyms should be preserved?

**Comment by royfielding** [comment]
The example is correct.

**Comment by wenbozhu** [comment]
I could be wrong but I thought the example meant to show the following 

1.1 ethel, 1.1 fred  => combined into =>   1.1 fred

**Comment by royfielding** [comment]
It's just an example.
