### ISSUE TITLE
Semantics: 9.2.2 Idempotent Methods

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#744]
>  A client SHOULD NOT automatically retry a failed automatic retry.

Not sure why this is mentioned or relevant, or if this is the case.  

Do you mean "a client should not  automatically retry a failed non-idempotent request"?

**Comment by royfielding** [comment]
It means that the client should not go into an infinite loop of retrying a request that has failed.

**Comment by mnot** [comment]
This text seems clear to me as written.

**Comment by martinthomson** [comment]
It's clear, but why not say "A client MUST limit the number of attempts it makes for the same request."  Or similar?

**Comment by wenbozhu** [comment]
Maybe even drop this sentence since the exact retry behavior is very implementation or application specific.

**Comment by royfielding** [comment]
> It's clear, but why not say "A client MUST limit the number of attempts it makes for the same request." Or similar?

Because then we will get comments asking that we define a limit. One, two, N?

In 2616, it said

> The automatic retry SHOULD NOT be repeated if the second sequence of requests fails. 

but we changed that because we wanted all requirements to be complete sentences with role scope.

**Comment by mnot** [comment]
@wenbozhu this is only automatic HTTP library retries, not application retries. 

I think we can close this with no action, unless the WG thinks we want to revisit retries again.

**Comment by wenbozhu** [comment]
My experience is that implementations will either not retry or retry multiple-times.

If you believe retry-at-most-once is a widely implemented spec feature (at least by browsers), then the current text looks good.

Thanks for the clarification.

**Comment by martinthomson** [comment]
My recollection is that Firefox retries up to 10 times in certain cases.  Patrick had a story about reducing the number and that resulting in bustage.

**Comment by mnot** [comment]
IIRC that was limited to when the transport connection failed and no part of the response was received; @mcmanus can you elaborate (and give your thoughts about whether this needs a change)?

See also context in #27.

**Comment by mnot** [comment]
Without data showing that we're able to converge on something that will get supported, I'm wary of making a specific changes here. SHOULD NOT gives wiggle room for multiple retries under specific circumstances. So, my inclination here is to close with no action.

**Comment by wenbozhu** [comment]
The text in [2616 ](https://github.com/httpwg/http-core/issues/744#issuecomment-776253484) reads slightly more clear to me. Otherwise, agreed to close with no action.

Optimistic retries (idempotent or not) over transport failures are mostly an implementation detail, and are not recommended for non-idempotent requests as already mentioned in the same paragraph.
