### ISSUE TITLE
Semantics: 11.6.2 Authentication

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#745]
Is there a process to fix the naming?

- Authorization header => Authentication
- Proxy-Authorization => Proxy-Authentication
- 401 (Unauthorized) => 401 (Unauthenticated)

The status name may be easier to change?

**Comment by martinthomson** [comment]
If we could fix field names, do you think that we would still have Referer?

Changing the status thing is likely not to have any real effect.  For some reason, there is lots of software that has these strings hard-coded.

**Comment by reschke** [comment]
The status name would need to change to "Unauthenticated or Unauthorized" :-)

Proposal: close with no action.

**Comment by royfielding** [comment]
We can't change the names. We can update reason phrases when there is a compelling reason, but I don't see one here. 401 is used for both unauthorized and unauthenticated.

**Comment by wenbozhu** [comment]
I didn't know 401 could be used for unauthorized too. Thanks for the clarification.
