### ISSUE TITLE
messaging 2.3: version (rewriting by intermediaries)

### ISSUE THREAD

**Issue by wtarreau** [httpwg/http-core#751]
It's written:

> Intermediaries that process HTTP messages ... MUST send their own HTTP-version in forwarded messages```

Actually I'd rather say "MUST send a version no higher than their own in forwarded messages" (poor wording, I know, maybe someone can propose better).

Indeed, if an intermediary receives an HTTP/1.0 request and passes it as HTTP/1.1, the server will wrongly assume that the client can deal with 1.1 (e.g. chunks) and the message may have to be degraded by the intermediary (such as de-chunking and rely on close only). Furthermore, seeing 1.0 for a server is often an indication of very limited (or possibly bogus) client. For example some intermediaries might avoid compressing or caching when facing HTTP/1.0 messages, and as such it's preferable to let such versions be properly advertised in messages that could be considered as potentially unsafe.

Maybe a different wording should be "intermediaries... MUST NOT pass a message showing a version they do not support, and MUST make sure the message always conforms to the advertised version".

**Comment by martinthomson** [comment]
I agree with Willy: the underlying requirement is that intermediaries accept and send messages only in versions that they understand (unless acting as a tunnel, I guess).  The original text basically means that, even if it is phrased in terms of what value is placed in a specific field rather than as the true requirement.

**Comment by mnot** [comment]
Discussed at Feb 21 interim; should work on a proposal to loosen this somewhat, at least for intermediaries. SHOULD + context?

**Comment by wtarreau** [comment]
OK let's try with that.
