### ISSUE TITLE
Semantics: How to know to stop parsing a header at CRLF?

### ISSUE THREAD

**Issue by miketaylr** [httpwg/http-core#754]
rfc2616 stated:

> Request (section 5) and Response (section 6) messages use the generic
   message format of RFC 822 [9] for transferring entities (the payload
   of the message).

If you hop over to rfc822(https://tools.ietf.org/html/rfc822#section-3.2) it defines the field meta-sytax:

> field       =  field-name ":" [ field-body ] CRLF

rfc7231 obsoletes 2616, and references rfc7230 which does define:

`HTTP-message = start-line *( header-field CRLF ) CRLF [ message-body]`

Just from reading the current -semantics draft (which obsoletes 7231 and *portions of 7230* (maybe not the parts I'm looking for?)), I can't see how to know that headers should be parsed until CRLF just from reading the current -semantics draft. 

Am I missing something obvious?

**Comment by reschke** [comment]
See <https://www.ietf.org/archive/id/draft-ietf-httpbis-messaging-14.html#name-message>

**Comment by wtarreau** [comment]
It's very possible that this sentence at the end of the section is not clear enough for those not used to the terminology here (let's keep in mind that what has become the norm for those of us dealing with this for more than a decade is not necessarily obvious and that these docs are primarily aimed at first-time readers):
```
This revision of HTTP separates the definition of semantics (this document) and
caching ([Caching]) from the current HTTP/1.1 messaging syntax ([Messaging]) to
allow each major protocol version to progress independently while referring to the
same core semantics.
```
What about something a bit more explanatory like this, which maybe we could adopt in each of the 3 documents to help newcomers quickly figure where to look:
```
This revision of HTTP relies on three distinct parts: HTTP/1.1 messaging
([messaging]), semantics (this document), and caching ([caching]). HTTP/1.1
messaging documents how HTTP/1.1 messages and protocol elements are
delimited, connection-specific header fields, and deals with all the operational
concerns of their byte-level representation. The Semantics document defines the
syntax and values of each header field and their relations with the payload,
regardless of any protocol version. The Caching document defines how and when
agents cache contents, and how to instruct them to change their default caching
behavior. Newer versions of the HTTP protocol will only use a different messaging
document and will use the same semantics and caching documents.
```
It's definitely not of the best style but maybe someone with a great writing style like Roy or Martin could help reformulate this better.

**Comment by miketaylr** [comment]
> See https://www.ietf.org/archive/id/draft-ietf-httpbis-messaging-14.html#name-message

Thanks @reschke. So it turns out I wasn't looking in the right place. :)

And +1 to the editorial suggestions given by @wtarreau. As someone relatively new to these specs, it's a nice improvement.

**Comment by mnot** [comment]
I think the original question has been answered here, so this can be closed. Willy, your suggestion is appreciated, but these specs are already very long, and do contain all of that information; I'm not convinced that repeating it helps.

**Comment by wtarreau** [comment]
I know but it's also because they're long that we know for sure that nobody reads them entirely. And having a short intro to mention the existence of the other docs and the relation with the current one doesn't seem bad to me (again, *we* know what semantics vs messaging are about, it's hardly obvious for newcomers).

**Comment by miketaylr** [comment]
> but these specs are already very long, and do contain all of that information; I'm not convinced that repeating it helps

But you only really know that after you read them all. A short intro seems like a win for outsiders and newcomers to the HTTP community.

**Comment by reschke** [comment]
@miketaylr - there is already an intro; it says:

> This revision of HTTP separates the definition of semantics (this document) and caching ([Caching]) from the current HTTP/1.1 messaging syntax ([Messaging]) to allow each major protocol version to progress independently while referring to the same core semantics.

So if you got there, you should have realized that questions specific to HTTP/1.1 are answered in [MESSAGING].

**Comment by miketaylr** [comment]
Respectfully I disagree with what I should have realized, given my own lack of knowledge of HTTP specs and history, but if the editors don't feel like this is worth an update, I'm not sure there is more to discuss.
