### ISSUE TITLE
Semantics: reliable transport and datagrams ...

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#769]
Related to [739](https://github.com/httpwg/http-core/issues/739)

If http-core mandates reliable transport, what happens if the mimetype (e.g. audio/video) can tolerate data loss. 

That is, HTTP will not tolerate loss of metadata or control messages (by peers, proxies or transport) but otherwise, any part of request/response payload may be lost or discarded in transit as indicated by the MIME type.

Does this make the spec somewhat more future-proof? There are probably proxies that already drop data for memory control etc?

And how http3/QUIC supports datagrams is then decoupled from http-core semantics, maybe.

**Comment by mnot** [comment]
There's been some discussion of unreliable HTTP delivery, but that would be an extension (e.g., CONNECT-UDP, currently being discussed in MASQUE; I could also see a header negotiating for an unreliable GET response). Core doesn't prevent such extension, and I don't think it needs to be accommodated here.

**Comment by wtarreau** [comment]
One difficulty with losses is to define the boundary around the possible parts that support losses. You can't lose random bytes, you need to lose entire datagrams, and HTTP doesn't provide provisions for this. It could be thought that chunk boundaries could define such datagrams at the connection level but that would mean connection-local lossy information. Maybe there an be some use around this, I don't know :-/
