### ISSUE TITLE
artwork -> sourcecode

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#771]
In most of the recent RFCs I've had published, the RPC has a preference for using `<sourcecode>` for example protocol elements, so we should probably switch.

Also, we've settled on using `<sourcecode type="http-message">` for example HTTP messages, and we have tooling to validate them.

**Comment by reschke** [comment]
That sounds like an issue that should be raised with the RPC. Examples in general are not sourcecode.

The aforementioned tooling can be extended to apply to artwork as well.

**Comment by mnot** [comment]
It can, but they have a registry of types, and the appropriate type is `http-message`, not `message/http`.

**Comment by reschke** [comment]
...which you registered yourself, instead of just using the one we had in the source for a decade :-).

Anyway, we can switch the type string if you want; but examples are not sourcecode.

**Comment by mnot** [comment]
We should ask them before submission; they've been doing it very consistently, and if it's going to change, I'd rather we do it.

**Comment by reschke** [comment]
see https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/195

**Comment by reschke** [comment]
see also https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/195#issuecomment-782245779
