### ISSUE TITLE
421 - how many retries?

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#789]
We're trying to integrate 421 support into Fetch, partially because we cannot always satisfy it (e.g., with upload streams) and I'm wondering what we should define to happen if you keep getting a 421 back on each new connection. It seems that browsers (Chrome and Firefox; Safari doesn't appear to support it) return the second 421, so it's retried once and doesn't result in a network error. Is that okay?

(https://github.com/web-platform-tests/wpt/pull/27322 has a test for this and https://github.com/whatwg/fetch/pull/1141 would end up defining this in Fetch.)

(As I understand it https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.421 is all the specification there is on this at the moment.)

cc @yoichio

**Comment by yutakahirano** [comment]
Chromium's implementation is  [here](https://source.chromium.org/chromium/chromium/src/+/master:net/http/http_network_transaction.cc;l=1168?q=421). I believe we retry only once.

**Comment by mnot** [comment]
If you have / discover multiple alternative services, you should continue trying them (disassociating any service that returns a 421) until you exhaust them and fall back to the 'native' service. If that produces a 421, I agree you should only retry once.

**Comment by annevk** [comment]
I guess there is no end-to-end integration of Alt-Svc either... Okay, we'll do this in small steps.
