### ISSUE TITLE
make sure all previous ADs are in the ACKs

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#799]

**Comment by reschke** [comment]
- Barry Leiba
- Alexey Melnikov

**Comment by royfielding** [comment]
Can I ask why? We have never done that in the past. I agree that we should ack ADs when they make contributions to the spec, just like we ack everyone else. I'd guess that applies to Barry and Alexey.

**Comment by royfielding** [comment]
And I certainly don't believe they deserve a paragraph. Sorry, I'd never allow that b.s. at Apache.

**Comment by reschke** [comment]
It occured to me during the last IETF meeting that we never thanked Barry,
