### ISSUE TITLE
clarify upgrade token case-sensitivity

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#8]
https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/0390.html

**Comment by reschke** [comment]
Citing @royfielding  selectively:

> They are case-sensitive.

I do not necessarily disagree, but don't see anything saying that, except for the use of the "token" ABNF production. Should we clarify?

**Comment by reschke** [comment]
Also, if we agree on the case-sensitivity, we should raise a bug report against RFC 6455.

**Comment by reschke** [comment]
Erratum against RFC 6455: https://www.rfc-editor.org/errata/eid5453

**Comment by royfielding** [comment]
Hmm, while the token is case-sensitive, that does not imply that a recipient must limit itself to case-sensitive match (unless, for some bizarre reason, two tokens that differ by case are distinctly implemented by the recipient).

**Comment by royfielding** [comment]
IOW, we should ideally write that the token is intended to be case-sensitive and senders SHOULD (or MUST) generate the same case as the registered token, but a recipient MAY interpret a received token case-insensitively (for robustness) when there is no potential for misinterpretation.

This is hop-by-hop, so no worries about intermediary confusion.

**Comment by reschke** [comment]
How is a recipient supposed to know whether there is no potential for misinterpretation?

If we allow the registry to contain "a" and "A" with different meanings, it can't know for sure.

If we don't allow that, the upgrade token essentially is case-insensitive, no?

**Comment by royfielding** [comment]
Because the recipient is going to choose one and signal what it is to the client. It isn’t going to choose something it hasn’t implemented, so it either has more than one implementation for different cases, or one for all cases, or one for the right case and ignores badly cased tokens. Forcing a given choice on the recipient in this situation is not going to improve interoperability because both ends have to agree.

**Comment by royfielding** [comment]
Okay, you have convinced me.  I don't want this to be confused with other uses of the protocol ABNF rule, but I don't see any value in registering case-confusing tokens.

**Comment by mnot** [comment]
In the meantime, in the [registry](https://www.iana.org/assignments/http-upgrade-tokens/http-upgrade-tokens.xhtml#http-upgrade-tokens-1):


> WebSocket | The Web Socket Protocol |   | [RFC6455]
> websocket | The Web Socket Protocol |   | [RFC6455][RFC8441]

**Comment by reschke** [comment]
@royfielding - so are you now ok with https://github.com/httpwg/http-core/pull/131 ?

**Comment by royfielding** [comment]
I updated the PR to make protocol-name case-insensitive (with preferred case registered).

**Comment by ioquatix** [comment]
Is this official yet?

**Comment by reschke** [comment]
What do you mean by "official"?

**Comment by ioquatix** [comment]
Is it published in any RFC? Should we depend on this behaviour?

**Comment by reschke** [comment]
The specs are currently in "IETF Last Call", ending June 10. See <https://lists.w3.org/Archives/Public/ietf-http-wg/2021AprJun/0154.html>.
