### ISSUE TITLE
GET conditioned over If-Match

### ISSUE THREAD

**Issue by liyishuai** [httpwg/http-core#800]
Consider a GET request conditioned over `If-Match` (I know it's nonsense, but the spec allows it). If the origin server does not have a current representation for the target resource, then the condition is false:
https://github.com/httpwg/http-core/blob/df2fefd530357474ecc7b0ef2f5b324371cdc878/draft-ietf-httpbis-semantics-latest.xml#L6963-L6978
Therefore, the server should respond 412:
https://github.com/httpwg/http-core/blob/df2fefd530357474ecc7b0ef2f5b324371cdc878/draft-ietf-httpbis-semantics-latest.xml#L7450-L7459
However, both Apache and Nginx responded 404.
Did I misunderstand some part of the specification, or are the servers violating the spec?

**Comment by reschke** [comment]
I just tried and got a 412 (on Apache):

~~~
> curl -v -H 'if-match: "foo"' https://www.greenbytes.de -o x.html
* Rebuilt URL to: https://www.greenbytes.de/
 ...
> GET / HTTP/1.1
> Host: www.greenbytes.de
> User-Agent: curl/7.55.1
> Accept: */*
> if-match: "foo"
>
...
< HTTP/1.1 412 Precondition Failed
< Date: Wed, 17 Mar 2021 05:04:13 GMT
< Server: Apache/2.4.46 (Debian)
< Strict-Transport-Security: max-age=15768000
< Upgrade: h2
< Connection: Upgrade
< Last-Modified: Wed, 23 May 2018 10:02:30 GMT
< ETag: "112f-56cdca204a0c4"
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Type: text/html
...
~~~

**Comment by liyishuai** [comment]
That's because the request target exists on the server. The following request gets 404:
```bash
curl -v -H 'if-match: "foo"' https://www.greenbytes.de/wat
```

**Comment by reschke** [comment]
I see (missed that part).

So the spec says (https://greenbytes.de/tech/webdav/draft-ietf-httpbis-semantics-latest.html#when-to-evaluate):

> Except when excluded below, a recipient cache or origin server MUST evaluate received request preconditions after it has successfully performed its normal request checks and just before it would process the request content (if any) or perform the action associated with the request method. A server MUST ignore all received preconditions if its response to the same request without those conditions, prior to processing the request content, would have been a status code other than a 2xx (Successful) or 412 (Precondition Failed). In other words, redirects and failures that can be detected before significant processing occurs take precedence over the evaluation of preconditions.

Note the last sentence.

**Comment by liyishuai** [comment]
I see. This justifies the servers' behavior.

However, the specification seems impossible to comply with: Before processing the request, the server cannot predict if it might fail into 500/503 errors, and therefore MUST:
1. Dry-run the request without conditions;
2. Guarantee that the status code is either 2xx or 412;
3. Evaluate the preconditions; and upon true,
4. Really process the request.

The specification should clarify what are the "redirects and failures that can be detected before significant processing occurs".
In my GET example, evaluating the `If-Match` condition involves determining whether the target resource exists or not, so prioritising 404 doesn't introduce any overhead, and should be preferred.

Or, consider changing the `MUST` into `MAY`?
> A server ~MUST~MAY ignore all received preconditions if its response to the same request without those conditions, prior to processing the request content, would have been a status code other than a 2xx (Successful) or 412 (Precondition Failed).

**Comment by liyishuai** [comment]
Crossed out my last comment: I missed the condition "prior to processing the request content". However, having noticed this condition, I'm getting more confused: Should the specification clarify what it is to "process the request content"? GET requests have no content, so when should the preconditions be evaluated?

**Comment by royfielding** [comment]
This is not something that needs to be defined. Preconditions are evaluated when there is some benefit gained by doing so. Hence, they are evaluated at the imprecise time at which their semantics can be meaningfully applied.

**Comment by liyishuai** [comment]
Yes the specification can be imprecise to allow more flexibility for server implementations.
My question becomes: Since a GET request may be responded with 404, does the server MUST skip its preconditions before determining whether the response is 404 or not? Or, does the server MUST NOT respond with 412 when the target is Not Found?

**Comment by royfielding** [comment]
Think it through the request. 404 means there is no selected representation. In order to test a precondition on the current metadata of a selected representation, you have to have a selected representation to test. So, which happens first? The 404 always happens first, after which there is no sensible metadata upon which to base the precondition.

**Comment by liyishuai** [comment]
Yes 404 is always determined first. However, if my server has a generic If-Match logic:
```coq
let if_match (request) : bool :=
  if get_target (request.path) is Some resource
  then strong_match(request.etag, resource.etag)
  else false in
let validate0 (request) :=
  if if_match (request)
  then process (request)
  else precondition_failed
```
Is it violating the specification, and I MUST change it into the following?
```coq
let validate1 (request) :=
  if request.method is GET
  then if get_target(request.path) is None
       then not_found
       else valdiate0 (request)
  else validate0 (request)
```

**Comment by awwright** [comment]
In my opinion, it's not possible to have "generic If-Match logic" because the behavior varies depending on the method call.

Conditional headers can be thought of as a combination of two different features, they can: ① condition a non-safe operation on the state of the resource being unchanged, and ② condition providing the response body on the resource having been changed.

Because these features do not overlap, we can use `If-Match` and `If-None-Match` to implement both of them without any ambiguity.

The fact that GET can return 412 seems like a compromise to define a single behavior that works for both features.

I think it would be worth splitting conditional requests into these two classes. Class ① is used for GET/HEAD (I don't know why you'd want to make a conditional HEAD request, but that's another issue); Class ② is used for non-safe operations.

**Comment by liyishuai** [comment]
Other than mentioned in https://github.com/httpwg/http-core/issues/800#issuecomment-800874285, the only method-specific logic I can find in the spec is for `If-None-Match` and `If-Modified-Since`:
https://github.com/httpwg/http-core/blob/df2fefd530357474ecc7b0ef2f5b324371cdc878/draft-ietf-httpbis-semantics-latest.xml#L7471-L7487
I read the precedence section as a generic logic for conditional requests, but the "MUST ignore precondition if known result" exception makes the spec unnecessarily stricter (_e.g._ upon 404, MUST NOT return 412 for GET).
I'd propose to loosen this constraint (when result is known, MAY consider or ignore precondition), or further tighten it (MUST NOT condition GET over `If-Match`).

**Comment by awwright** [comment]
The method-specific logic is implicitly specified:

> Except when excluded below, a recipient cache or origin server MUST evaluate received request preconditions after it has successfully performed its normal request checks and just before it would process the request content (if any) or perform **_the action associated with the request method_**

(emphasis mine)

The purpose of conditional requests are to make requests fail (or omit a response) when they would otherwise succeed and cause some undesirable behavior (like lost updates, or waste bandwidth). A 412 tells you that the state of the server _would have changed_ if it weren't for the conditional request.

If a server were to return 412 instead of 404, you would lose the knowledge that the requested resource does not exist; additionally, the 412 would be misleading, because if you had omitted the If-Match, the state of the server wouldn't have changed at all; the 412 is not preventing anything undesirable (like a lost update).

In your application, what is the _undesirable_ behavior you are looking to prevent (not merely inconsistent)?

**Comment by liyishuai** [comment]
I'm not an application developer. I'm writing a [formal specification of HTTP](https://github.com/liyishuai/coq-http) that can be verified and tested against. That's why I'm traversing every edge case and want to clarify them all.

**Comment by awwright** [comment]
I think this brings up a good point, that it doesn't make sense for 412 to be returned from a GET request. Does my point about that make sense?

**Comment by liyishuai** [comment]
Conditioning a GET request over `If-Match` is already nonsense, and worth disallowing.
The confusing 412 arises when a server implementation ignores the request method before evaluating the preconditions. Such ignorance might seem counterintuitive in imperative languages like C, but is more straightforward to implement in functional languages (like the `validate0` shown in https://github.com/httpwg/http-core/issues/800#issuecomment-801349418).

**Comment by reschke** [comment]
I think there are just a few details that merit attention...:

https://github.com/httpwg/http-core/blob/97bb9281cf3023547994894e22d0632c82e1a3df/draft-ietf-httpbis-semantics-latest.xml#L7393-L7396

Here we could replace "prior to processing the request content" by "prior to processing the request content (if any)".

Furthermore:

https://github.com/httpwg/http-core/blob/97bb9281cf3023547994894e22d0632c82e1a3df/draft-ietf-httpbis-semantics-latest.xml#L7452-L7461

Here maybe replace "unless it can be determined that the state-changing request has already succeeded" by "unless no state change was requested or it can be determined that the state-changing request has already succeeded".

**Comment by liyishuai** [comment]
Yes these changes make the specification clearer.

The condition "unless it can be determined that the state-changing request has already succeeded" corresponds to Section `field.if-match`:
https://github.com/httpwg/http-core/blob/97bb9281cf3023547994894e22d0632c82e1a3df/draft-ietf-httpbis-semantics-latest.xml#L6982-L6991
If we are to add "no state change was requested", maybe worth updating Section `field.if-match` accordingly.

**Comment by awwright** [comment]
By

> the state-changing request has already succeeded

Is this referring to a repeated idempotent operation, or other operation that doesn't affect the state of the server?

**Comment by reschke** [comment]
> Is this referring to a repeated idempotent operation, or other operation that doesn't affect the state of the server?

Then it wouldn't be called state-changing...

**Comment by royfielding** [comment]
No, I've gone over this a third time and the specification is still correct as written.

Whether or not If-Match on GET makes sense, the intention is clear that the client wants a normal error first (404 if applicable), then the condition applied (412 if false), then the 2xx response only if the precondition was true. The only reason for sending the precondition on GET is to prevent the response from being 200 if the precondition is false, which might be useful if the content is very very large.

**Comment by awwright** [comment]
@reschke

> Then it wouldn't be called state-changing...

More specifically, I'm wondering about requests that are _potentially_ state changing (a non-safe method), but ends up not changing the state. The current wording is not immediately clear to me.

@royfielding So to clarify, GET supports 412 in the event that a user-agent wants to download a document, and is only interested in a specific version?
