### ISSUE TITLE
confusing paragraph in Idempotent methods

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#819]
I have no idea what this is trying to say and it is 1.1-specific. I suggest we delete it.

>    Some clients use weaker signals to initiate automatic retries. For example, when a POST request is sent, but the underlying transport connection is closed before any part of the response is received. Although this is commonly implemented, it is not recommended.

**Comment by reschke** [comment]
Added as part of https://github.com/httpwg/http-core/pull/222

**Comment by royfielding** [comment]
How about

> Some clients take a riskier approach and attempt to guess when an automatic retry is possible. For example, automatically retrying a POST request if the underlying transport connection closed before any part of a response is received. This is often the case when a request is sent over an apparently idle persistent connection which has already timed-out on the server.

**Comment by wenbozhu** [comment]
> if the underlying transport connection closed before any part of a response is received ...

May end up encouraging this kind of implementation, by providing an example here ... ?

Maybe just leave this as "Some clients take a riskier approach and attempt to guess when an automatic retry is possible because the original request may not have been received by the server." ....

**Comment by mnot** [comment]
I don't see any problem with the original text, but @royfielding your replacement is fine too (although the second sentence is a fragment).

**Comment by royfielding** [comment]
How about

> Some clients take a riskier approach and attempt to guess when an automatic retry is possible. For example, a client might automatically retry a POST request if the underlying transport connection closed before any part of a response is received, particularly if an idle persistent connection was used.
