### ISSUE TITLE
Mention that 204 responses should not include content-headers 

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#823]
> [15.3.5. 204 No Content](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.204)
Metadata in the response header fields refer to the target resource and its selected representation after the requested action was applied.

Should the spec also mention that "content headers" such as C-T should not be included?

**Comment by MikeBishop** [comment]
Why wouldn't they?  They describe the selected representation of the target resource.  Things that are about the message payload shouldn't be present, like T-E, but C-E is a property of the resource.

**Comment by reschke** [comment]
"Metadata in the response header fields refer to the target resource and its selected representation after the requested action was applied."

I think that's pretty clear for Content-Type. When you say "some applications don't expect to see..." - what does this mean? How do they fail?

**Comment by wenbozhu** [comment]
> - what does this mean? How do they fail?
I haven't asked, e.g. with different frameworks out there.

Maybe add "Entity-level metadata such as C-T should be included in the response header fields".   Not sure about C-L, as you suggested.

**Comment by royfielding** [comment]
The spec doesn't say that because it doesn't need to say that -- the server will include whatever metadata it thinks the client might need, and the client will interpret that as metadata about the resource.
