### ISSUE TITLE
Unused references in semantics?

### ISSUE THREAD

**Issue by tfpauly** [httpwg/http-core#830]
== Unused Reference: 'RFC2145' is defined on line 9325, but no explicit
     reference was found in the text

  == Unused Reference: 'RFC7617' is defined on line 9470, but no explicit
     reference was found in the text

**Comment by reschke** [comment]
RFC 7617 is mentioned in Section 11.1, so this is idnits misreporting.
RFC 2145 is mentioned in the Acks, so we may want to check why it's not mentioned elsewhere.

**Comment by reschke** [comment]
I believe we can close this with no action.
