### ISSUE TITLE
anchor names for sibling specs

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#846]
We currently have [Semantics], [Caching] etc.

Should we...:

1. Stick with those?
2. Use RFCnnnn notation (consistent with what we did in the past)?
3. Something else?

Also: if we stick with this style, should we rename "Messaging" to "HTTP11"?

**Comment by MikeBishop** [comment]
I find the names to be more helpful than RFC numbers, personally.  You can look up either piece of info to find the other, but the name is more useful to recognize what document is being referred to without opening it.

**Comment by mnot** [comment]
+1 to names -- anything we can do to reinforce the idea that the RFC numbers don't matter.

**Comment by mnot** [comment]
HTTP11 seems appropriate.

**Comment by reschke** [comment]
> +1 to names -- anything we can do to reinforce the idea that the RFC numbers don't matter.

They do matter a lot when looking up an RFC for which you don't have an hyperlink.

**Comment by mnot** [comment]
sure... but the number is in the reference text.

**Comment by reschke** [comment]
True. But using something like "ABNF [RFC5234]" helps memorizing those. Just IMHO.

**Comment by mnot** [comment]
Memorising those is what we *don't* want to encourage - it associates a number with a specification whose number may change.

**Comment by royfielding** [comment]
waiting for the last PRs to be merged and then someone can global-replace this hunk of joy and we are done.

**Comment by mnot** [comment]
OK, here we are...

**Comment by reschke** [comment]
AFAIU: we replace "Messaging" by "HTTP/1.1", and that's it. Or do you want to go further?

**Comment by royfielding** [comment]
I think a little further. It is easiest to use the same reference names as https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34

```
   [CACHING]  instead of [Caching]
   [SEMANTICS] instead of [Semantics]
   [HTTP11]     instead of [Messaging]
   [HTTP10]  RFC 1945
   [HTTP2]    RFC 7540
   [HTTP3]    draft-ietf-quic-http-34

   [URI]          RFC 3986
   [ALTSVC]   RFC 7838
   [HPACK]    RFC 7541
   [TLS13]      RFC 8446

we already have

   [BREACH]   Gluck, Y., Harris, N., and A. Prado

maybe also

   [COOKIE] instead of [RFC6265]
   [TCP] instead of [RFC0793]
   [WebDAV] instead of [RFC4918]
```

**Comment by MikeBishop** [comment]
Hopefully obvious, since it's pulling from what I edited, but I enthusiastically support Roy's list.

**Comment by royfielding** [comment]
I am thinking of changing [SEMANTICS] to [HTTP] to close that out (and it sorts the references properly). WDYT?

**Comment by royfielding** [comment]
Yep, that's better. All done. Time to reboot my computer and stop looking at the spec.

**Comment by royfielding** [comment]
Okay. I worry about what will happen with other tools (like markdown) where there might be no way to distinguish between the anchor HTTP11 and the presentation "HTTP/1.1". I don't want to see a slash in the fragments. It is handled properly by your tools, so let's hope it can be done consistently by the RFC editor.
