### ISSUE TITLE
Remove the word "Registry" from IANA registry names

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#848]
as per [IANA #1198294]:

> NOTE: In its review of draft-ietf-httpbis-semantics, IANA will ask that the word "Registry" be left out of the name of the new registry.

**Comment by reschke** [comment]
But then, other registries *do* contain the term inside the registry name.

**Comment by mnot** [comment]
Personally, I'm not thrilled with this -- having the word 'registry' in it makes it clear that it's the authoritative source (as opposed to, e.g., Wikipedia).

**Comment by reschke** [comment]
I believe we have concluded that no change is needed.
