### ISSUE TITLE
Francesca Palombini Editorials and clarifications (AD review of draft-ietf-httpbis-semantics-16)

### ISSUE THREAD

**Issue by fpalombini** [httpwg/http-core#849]
Hi! I post here my combined comments for draft-ietf-httpbis-semantics-16, as I don't think they deserve one issue each :) I hope that's fine.

My comments range from minor to very minor to nit, and are mostly editorials and clarifications. As this can possibly be me, I'll leave it up to you to decide if they can be useful to improve readability, or not.

Thanks for your work!
Francesca

- [x] 1. -----

   Additional (social) requirements are placed on implementations,

FP: I am not sure I understand the meaning behind the term "social requirement".

Editors: https://github.com/httpwg/http-core/commit/366006c3dbb0aa47aaf0e545c704e8896d1a12fa (https://github.com/httpwg/http-core/issues/854#issuecomment-877502247)

- [x] 2. -----

   When a major version of HTTP does not define any minor versions, the
   minor version "0" is implied and is used when referring to that
   protocol within a protocol element that requires sending a minor
   version.

FP: I had a hard time parsing this sentence (starting at "and is used..."), maybe breaking it up with commas would be enough. Especially the two "that" are unclear to me.

Editors: https://github.com/httpwg/http-core/commit/43700886dbd89e86d67619bb366ba97252a49dfb (https://github.com/httpwg/http-core/issues/849#issuecomment-857655632)

- [x] 3. -----

   RFC 3986, which allows for an empty path to be used in references,

FP: very minor, I'd prefer "in URI references".

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857803227, change applied in https://github.com/httpwg/http-core/commit/8c9453883a25ca072e61c4162417c15f2a939c66

- [x] 4. -----

   The process for determining that access is defined by the URI scheme
   and often uses data within the URI components, such as the authority
   component when the generic syntax is used.  However, authoritative

FP: I had to read the sentence above 3 times before realizing that the subject of "is defined" is not "access", but "The process", and understanding it. 

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-861430334, change applied in https://github.com/httpwg/http-core/commit/4818ea0dd1ea3f7449e5251f405b93ed6824f857

- [x] 5. -----

   A client MAY discard or truncate received field lines that are larger

FP: I assume and It might have been good to clarify that "truncate" a field lines is equivalent to dropping a member of the list of values.

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857692414

- [x] 6. -----

   Note that double-quote delimiters are almost always used with the
   quoted-string production; using a different syntax inside double-

FP: I am not sure I understand "quoted-string production"

Editors: added missing fwd reference - https://github.com/httpwg/http-core/commit/45db9383d93ccb9505dd437e94e0fa2a88c48607

- [x] 7. -----

   content, it is often desirable for the sender to supply, or the
   recipient to determine, an identifier for a resource corresponding to
   that representation.

FP: It might have been good here to give a hint or example on why such identifiers could be desirable.

Editors: https://github.com/httpwg/http-core/commit/2f7b5941a9ae35f9018354449d93afc99e43fee4 (https://github.com/httpwg/http-core/issues/849#issuecomment-857694461)

- [x] 8. -----

   Fields (Section 5) that are located within a _trailer section_ are
   are referred to as "trailer fields" (or just "trailers",

FP: s/are are/are

Editors: https://github.com/httpwg/http-core/commit/b2118846c98a026f522eb44f8e9db27b6368e0ea

- [x] 9. -----

   All responses, regardless of the status code (including interim
   responses) can be sent at any time after a request is received, even
   if the request is not yet complete.  A response can complete before

FP: I think at this point in the text there is no definition of what qualifies a request or response being "complete".

Editors: actually, the definition is earlier in the text; added a reference anyway: https://github.com/httpwg/http-core/pull/850/commits/3e80597e99bcee62ca2be14b963ea980ab3fe4c6

- [x] 10. -----

   An intermediary MAY combine an ordered subsequence of Via header
   field list members into a single member if the entries have identical
   received-protocol values.  For example,

FP: Is there any requirement on the intermediary to be able to collapse the ordered sequence into a single member (such as storing and being able to expand this information)? Might want to expand a little.

Editors: Declined because there is no requirement to do so. We already explain that one might want to do so for information hiding of intermediaries within a private network (https://github.com/httpwg/http-core/issues/849#issuecomment-857700209 and https://github.com/httpwg/http-core/issues/849#issuecomment-857714514)

- [x] 11. -----

   This definition of safe methods does not prevent an implementation
   from including behavior that is potentially harmful, that is not
   entirely read-only, or that causes side effects while invoking a safe
   method.  What is important, however, is that the client did not
   request that additional behavior and cannot be held accountable for
   it.  For example, most servers append request information to access
 
FP: I might be missing the motivation for it, but this paragraph seems strange to me. Why is it important that the client cannot be held accountable for it? The concern I have is that the text seems to be saying "safe is essentially read only/not harmful/..., but not really". (And same for idempotent)

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857708360

- [x] 12. -----

   referring to making a GET request.  A successful response reflects
   the quality of "sameness" identified by the target URI.  In turn,

FP: I am confused by this terminology: quality of "sameness".

Editors: https://github.com/httpwg/http-core/issues/863

- [x] #904

   > A client SHOULD NOT generate content in a GET request.  Content

   FP: The text could add something for when it is acceptable or expected to make sense (so why this is a SHOULD).

Editors: Because the protocol has historically preferred to separate semantics from parsing requirements so that the semantics can be extended over time without breaking parsers. It is a SHOULD NOT for GET because the original protocol did not define a meaning for such message content and some implementations took advantage of that leniency to implement and deploy features that work among consenting implementations but are non-interoperable with intermediaries and other implementations. Hence, it's a bad idea, but the protocol does not prevent it from happening. See #904 for why this is impossible to change.

- [x] 14. -----

   A server SHOULD NOT use the From header field for access control or
   authentication.

FP: Same as the previous comment, when is it acceptable to use the From header field for access control or authentication?

Editors: https://github.com/httpwg/http-core/commit/bde626d7cdfd2a6221e1d2f4ec6c87f40dd8c7be
[If it is acceptable to the server that does it, then HTTP doesn't care in terms of interop, but it is still a bad idea because the protocol has other mechanisms for doing access control and authentication which are less likely to be leaked by accident (https://github.com/httpwg/http-core/issues/849#issuecomment-877810122)]

- [x] 15. -----

FP: I don't know if I missed it, and please correct me if I did, but I was hoping to find a sentence stating something of the sort for the header fields: "If not otherwise stated, these fields can be used with any method or response code".

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-874405810

- [x] 16. -----

FP: Most of the header fields contain examples, which I find helpful. I think it would be good to have examples for all of them (including TE, Trailer).

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857747416

- [x] 17. -----

      |  Accept.  Future media types are discouraged from registering
      |  any parameter named "q".

FP: I wonder if it would be worth making a not out of it in the media type registry (so that it's easily remembered by experts)

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857594639

- [x] 18. -----

   Note that an If-None-Match header field with a list value containing
   "\*" and other values (including other instances of "\*") is unlikely
   to be interoperable.

FP: what does it mean for a header field specific value to be not-interoperable? I am also not sure how "\*" between the list of values would be processed. 2. above does not specify it, only stating:

   2.  If the field value is a list of entity-tags, the condition is
       false if one of the listed tags matches the entity-tag of the
       selected representation.

FP: I would possibly interpret this as "search for tags matching the entity tag - ignore all others".

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857733592
 and https://github.com/httpwg/http-core/commit/40ad074b7037141d29775c15d01e279279b67a5e
- [x] 19. -----

   senders might send erroneously send multiple values, and both

FP: remove one "send".

Editors: https://github.com/httpwg/http-core/pull/850/commits/f07d6d426a4cbad599ee12fa4a18e61d664e3e2b

- [x] 20. -----

   the String data type of [RFC8941]), or a field-specific encoding).

FP: remove the first parenthesis.

Editors: https://github.com/httpwg/http-core/pull/850/commits/fb297d0c78ece0825b069bafef428ecb3055c363

- [x] 21. -----

FP: This is more of a check, but I see that all references only point to sections. I hope this will be translated into "x.x.x of RFCthis", is that correct?

Editors: https://github.com/httpwg/http-core/issues/849#issuecomment-857587648

**Comment by reschke** [comment]
> 21. This is more of a check, but I see that all references only point to sections. I hope this will be translated into "x.x.x of RFCthis", is that correct?

You mean in the tables for IANA registrations? That's for brevity; IANA knows how to deal with that.

**Comment by reschke** [comment]
> 17. FP: I wonder if it would be worth making a not out of it in the media type registry (so that it's easily remembered by experts)

The media type registry is not owned by "us". I don't think we have the authority to change it.

**Comment by fpalombini** [comment]
> > 1. FP: I wonder if it would be worth making a not out of it in the media type registry (so that it's easily remembered by experts)
> 
> The media type registry is not owned by "us". I don't think we have the authority to change it.

I will look into this with IANA and the DEs and get back.

Just to be clear, the document states "future media types are discouraged..." but what we really mean is "experts should be conservative with assigning ..." , is that accurate? Yes, in theory we'd like to discourage media types to be registering "q", but the practical way to make sure that doesn't happen is to make the DEs react to it if it does.

**Comment by reschke** [comment]
> 2. FP: I had a hard time parsing this sentence (starting at "and is used..."), maybe breaking it up with commas would be enough. Especially the two "that" are unclear to me.

maybe "...whenreferring to that protocol version..."?

**Comment by fpalombini** [comment]
> > 1. FP: I had a hard time parsing this sentence (starting at "and is used..."), maybe breaking it up with commas would be enough. Especially the two "that" are unclear to me.
> 
> maybe "...whenreferring to that protocol version..."?

Yes, thanks!

**Comment by reschke** [comment]
> 5. FP: I assume and It might have been good to clarify that "truncate" a field lines is equivalent to dropping a member of the list of values.

I don't think it's restricted to that.

**Comment by reschke** [comment]
> 7. FP: It might have been good here to give a hint or example on why such identifiers could be desirable.

For instance, to provide a bookmark/make something accessable for a subsequent GET...

**Comment by reschke** [comment]
> 10. FP: Is there any requirement on the intermediary to be able to collapse the ordered sequence into a single member (such as storing and being able to expand this information)? Might want to expand a little.

I don't get that question. The spec *allows* collapsing. It doesn't require it. Could you please clarify your question?

**Comment by reschke** [comment]
> 11. FP: I might be missing the motivation for it, but this paragraph seems strange to me. Why is it important that the client cannot be held accountable for it? The concern I have is that the text seems to be saying "safe is essentially read only/not harmful/..., but not really". (And same for idempotent)

The motivation is that if something is defined as "safe", I can ...safely... do that operation without being held accountable. For instance, I can always GET a URI (such as for prefetch/preload/indexing) and if the server *does* do something stupid with that request (such as deleting a resource, or adding something to a shopping basked), it's *their* problem.

Re idempotenty: this makes it possible to repeat a request.

**Comment by fpalombini** [comment]
> > 1. FP: Is there any requirement on the intermediary to be able to collapse the ordered sequence into a single member (such as storing and being able to expand this information)? Might want to expand a little.
> 
> I don't get that question. The spec _allows_ collapsing. It doesn't require it. Could you please clarify your question?

The text states that intermediaries are allowed to collapse "an ordered subsequence of Via header field list members into a single member", and they can only do so "if the entries have identical received-protocol values." So I read 2 rules:
1. the order matter, i.e. if (A,B) collapses to C, (B,A) does not map to C
2. (A,B) must have identical recived-protocol values
 
I was wondering about any additional rules that the intermediaries have to follow in order to collapse the list into one: for example, is it ever expected for the intermediary to remember that this single member was this collapsed ordered sequence? Are they ever requested to un-collapse?

**Comment by reschke** [comment]
> 
> 
> > > 1. FP: Is there any requirement on the intermediary to be able to collapse the ordered sequence into a single member (such as storing and being able to expand this information)? Might want to expand a little.
> > 
> > 
> > I don't get that question. The spec _allows_ collapsing. It doesn't require it. Could you please clarify your question?
> 
> The text states that intermediaries are allowed to collapse "an ordered subsequence of Via header field list members into a single member", and they can only do so "if the entries have identical received-protocol values." So I read 2 rules:
> 
>     1. the order matter, i.e. if (A,B) collapses to C, (B,A) does not map to C

Order matters for the purpose of collapsing. If you have "D, E, F", and E has a different protcol than D or F, you can't collapse.

If "A, B" can be collapsed, so can "B, A" (because they have the same protocol)

>     2. (A,B) must have identical recived-protocol values
> 
> 
> I was wondering about any additional rules that the intermediaries have to follow in order to collapse the list into one: for example, is it ever expected for the intermediary to remember that this single member was this collapsed ordered sequence? Are they ever requested to un-collapse?

We are not saying that, so there is no expectation that the collapsing can be undone.

**Comment by fpalombini** [comment]
> > 1. FP: I might be missing the motivation for it, but this paragraph seems strange to me. Why is it important that the client cannot be held accountable for it? The concern I have is that the text seems to be saying "safe is essentially read only/not harmful/..., but not really". (And same for idempotent)
> 
> The motivation is that if something is defined as "safe", I can ...safely... do that operation without being held accountable. For instance, I can always GET a URI (such as for prefetch/preload/indexing) and if the server _does_ do something stupid with that request (such as deleting a resource, or adding something to a shopping basked), it's _their_ problem.
> 
> Re idempotenty: this makes it possible to repeat a request.

Ok, so yes I understand - the idea of this text is to say: "this is the intent, BUT be aware that implementations might do something stupid and not comply with this intent." I guess what I got stuck with was "the client can't be held accountable", as it wasn't clear to me what would it mean for a client to be held accountable of an operation, as clients in general are not aware of what's the action on the server their request will result in.

**Comment by reschke** [comment]
> 18. FP: what does it mean for a header field specific value to be not-interoperable? I am also not sure how "*" between the list of values would be processed. 2. above does not specify it, only stating:

This might require a separate issue.

A field value containing more than one list element *and* including "\*" is invalid, and the spec really doesn't say what that means. The intent of saying "interoperable" is (IMHO) to prevent people from assuming the different servers will do the same thing with it.

I believe we should clarify that a value like that is invalid, and thust MUST NOT be sent. @royfielding , @mnot ?

**Comment by reschke** [comment]
> 12. FP: I am confused by this terminology: quality of "sameness".

That refers to https://greenbytes.de/tech/webdav/rfc3986.html#rfc.section.1.2.2.p.4 - I guess we should cite that?

**Comment by reschke** [comment]
> 16. FP: Most of the header fields contain examples, which I find helpful. I think it would be good to have examples for all of them (including TE, Trailer).

On the other hand, people complain about the spec being too long already. I don't think we should add examples unless they are needed to make things easier to understand.

**Comment by fpalombini** [comment]
> > 1. FP: Most of the header fields contain examples, which I find helpful. I think it would be good to have examples for all of them (including TE, Trailer).
> 
> On the other hand, people complain about the spec being too long already. I don't think we should add examples unless they are needed to make things easier to understand.

Ok! (As I said, these are so minor that they are definitely up to you. Same with references and terminology comments)

**Comment by reschke** [comment]
> 3. FP: very minor, I'd prefer "in URI references".

I believe the simplest possible fix would be to remove "to be used in references", making this: 

> (This rule differs slightly from the path-abempty rule of RFC 3986, which allows for an empty path, and path-absolute rule, which does not allow paths that begin with "//".)

@royfielding ?

**Comment by mnot** [comment]
> 13. A client SHOULD NOT generate content in a GET request. Content
> 
> FP: The text could add something for when it is acceptable or expected to make sense (so why this is a SHOULD).

I think that we should probably convert this one (and similar) to MUST NOT -- there isn't any situation where we recommend this behaviour, as it has interoperability and security implications.

**Comment by reschke** [comment]
> I think that we should probably convert this one (and similar) to MUST NOT -- there isn't any situation where we recommend this behaviour, as it has interoperability and security implications.

Not convinced at all. The "SHOULD NOT" requirement is new and was controversial already. There is code out there using GET with body (in controlled environments) which just works.

**Comment by mnot** [comment]
> There is code out there using GET with body (in controlled environments) which just works.

That's not HTTP; that's a private protocol.

**Comment by reschke** [comment]
> That's not HTTP; that's a private protocol.

Tell that Google :-)

**Comment by reschke** [comment]
> 4.  The process for determining that access is defined by the URI scheme and often uses data within the URI components, such as the authority  component when the generic syntax is used. However, authoritative
>
> FP: I had to read the sentence above 3 times before realizing that the subject of "is defined" is not "access", but "The process", and understanding it.

Maybe "The process for determining whether access is granted is defined..."?

**Comment by mnot** [comment]
> FP: I don't know if I missed it, and please correct me if I did, but I was hoping to find a sentence stating something of the sort for the header fields: "If not otherwise stated, these fields can be used with any method or response code"

You mean generally, for the fields we define? I don't think that's true; they're defined for the semantics they specify. If a use isn't specified, it might be extended in the future, so we rarely prohibit such a use. Saying that they can be used with any method or status code would imply that they have meaning in each circumstance, and that's often not true.

**Comment by mnot** [comment]
> A server SHOULD NOT use the From header field for access control or
authentication.

This isn't important for interoperability, it's just a bad idea. Maybe 'The From header field is not intended or suitable for use as a means of access control or authentication.'?

**Comment by reschke** [comment]
> > A server SHOULD NOT use the From header field for access control or
> > authentication.
> 
> This isn't important for interoperability, it's just a bad idea. Maybe 'The From header field is not intended or suitable for use as a means of access control or authentication.'?

FWIW, the requirement is from RFC 7231, and widely accepted (I guess), so I don't think we should change it.

**Comment by mnot** [comment]
For 4, proposed rewrite:

> Access to a resource is said to be authoritative when the client has reason to believe that it has been performed in a way that proves control by the resource owner. The process for determining that access has been authoritative is defined by the URI scheme, and often uses data within the URI such as the authority component. However, a client's concept of authoritative access is not limited to the URI scheme's identified mechanism.

**Comment by mnot** [comment]
WRT `From` -- I don't think I'd use the word "widely" in conjunction with this header field. Again, if we use SHOULD NOT, we should explain the qualification.

**Comment by mnot** [comment]
> I believe we should clarify that a value like that is invalid, and thus MUST NOT be sent.

In the sense that it's an interoperability requirement on a sender (_not_ a recipient), I agree.

**Comment by reschke** [comment]
> > I believe we should clarify that a value like that is invalid, and thus MUST NOT be sent.
> 
> In the sense that it's an interoperability requirement on a sender (_not_ a recipient), I agree.

"MUST NOT be generated" maybe?

**Comment by mnot** [comment]
MUST NOT be generated, because recipient behaviour is not interoperable.

**Comment by reschke** [comment]
> MUST NOT be generated, because recipient behaviour is not interoperable.

...we already say "MUST NOT generate ABNF-invalid messages" in general. But then, the ABNF does not preclude this. I believe "MUST NOT" still would be correct, but would we have list that as a normative change?

**Comment by mnot** [comment]
I've reviewed the most recent commits, think this can be closed now.

**Comment by fpalombini** [comment]
Thanks for addressing my comments. 

I checked the commits and your answers: I can see everything was addressed, either by changes or by answers clarifying what I found confusing, except for:

* the one which is now issue #904 
* point 14: giving context around the "SHOULD NOT" for the 'From' header field. Note that I am not asking you to make any change (such as removing the BCP 14 text), but following what BCP 14 defines:

>   4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED", means that
>    there may exist valid reasons in particular circumstances when the
>    particular behavior is acceptable or even useful, but the full
>    implications should be understood and the case carefully weighed
>    before implementing any behavior described with this label.

it seems important that the reader understands, or at least gets a hint of what these reasons and particular circumstances are, in order to be able to understand the full implications. This is why I think it's important to clarify the context around the SHOULD / SHOULD NOT, and was also my comment for the GET requirement, but I see that that comment has now transformed in a bigger issue the wg needs to find consensus on.

**Comment by royfielding** [comment]
> it seems important that the reader understands, or at least gets a hint of what these reasons and particular circumstances are, in order to be able to understand the full implications. This is why I think it's important to clarify the context around the SHOULD / SHOULD NOT, and was also my comment for the GET requirement, but I see that that comment has now transformed in a bigger issue the wg needs to find consensus on.

I disagree. You are presuming that we know those particular circumstances, and that is almost always false when SHOULD is being used. When we have a detailed list of conditions, we use "MUST NOT unless ...". The SHOULD is literally saying that the reader needs to take care and understand the risk/benefit for their own context, not that we need to explain to them based on our own imagination.

It is fine to suggest additional text to address a specific concern, but I personally think that this one is self-explanatory. If we added a general description about why auth parameters shouldn't be sent in fields that are not expected to be treated as auth parameters by every recipient, such as within a security consideration, then we could reference it here.

**Comment by fpalombini** [comment]
> You are presuming that we know those particular circumstances, and that is almost always false when SHOULD is being used. 

I don't think we should know all possible circumstances, but I presume we do have an inkling that implementations going against the RECOMMENDations exist, for whatever reason, right? As a reader, putting myself in a new implementer shoes, I personally would have found it useful to get that hint of what to consider, but if you think that this one is self-explanatory, I won't insist.

The type of sentence I was thinking about would be something like:

> Implementations using this field for access control or authentication need to evaluate and understand the risk of leaking information, and consider using the protocol's built in mechanism instead (see Section 11).

(Just trying to explain myself here, again, feel free not to take this suggestion if you and the wg don't think it helps the reader)

**Comment by royfielding** [comment]
Okay, I have added https://github.com/httpwg/http-core/commit/bde626d7cdfd2a6221e1d2f4ec6c87f40dd8c7be because I think we should explain it if it isn't obvious to others.

**Comment by fpalombini** [comment]
Thank you @royfielding !
