### ISSUE TITLE
Martin Duke COMMENT on draft-ietf-httpbis-semantics-16

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#857]
- [x] (7.6.3) Via

"If a port is not provided, a recipient MAY interpret that as meaning it was
received on the default TCP port, if any, for the received-protocol."

So if received-protocol is "3", it's a UDP port.

If received-protocol is "1" or "1.1", is the default port 80 or 443? IIUC the
scheme isn't included to determine this.

Editors: https://github.com/httpwg/http-core/pull/881

---

- [x] (7.7) Message Transformations

"A proxy that transforms the content of a 200 (OK) response can inform
downstream recipients that a transformation has been applied by changing the
response status code to 203 (Non-Authoritative Information)"

Why not an normative word, instead of "can"?

Editors: https://github.com/httpwg/http-core/issues/857#issuecomment-872025414

---

- [x] (12.5.3) Is it correct that "identity" and having no field value for
Accept-Encoding are synonymous?

Editors: https://github.com/httpwg/http-core/issues/857#issuecomment-872759458

---

- [x] "Servers that fail a request due to an unsupported content coding ought to
respond with a 415 (Unsupported Media Type) status"

Why not s/ought to/SHOULD ?

Editors: https://github.com/httpwg/http-core/issues/857#issuecomment-872939272

---

- [x] (14.3) Why can only origin servers send "Accept-Ranges: bytes"? Why not
intermediaries?

Editors: https://github.com/httpwg/http-core/pull/882

---

- [x] (15.3.7) "A sender that generates a 206 response with an If-Range header
field"... (13.1.5) leads me to believe that only clients can send If-Range. So
how can there be a response with If-Range?

Editors: https://github.com/httpwg/http-core/pull/883

---

- [x] (15.3.7.2) The last instance of THIS_STRING_SEPARATES has a trailing '--'. If
this is intentional, it ought to be explained.

Editors: https://github.com/httpwg/http-core/issues/857#issuecomment-872032533

---

- [x] (16.3.1) says field names SHOULD begin with a letter, but (16.3.2.1) says they
SHOULD begin with "an alphanumeric character". More broadly, the "Field name:"
description in (16.3.1) should probably refer to (16.3.2.1) unless I'm
misunderstanding the scope of these sections.

Editors: https://github.com/httpwg/http-core/pull/890

---

- [x] (17.13) s/TCP behavior/TCP or QUIC behavior

Editors: https://github.com/httpwg/http-core/pull/884

---

- [x] (B) It would be good to mention here that accept-ext has been removed in
(12.5.1), and accept-charset is deprecated in (12.5.2), if that is new to this
spec.

Editors: see https://github.com/httpwg/http-core/issues/886 and https://github.com/httpwg/http-core/issues/885

**Comment by mnot** [comment]
> (14.3) Why can only origin servers send "Accept-Ranges: bytes"? Why not intermediaries?

Because the header is information about the capabilities of the origin server, not other members of the request chain. Intermediaries can change (e.g., with proxy configuration). Note that a gateway (e.g., a CDN) is effectively acting as an origin server, so it can do this.

The language in this section needs to be tweaked, however; there are a few instances of 'server' that should be 'origin server'.

**Comment by mnot** [comment]
> (15.3.7) "A sender that generates a 206 response with an If-Range header
field"... (13.1.5) leads me to believe that only clients can send If-Range. So
how can there be a response with If-Range?

It looks like the phrase 'to a request' was dropped somewhere between [7233](https://httpwg.org/specs/rfc7233.html#status.206) and now.

**Comment by mnot** [comment]
> (15.3.7.2) The last instance of THIS_STRING_SEPARATES has a trailing '--'. If
this is intentional, it ought to be explained.

This is how multipart works; see [RFC2046](https://datatracker.ietf.org/doc/html/rfc2046#section-5.1.1). I don't think there's value in re-specifying it here.

**Comment by mnot** [comment]
>  Is it correct that "identity" and having no field value for Accept-Encoding are synonymous?

As per the spec:

> An "identity" token is used as a synonym for "no encoding" in order to communicate when no encoding is preferred.

...

> An Accept-Encoding header field with a field value that is empty implies that the user agent does not want any content coding in response.

**Comment by reschke** [comment]
> > "Servers that fail a request due to an unsupported content coding ought to respond with a 415 (Unsupported Media Type) status"
>
> Why not s/ought to/SHOULD ?

Because we avoid making existing servers that predate this spec non-compliant (unless there's a very good reason, such as security)
