### ISSUE TITLE
Lars Eggert COMMENT draft-ietf-httpbis-cache-16

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#858]
Lars Eggert has entered the following ballot position for
draft-ietf-httpbis-cache-16: No Objection

When responding, please keep the subject line intact and reply to all
email addresses included in the To and CC lines. (Feel free to cut this
introductory paragraph, however.)

Please refer to https://www.ietf.org/iesg/statement/discuss-criteria.html
for more information about DISCUSS and COMMENT positions.

The document, along with other ballot positions, can be found here:
https://datatracker.ietf.org/doc/draft-ietf-httpbis-cache/

COMMENT:

- [ ] Section 3. , paragraph 2, comment:
>    A cache MUST NOT store a response to a request unless:

Unless all of these are true or any of these are true? I guess the former.

All comments below are about very minor potential issues that you may choose to
address in some way - or ignore - as you see fit. Some were flagged by
automated tools (via https://github.com/larseggert/ietf-reviewtool), so there
will likely be some false positives. There is no need to let me know what you
did with these suggestions.

- [x] Section 2. , paragraph 2, nit:
>    Proper cache operation preserves the semantics of HTTP transfers
>    ([Semantics]) while reducing the transmission of information already

It's unusual to put a reference (also) in parentheses; suggest removing the
parentheses here and checking similar occurrences throughout the document.

- [x] Section 1. , paragraph 5, nit:
~~~
-    HTTP caching's goal is significantly improving performance by reusing
-                -------
+    The goal of HTTP caching is significantly improving performance by reusing
+   ++++++++++++
~~~

- [x] Section 1.3. , paragraph 5, nit:
>  uses to select a response and is comprised of, at a minimum, the request met
>                                ^^^^^^^^^^^^^^^
Did you mean "comprises" or "consists of" or "is composed of"?

- [x] Section 9.1. , paragraph 3, nit:
> ferring to RFC 723x. * Remove acknowledgements specific to RFC 723x. * Move
>                               ^^^^^^^^^^^^^^^^
Do not mix variants of the same word ("acknowledgement" and "acknowledgment")
within a single text.

Editors: see https://github.com/httpwg/http-core/issues/852

- [x] Section 9.1. , paragraph 3, nit:
> pecific to RFC 723x. * Move "Acknowledgements" to the very end and make them
>                              ^^^^^^^^^^^^^^^^
Do not mix variants of the same word ("acknowledgement" and "acknowledgment")
within a single text.

Editors: see https://github.com/httpwg/http-core/issues/852

- [x] These URLs point to tools.ietf.org, which is being deprecated:
 * https://tools.ietf.org/html/draft-ietf-httpbis-messaging-16
 * https://tools.ietf.org/html/draft-ietf-httpbis-semantics-16
 
Editors: see https://github.com/httpwg/http-core/issues/852

**Comment by mnot** [comment]
> Unless all of these are true or any of these are true? I guess the former.

Previously, we explicitly said `and` at the end of each clause, but that got lost somewhere along the way.

I'm inclined to add them again; @reschke @royfielding, any objection?

**Comment by reschke** [comment]
I think the answer is "any of these", and that's what the current text IMHO implies.

**Comment by mnot** [comment]
It is definitely **not** 'any of these.'

**Comment by reschke** [comment]
> When doing so, the cache MUST add each header field in the provided response to the stored response, replacing field values that are already present, with the following exceptions:
>
 >   Header fields excepted from storage in Section 3.1,
 >   Header fields that the cache's stored response depends upon, as described below,
 >   Header fields that are automatically processed and removed by the recipient, as described below, and
 >   The Content-Length header field.

**Comment by mnot** [comment]
The problem is that 'all of the conditions below' is ambiguous, if we're holding things to such a high standard of precision; some of the bullet items contain multiple options, and 'below' itself is ambiguous. 

I don't think "and" makes things harder to follow, but if we don't want to do that, I'd argue for no change.

**Comment by mnot** [comment]
I'm not hearing any strong feelings from @reschke or @royfielding so I'm inclined to close. Please reopen if you disagree.
