### ISSUE TITLE
Martin Duke COMMENT draft-ietf-httpbis-messaging-16

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#860]
Martin Duke has entered the following ballot position for
draft-ietf-httpbis-messaging-16: No Objection

When responding, please keep the subject line intact and reply to all
email addresses included in the To and CC lines. (Feel free to cut this
introductory paragraph, however.)

Please refer to https://www.ietf.org/iesg/statement/discuss-criteria.html
for more information about DISCUSS and COMMENT positions.

The document, along with other ballot positions, can be found here:
https://datatracker.ietf.org/doc/draft-ietf-httpbis-messaging/

COMMENT:

- [X] (3.3)  "Alternatively, it might be better to redirect the request to a safe
resource that explains how to obtain a new client."

Did you mean "obtain a new user agent?"

Editors: a user agent is a client, but not every client is a user agent. IMHO we really want to say "client" here.

- [X] (7.1) "recipients MUST anticipate potentially large decimal numerals"

s/decimal/hexidecimal (?) The chunk-size is in hex.

Editors: https://github.com/httpwg/http-core/commit/cf84cd118c77dcc796b3eac65cfc06696f8ab072

- [x] (10) This section could use an introductory paragraph. It is not at all clear
from the text why someone would enclose message as data or in what context this
would occur.

Editors: https://github.com/httpwg/http-core/issues/860#issuecomment-872753489

**Comment by mnot** [comment]
> (10) This section could use an introductory paragraph. It is not at all clear
from the text why someone would enclose message as data or in what context this
would occur.

I don't think that adds a lot of value; sometimes people want a format for a message; this provides it.

**Comment by mnot** [comment]
Can this issue be closed?

**Comment by reschke** [comment]
I think so.
