### ISSUE TITLE
Should we return only headers on HEAD requests with unsupported protocol mentioned in HTTP/1.1 syntax?

### ISSUE THREAD

**Issue by RajeevaLochana** [httpwg/http-core#861]
If someone requests:
```
HEAD / HTTP/5.0
Host: somehostname
```
Should we return:
```
HTTP/1.1 505 HTTP Version Not Supported
Date: some-date-header-stuff
Server: Server-Software
Connection: close
more-headers: their-values
```

Or should we return:
```
HTTP/1.1 505 HTTP Version Not Supported
Date: some-date-header-stuff
Server: Server-Software
Connection: close
more-headers: their-values

With some content explaining the error, even though it is a HEAD request
```

Also, what about `HEAD invaliduri HTTP/1.1\r\nHost: somehostname`? Should we return the headers only, or should we return the body too?

**Comment by reschke** [comment]
a) I don't think it matters in practice.

b) The reponse needs to use a version that describes the format, so it can't be 5.0. In practice, it would need to be 1.0 or 1.1 (when the request was received as plain text over HTTP).

**Comment by RajeevaLochana** [comment]
> a) I don't think it matters in practice.

Hmm... Apache and Nginx seem to return the headers only

**Comment by reschke** [comment]
The syntax is not correct. There is no HTTP 5.0.

**Comment by reschke** [comment]
> Also, what about GET invaliduri HTTP/1.1\r\nHost: somehostname? Should we return the headers only, or should we return the body too?

Did mean to say HEAD here?

**Comment by RajeevaLochana** [comment]
> > Also, what about GET invaliduri HTTP/1.1\r\nHost: somehostname? Should we return the headers only, or should we return the body too?
> 
> Did mean to say HEAD here?

Yes, accident

**Comment by reschke** [comment]
So HEAD-with-invalid-URI is a completely separate question. It depends a bit on how concretely the URI is invalid. Example?

**Comment by RajeevaLochana** [comment]
> So HEAD-with-invalid-URI is a completely separate question. It depends a bit on how concretely the URI is invalid. Example?

An example was given right there, (the uri part not beginning with a forward slash).

**Comment by reschke** [comment]
Neither of these conform to the ABNF for request-line, so a server should return a 400 Bad Request. Whether that contains a body is really not important, because there's no expectation that communication can continue with that client being that broken.
