### ISSUE TITLE
Via and default ports

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#865]
Source: #857 

> (7.6.3) Via
> 
> "If a port is not provided, a recipient MAY interpret that as meaning it was
> received on the default TCP port, if any, for the received-protocol."
> 
> So if received-protocol is "3", it's a UDP port.
> 
> If received-protocol is "1" or "1.1", is the default port 80 or 443? IIUC the
> scheme isn't included to determine this.

**Comment by mnot** [comment]
The non-obvious thing here is that `received-protocol` for HTTPS is `HTTP`, which means that for HTTPS connections, the port is _never_ default and always needs to be explicit.

So, the minimal correction here is to note that in prose. 

A more invasive fix would be to register `HTTPS` in [the upgrade token registry](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#upgrade.token.registry).

**Comment by royfielding** [comment]
It's completely irrelevant to the recipient what port number was used for an upstream intermediary, which is why it says MAY here.

**Comment by mnot** [comment]
There are two issues here:

1) The protocol-name doesn't reflect the scheme in use, for HTTPS, it's still 'HTTP'. The practical implication of that is that when HTTPS is used, the port needs to be explicit, even if it's the default for HTTPS. A clarifying note might help here.

2) HTTP/3 uses UDP, not TCP. Omitting 'TCP' from the MAY requirement might help.

**Comment by royfielding** [comment]
This is for Via. HTTPS is not a separate protocol. "https" is a scheme that, among other things, doesn't allow an intermediary to forward HTTP messages until they are beyond the origin secured connection (and hence no longer HTTP/TLS). Whatever the post-TLS origin does to forward its messages via CDN or downstream origins is beyond the scope here.

**Comment by royfielding** [comment]
Yes, we can just remove TCP from that sentence.

**Comment by martinduke** [comment]
That would be acceptable.
