### ISSUE TITLE
who "perform's" a request?

### ISSUE THREAD

**Issue by kaduk** [httpwg/http-core#866]
-semantics currently uses "perform" both in the context of a client performing a request and a server performing it.  There is also mention of the server "servicing" the request, "fulfilling" it, etc.  While a full normalization of terminology is probably too much to ask for at this point, having the server "perform" the request (vs "perform the requested operation") seemed an unusual enough phrasing to raise the question.

**Comment by mnot** [comment]
I don't think creating alignment in terminology here is worthwhile; I checked each instance of 'perform' and found them unambiguous.

**Comment by reschke** [comment]
+1 to close
