### ISSUE TITLE
Cache lists HTTP/1.1 as a normative reference when it could be informative

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#911]
We spent all that time removing normative references from Semantics to HTTP/1.1 and yet Cache has several "see other" kinds of references to HTTP/1.1 (for security considerations) and then lists it as normative reference.

I think this can be fixed by the RFC editor.

**Comment by mnot** [comment]
Odd. I know we did the work to enable this; did we just forget to actually change the reference type?

**Comment by reschke** [comment]
I prefer fixing things as early as possible. Also, more feedback might come in before approval...
