### ISSUE TITLE
RFC 5322 is not cited normatively, yet used in the ABNF

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#924]
From https://github.com/httpwg/http-core/issues/914:

> Should RFC 5322 be normative? We rely on it for, e.g., the "mailbox" ABNF construction.

**Comment by reschke** [comment]
This is unchanged from RFC 7231. If the concern is about the ABNF dependency, the simplest possible fux would be to remove the formal ABNF, and stick with the existing prose (which says "ought to be..").

**Comment by royfielding** [comment]
just make it a normative reference
