### ISSUE TITLE
Content-MD5

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#93]
The deprecation of Content-MD5 in 7231 was a bit too subtle; it's only mentioned in a change note, and the registry wasn't updated.

**Comment by reschke** [comment]
How exactly should we update the registry?

**Comment by mnot** [comment]
change its status there to `obsoleted`, as it has for other selected headers.

**Comment by reschke** [comment]
History: https://trac.ietf.org/trac/httpbis/ticket/178

We *removed* the header field, which is different from deprecation (which we did for a new status codes). The reason might be that we hoped that a replacement for Content-MD5 would surface, and that spec would then obsolete C-MD5.

Can't we just instruct IANA to update the registry? It would be weird to talk about Content-MD in the new spec, when the previous one didn't have it (except in the "changes" section).

**Comment by mnot** [comment]
We can try, or we can put it in IANA considerations only.

**Comment by mnot** [comment]
Proposal:

Add to the [table in 4.1](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.names):

| Content-MD5 | http | obsoleted | RFC7231, Appendix B |

**Comment by reschke** [comment]
My proposal is to leave the spec alone and just tell IANA.

**Comment by royfielding** [comment]
+1 to just telling IANA.

**Comment by mnot** [comment]
OK, will bring it up on the mailing list and see how that goes.

**Comment by mnot** [comment]
Brought up on the ietf-message-headers list: https://mailarchive.ietf.org/arch/msg/ietf-message-headers/ngv6EIWfWjJCIR3ilxDn8OEH38w

**Comment by aamelnikov** [comment]
IANA/IESG prefers for the action to be recorded somewhere. So I think mentioning this in a future RFC would be the best.
If people think that this is urgent, I can ask IESG approve obsoletion.

**Comment by mcmanus** [comment]
I think its fine to do this in the IANA considerations of http-core itself.
perhaps with 1 sentence explaining the situation.

**Comment by mnot** [comment]
As per discussion in #188, should this be _deprecated_, not _obsoleted_?

**Comment by royfielding** [comment]
As Julian said, if we still define the header field it is deprecated; if we don't define the header field (meaning its only definition is in obsolete documents) then it is obsoleted.
