### ISSUE TITLE
Section 7.7

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#930]
In semantics 7.7:

> A proxy MUST NOT modify the "absolute-path" and "query" parts of the received target URI when forwarding it to the next inbound server, except as noted above to replace an empty path with "/" or "*".

I found where (in the discussion of normalization in §4.2.3) we say to
replace the empty path with "/" for non-OPTIONS requests. I couldn't
find anywhere "above" where it was noted to replace an empty path with
"*" (presumably, for the OPTIONS requests), though.

**Comment by royfielding** [comment]
This is a reference to text that was moved to HTTP/1.1 because it is version specific. I suggest we replace it with

> A proxy MUST NOT modify the "absolute-path" and "query" parts of the received target URI when forwarding it to the next inbound server except as required by that forwarding protocol. For example, a proxy forwarding a request to an origin server via HTTP/1.1 will replace an empty path with "/" (Section 3.2.1 of [HTTP/1.1]) or "*" (Section 3.2.4 of [HTTP/1.1]), depending on the request method.

**Comment by mnot** [comment]
LGTM
