### ISSUE TITLE
More Permissive Syntax for "Accept-Encoding"

### ISSUE THREAD

**Issue by felixhandte** [httpwg/http-core#932]
Yesterday I circulated a [proposal on the mailing list](https://lists.w3.org/Archives/Public/ietf-http-wg/2021JulSep/0137.html) for an option that could be added to content-coding identifiers in the "Accept-Encoding" header. @reschke pointed out that such an option is not permitted by the [syntax of "Accept-Encoding"](https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.4). Although "Accept-Encoding" looks like a list of parameterized tokens, only a single parameter (the qvalue) is allowed.

I would like the WG to consider relaxing that restriction. (Perhaps this could be part of normalizing the header into an `sf-list`!)

Aside from the use case that motivated this topic linked above, I myself have (erroneously, apparently) used options in the "Accept-Encoding" header in a different context, to negotiate the use of dictionaries in a dictionary-based compression scheme. And I think other uses are not hard to imagine.

OTOH, obviously this would be a change to an important header, which poses a real compatibility risk. My hope would be that because existing implementations have to handle (or at least strip out) qvalues, that they would be successful in stripping out other parameters as well. So the actual impact might be quite small, especially since the presumed fallback would be responding without an encoding, rather than failing the request.

**Comment by reschke** [comment]
I don't think we can do this at this point of time.
