### ISSUE TITLE
Proof of work as DDOS mitigation

### ISSUE THREAD

**Issue by earonesty** [httpwg/http-core#935]
http2 tls negotiation can cause a high server load if an attacker repeatedly requests negotiations that require public key production.

one way to mitigate this is to optionally require a proof of work.

the server can send a nonce to the client that calculates a small proof of work in response.   

https://simulx.medium.com/adaptive-proof-of-work-for-socket-connection-establishment-1eccf3817e90

even a very (<1ms on 1ghz cpu) proof of work can prevent denial of service attacks, and can be made adaptive

im not sure where best to propose this properly

**Comment by mnot** [comment]
The best thing to do would be to bring it up on the mailing list, or write an internet-draft (but the mailing list is probably a better and easier first step).

I remember this being discussed while HTTP/2 was being developed, but a quick search of the minutes repo didn't turn anything up.

**Comment by earonesty** [comment]
i did try sending to the list (which i subscribe to), seemed to bounce.   (never made it into the archives)

**Comment by mnot** [comment]
Hm. Could you forward the bounce to `mnot@mnot.net`? Thanks.
