### ISSUE TITLE
Section 16.3.1: is a specification required for non-permanent field registrations?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#950]
Registration requests consist of at least the following information:
    [...]
    Specification document(s):
    Reference to the document that specifies the field, preferably

If the registration consists of "at least" a group of information that
includes a specification document, doesn't that mean the policy is
always "Specification Required", not just for permanent registrations?

**Comment by mnot** [comment]
I think the intent here was to encourage but not require a specification for provisional registration. Will PR.
