### ISSUE TITLE
Selected [representation, response]

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#958]
We use the phrases 'selected representation' and 'selected response' in Semantics and Caching (respectively) to refer to two completely different concepts.

Can we do better?

**Comment by royfielding** [comment]
No

**Comment by royfielding** [comment]
I think the two concepts match pretty well (and are used correctly in the four sentences). However, I also think that "chosen response" would be okay given it is only used in four places. I really don't think it needs a separate definition, since it means what the two words mean. So, maybe.

**Comment by royfielding** [comment]
It was actually used in a few more places as the response selected. I think I found all of them.
