### ISSUE TITLE
Allow: response after authentication

### ISSUE THREAD

**Issue by dilyanpalauzov** [httpwg/http-core#97]
In the [description for the `Allow` header](https://tools.ietf.org/html/rfc7231#section-7.4.1) isn't mentioned, whether the result shall depend on the authenticated user.  E.g. whether `OPTIONS -> Allow: DELETE` shall be returned, if the current user is not entitled to perform DELETE, but another user can do so.

Does the specification skip talking about of the authentication in regards of `Allow` on purpose?

**Comment by dilyanpalauzov** [comment]
There are different opinions how to understand this, in particular whether the returned list shall be the same for all recipients or also take into account the authorization of the recipient.

**Comment by reschke** [comment]
I understand that there were different opinions. I disagree that the spec text supports that.

**Comment by dilyanpalauzov** [comment]
Does the spec say that the authorization shall be taken into account when the `Allow:`-list is generated?

**Comment by reschke** [comment]
It says what I quoted above. Authentication/Authorization isn't mentioned there.

**Comment by dilyanpalauzov** [comment]
What is the use of returned `Allow: GET HEAD DELETE` if the requester cannot do DELETE and the server knows this when it generates the `Allow` response?

**Comment by reschke** [comment]
It seems you want to discuss what the spec should have said. That's different from clarifying the existing use.

**Comment by dilyanpalauzov** [comment]
This was moved to ietf-http-wg@w3.org.
