### ISSUE TITLE
Align text about not registering new media type parameters named "q" with IANA note

### ISSUE THREAD

**Issue by fpalombini** [httpwg/http-core#970]
The text in the document says:

> Future media types are discouraged from registering any parameter named "q".

The Media Type Designated Experts' suggested to make that stronger, and have the following note on the [IANA registry itself](https://www.iana.org/assignments/media-types/media-types.xhtml):

> Future media types are prohibited from registering any parameter named "q".

Let's agree on either "discouraged" or "prohibited", and align the text in the document and in the IANA registry note.

**Comment by reschke** [comment]
I believe what the IANA registry says is good, so what's left to do is to align our spec text with that.

My understanding is that no new text in the IANA Considerations is needed, as the change to the registry already happened.

**Comment by fpalombini** [comment]
If we agree to add the reference to this RFC once it's published, I can ask IANA to do that.

**Comment by reschke** [comment]
Good point. We *could* add that to the IANA Considerations. Should I?

**Comment by fpalombini** [comment]
I think that would make sense. Let's hear from others.
