### ISSUE TITLE
Field Extensibility: what to do with non-deployed fields

### ISSUE THREAD

**Issue by annevk** [httpwg/http-core#986]
There are a number of fields that got provisionally registered in the early days of the development of the CORS protocol. They are currently marked "deprecated". As far as I know they have not been implemented and are not in use. Should they be kept in the registry? If so, should they be marked as "obsoleted" with the Specification document(s) field as N/A?

Should there be considerations for existing fields in the Field Extensibility section of HTTP Semantics?

(I initially though there was a larger issue with HTTP Semantics, but it seems that's due to the registry pointing to -19 which does not acknowledge the "deprecated" and "obsoleted" statuses yet.)

**Comment by mnot** [comment]
`obsoleted` probably makes sense for them; if you make requests we can process them (it'll be easier if someone authoritative from w3c gives a blessing). The spec links should probably stay, just for history.

**Comment by annevk** [comment]
I filed them as issues 10 through 13. Hopefully @plehegar can +1 as needed, though the specification reference I found for them should demonstrate quite clearly they are obsolete. (I also found a bunch of other header names in earlier and later drafts that never ended up in the registry, FWIW.)

I guess that leaves the question to what extent HTTP Semantics ought to give guidance on this.

**Comment by reschke** [comment]
We either need to answer this now (because we're about to publish the RFCs), or decide to close it.

**Comment by mnot** [comment]
Those issues have been dealt wit. @annevk what kind of guidance would you expect? Like any registry with an expert, you can make requests.

**Comment by annevk** [comment]
I guess I would expect someplace to state when "deprecated" and "obsoleted" are appropriate to use. Leaving that entirely to experts seems reasonable, though maybe https://github.com/protocol-registries/http-fields#choosing-the-right-status could be flushed out a bit more then.

**Comment by mnot** [comment]
See https://github.com/protocol-registries/http-fields/commit/473a721181428cb35f7dc38d93d968f6f416c160.
